module.exports = {
  "MIX": {
    "label": "🎲 Aleatorio (Mix)",
    "hint": "Cualquier cosa",
    "words": [] 
  },
  "FÁCILES": {
    "label": "⭐ Palabras Fáciles",
    "hint": "Para todos los públicos",
    "words": [
        { word: "Sol", hint: "Círculo" },
        { word: "Luna", hint: "Media" },
        { word: "Estrella", hint: "Picos" },
        { word: "Nube", hint: "Algodón" },
        { word: "Árbol", hint: "Tronco y círculo" },
        { word: "Flor", hint: "Pétalos simples" },
        { word: "Casa", hint: "Cuadrado con triángulo" },
        { word: "Puerta", hint: "Rectángulo" },
        { word: "Ventana", hint: "Cuadrado con cruz" },
        { word: "Coche", hint: "Rectángulo" },
        { word: "Rueda", hint: "Círculo" },
        { word: "Pelota", hint: "Círculo" },
        { word: "Corazón", hint: "Forma clásica" },
        { word: "Flecha", hint: "Línea con punta" },
        { word: "Montaña", hint: "Triángulos" },
        { word: "Río", hint: "Línea ondulada" },
        { word: "Sol con gafas", hint: "Sol + dos rayas" },
        { word: "Sombrero", hint: "Óvalo con ala" },
        { word: "Gafas", hint: "Dos" },
        { word: "Zapato", hint: "Forma curva" },
        { word: "Calcetín", hint: "L invertida" },
        { word: "Manzana", hint: "Círculo" },
        { word: "Plátano", hint: "Media" },
        { word: "Pera", hint: "bola" },
        { word: "Botella", hint: "Rectángulo" },
        { word: "Vaso", hint: "Trapecio" },
        { word: "Taza", hint: "Círculo" },
        { word: "Llave", hint: "dientes" },
        { word: "Candado", hint: "U invertida" },
        { word: "Reloj", hint: "palos" },
        { word: "Teléfono", hint: "Rectángulo" },
        { word: "Libro", hint: "abierto" },
        { word: "Lápiz", hint: "punta" },
        { word: "Papel", hint: "Rectángulo" },
        { word: "Cama", hint: "Rectángulo" },
        { word: "Mesa", hint: "Rectángulo" },
        { word: "Silla", hint: "Cuatro palos" },
        { word: "Escalera", hint: "Rayas" },
        { word: "Puente", hint: "Arco" },
        { word: "Caracol", hint: "Espiral" },
        { word: "Serpiente", hint: "Línea en S" },
        { word: "Pez", hint: "Óvalo con cola" },
        { word: "Barco", hint: "Triángulo sobre línea" },
        { word: "Avión", hint: "Cruz" },
        { word: "Cohete", hint: "Triángulo con fuego" },
        { word: "Bandera", hint: "Palo" },
        { word: "Semáforo", hint: "Tres" },
        { word: "Cactus", hint: "Palos" },
        { word: "Helado", hint: "bola" },
        { word: "Pastel", hint: "Capas" },
        { word: "Guitarra", hint: "Cuerpo y mástil" },
        { word: "Batería", hint: "Círculos" },
        { word: "Micrófono", hint: "palo" }
    ]
  },
  "COMIDA": {
    "label": "🍕 Comida y Bebida",
    "hint": "Es algo comestible o bebible",
    "words": [
      { word: "Pizza", hint: "Ptolemaico" },
      { word: "Sushi", hint: "Xenofobia" },
      { word: "Hamburguesa", hint: "Simetría" },
      { word: "Paella", hint: "Helicóptero" },
      { word: "Tacos", hint: "Metacarpo" },
      { word: "Espaguetis", hint: "Caligrafía" },
      { word: "Helado", hint: "Arqueología" },
      { word: "Chocolate", hint: "Epistemología" },
      { word: "Cerveza", hint: "Olfato" },
      { word: "Vino", hint: "Sedimentación" },
      { word: "Agua", hint: "Osmosis" },
      { word: "Café", hint: "Fototropismo" },
      { word: "Queso", hint: "Cuotidiano" },
      { word: "Jamón", hint: "Cetáceo" },
      { word: "Huevo Frito", hint: "Simetría" },
      { word: "Croquetas", hint: "Efervescencia" },
      { word: "Ensalada", hint: "Fotosíntesis" },
      { word: "Manzana", hint: "Manzana" },
      { word: "Plátano", hint: "Inclinómetro" },
      { word: "Kebab", hint: "Samurái" },
      { word: "Tortilla de Patatas", hint: "Cero" },
      { word: "Gazpacho", hint: "Isotermo" },
      { word: "Pancakes", hint: "Servidumbre" },
      { word: "Galletas", hint: "Litosfera" },
      { word: "Donuts", hint: "Topología" },
      { word: "Aceite de Oliva", hint: "Lubricitación" },
      { word: "Salchichón", hint: "Helicoide" },
      { word: "Lentejas", hint: "Dioptrías" },
      { word: "Arroz con Leche", hint: "Sinestesia" },
      { word: "Batido", hint: "Agitación" },
      { word: "Gominolas", hint: "Polímero" },
      { word: "Mofongo", hint: "Fusión" },
      { word: "Ceviche", hint: "Desnaturalización" },
      { word: "Ramen", hint: "Seísmo" },
      { word: "Falafel", hint: "Inmersión" },
      { word: "Miso", hint: "Bacteriología" },
      { word: "Tahini", hint: "Molturación" },
      { word: "Kimchi", hint: "Anaerobiosis" },
      { word: "Tempura", hint: "Subacuático" },
      { word: "Poutine", hint: "Criogénico" },
      { word: "Croissant", hint: "Tumefacción" },
      { word: "Tiramisú", hint: "Levitación" },
      { word: "Pavlova", hint: "Meringue" },
      { word: "Macarrón", hint: "Almohada" },
      { word: "Mozzarella", hint: "Viscoelástico" },
      { word: "Hummus", hint: "Licuefacción" },
      { word: "Wasabi", hint: "Capsaicina" },
      { word: "Quinua", hint: "Andino" }
    ]
  },
  "OBJETOS": {
    "label": "💡 Objetos Cotidianos",
    "hint": "Es un objeto inanimado",
    "words": [
      { word: "Mesa", hint: "Planaridad" },
      { word: "Silla", hint: "Ergonomía" },
      { word: "Teléfono", hint: "Frecuencia" },
      { word: "Ordenador", hint: "Algoritmo" },
      { word: "Cama", hint: "Homeostasis" },
      { word: "Cuchillo", hint: "Filo" },
      { word: "Tenedor", hint: "Prensión" },
      { word: "Coche", hint: "Combustión" },
      { word: "Reloj", hint: "Cronometría" },
      { word: "Gafas", hint: "Refracción" },
      { word: "Llaves", hint: "Cerradura" },
      { word: "Cartera", hint: "Portabilidad" },
      { word: "Mochila", hint: "Ergonomía" },
      { word: "Lámpara", hint: "Fotometría" },
      { word: "Espejo", hint: "Especularidad" },
      { word: "Cepillo de Dientes", hint: "Higiene" },
      { word: "Papel Higiénico", hint: "Celulosa" },
      { word: "Sartén", hint: "Conducción" },
      { word: "Toalla", hint: "Capilaridad" },
      { word: "Zapatos", hint: "Tracción" },
      { word: "Calcetines", hint: "Termorregulación" },
      { word: "Mando a Distancia", hint: "Infrarrojo" },
      { word: "Cargador", hint: "Amperaje" },
      { word: "Auriculares", hint: "Transductor" },
      { word: "Botella", hint: "Hermetismo" },
      { word: "Libro", hint: "Papirografía" },
      { word: "Bolígrafo", hint: "Capilaridad" },
      { word: "Tijeras", hint: "Palanca" },
      { word: "Microondas", hint: "Magnetrón" },
      { word: "Nevera", hint: "Ciclo Carnot" },
      { word: "Binoculares", hint: "Prisma" },
      { word: "Termómetro", hint: "Dilatación" },
      { word: "Brújula", hint: "Declinación" },
      { word: "Candado", hint: "Pasador" },
      { word: "Cadena", hint: "Anillo" },
      { word: "Candela", hint: "Luminancia" },
      { word: "Incienso", hint: "Volatilidad" },
      { word: "Espejo retrovisor", hint: "Perspectiva" },
      { word: "Extinguidor", hint: "Sofocación" },
      { word: "Enchufe", hint: "Voltaje" },
      { word: "Interruptor", hint: "Contacto" },
      { word: "Bombilla", hint: "Filamento" },
      { word: "Vela", hint: "Propulsión" },
      { word: "Mapamundi", hint: "Proyección" },
      { word: "Telescopio", hint: "Aberración" },
      { word: "Microscopio", hint: "Aumentro" },
      { word: "Lupa", hint: "Aumento" },
      { word: "Cinturón", hint: "Circunferencia" },
      { word: "Corbata", hint: "Nudo" },
      { word: "Pañuelo", hint: "Absorción" },
      { word: "Bufanda", hint: "Aislamiento" },
      { word: "Sombrero", hint: "Sombrilla" },
      { word: "Gorro", hint: "Recubrimiento" },
      { word: "Paraguas", hint: "Impermeabilidad" }
    ]
  },
  "ACCIONES": {
    "label": "🏃 Acciones (Verbos)",
    "hint": "Es algo que se hace",
    "words": [
      { word: "Correr", hint: "Cinética" },
      { word: "Saltar", hint: "Parábola" },
      { word: "Dormir", hint: "Letargo" },
      { word: "Comer", hint: "Ingesta" },
      { word: "Beber", hint: "Hidratación" },
      { word: "Leer", hint: "Decodificación" },
      { word: "Escribir", hint: "Caligrafía" },
      { word: "Cantar", hint: "Vibrato" },
      { word: "Bailar", hint: "Sincronización" },
      { word: "Cocinar", hint: "Maillard" },
      { word: "Llorar", hint: "Lacrimal" },
      { word: "Reír", hint: "Hilariedad" },
      { word: "Besar", hint: "Osculación" },
      { word: "Abrazar", hint: "Circunvalación" },
      { word: "Pelear", hint: "Confrontación" },
      { word: "Conducir", hint: "Tracción" },
      { word: "Nadar", hint: "Propulsión" },
      { word: "Volar", hint: "Sustentación" },
      { word: "Pintar", hint: "Pigmentación" },
      { word: "Estudiar", hint: "Mnemotécnica" },
      { word: "Trabajar", hint: "Producción" },
      { word: "Jugar", hint: "Lúdica" },
      { word: "Limpiar", hint: "Ablución" },
      { word: "Comprar", hint: "Transacción" },
      { word: "Vender", hint: "Enajenación" },
      { word: "Robar", hint: "Apropiación" },
      { word: "Mentir", hint: "Falseamiento" },
      { word: "Gritar", hint: "Fonación" },
      { word: "Susurrar", hint: "Murmuración" },
      { word: "Pensar", hint: "Cognición" },
      { word: "Estornudar", hint: "Expulsión" },
      { word: "Toser", hint: "Reflejo" },
      { word: "Suspirar", hint: "Exhalación" },
      { word: "Jadear", hint: "Disnea" },
      { word: "Bostezo", hint: "Bostezar" },
      { word: "Gruñir", hint: "Regustación" },
      { word: "Ronronear", hint: "Vibración" },
      { word: "Silbar", hint: "Frecuencia" },
      { word: "Tararear", hint: "Zumbido" },
      { word: "Murmurar", hint: "Susurración" },
      { word: "Tartamudear", hint: "Disartria" },
      { word: "Balbucear", hint: "Balbucencia" },
      { word: "Protestar", hint: "Objeción" },
      { word: "Suplicar", hint: "Petición" },
      { word: "Exigir", hint: "Imposición" },
      { word: "Implorar", hint: "Rogativa" },
      { word: "Amenazar", hint: "Conminación" },
      { word: "Perseguir", hint: "Persecución" },
      { word: "Tropezar", hint: "Escollo" },
      { word: "Arrastrarse", hint: "Reptación" },
      { word: "Escalar", hint: "Ascensión" },
      { word: "Sumergirse", hint: "Inmersión" },
      { word: "Deslizar", hint: "Deslizamiento" },
      { word: "Tambalear", hint: "Oscilación" }
    ]
  },
  "PERSONAJES_PUBLICOS": {
    "label": "🌍 Personajes Públicos",
    "hint": "Persona real conocida",
    "words": [
      { word: "Messi", hint: "Biomecánica" },
      { word: "Cristiano Ronaldo", hint: "Musculatura" },
      { word: "Shakira", hint: "Cadera" },
      { word: "Michael Jackson", hint: "Antigraviedad" },
      { word: "Einstein", hint: "Curvatura" },
      { word: "Picasso", hint: "Simultaneidad" },
      { word: "Napoleón", hint: "Cartografía" },
      { word: "Cleopatra", hint: "Ptolemaico" },
      { word: "Elon Musk", hint: "Fusión" },
      { word: "Bill Gates", hint: "Algoritmo" },
      { word: "Obama", hint: "Oratoria" },
      { word: "Trump", hint: "Mercadotecnia" },
      { word: "Newton", hint: "Gravitación" },
      { word: "Tesla", hint: "Electromagnética" },
      { word: "Mozart", hint: "Sinfonía" },
      { word: "Beethoven", hint: "Sordera" },
      { word: "Madonna", hint: "Provocación" },
      { word: "Beyoncé", hint: "Pirotecnia" },
      { word: "Leonardo da Vinci", hint: "Polímata" },
      { word: "Oprah Winfrey", hint: "Empoderación" },
      { word: "Kim Kardashian", hint: "Narcisismo" },
      { word: "Dwayne Johnson", hint: "Hipertrofia" },
      { word: "Taylor Swift", hint: "Narratología" },
      { word: "Ariana Grande", hint: "Rango" },
      { word: "The Weeknd", hint: "Nostalgia" },
      { word: "Kanye West", hint: "Megalomanía" },
      { word: "Rihanna", hint: "Reinvención" },
      { word: "Lady Gaga", hint: "Experimentación" },
      { word: "Coldplay", hint: "Melancolía" },
      { word: "The Beatles", hint: "Sincronización" },
      { word: "Freddie Mercury", hint: "Falsete" },
      { word: "David Bowie", hint: "Metamorfosis" },
      { word: "Pink Floyd", hint: "Psicodelia" },
      { word: "Steven Spielberg", hint: "Nostalgia" },
      { word: "Martin Scorsese", hint: "Violencia" },
      { word: "James Cameron", hint: "Tecnología" },
      { word: "Quentin Tarantino", hint: "Diálogos" },
      { word: "Christopher Nolan", hint: "Temporalidad" },
      { word: "Greta Thunberg", hint: "Activismo" },
      { word: "Malala Yousafzai", hint: "Educación" },
      { word: "Gal Gadot", hint: "Femineidad" },
      { word: "The Rock", hint: "Metamorfosis" },
      { word: "Tom Hanks", hint: "Empatía" },
      { word: "Meryl Streep", hint: "Versatilidad" },
      
      // Presidentes España desde 1980
      { word: "Adolfo Suárez", hint: "Cambio" },
      { word: "Leopoldo Calvo-Sotelo", hint: "Brevedad" },
      { word: "Felipe González", hint: "Ideología" },
      { word: "José María Aznar", hint: "Conservadurismo" },
      { word: "José Luis Rodríguez Zapatero", hint: "Reformismo" },
      { word: "Mariano Rajoy", hint: "Austeridad" },
      { word: "Pedro Sánchez", hint: "Adaptabilidad" },
      
      // Cantantes más famosos en España
      { word: "Julio Iglesias", hint: "Sentimentalismo" },
      { word: "Miguel Bosé", hint: "Androginia" },
      { word: "Enrique Iglesias", hint: "Globalización" },
      { word: "Rosalía", hint: "Hibridación" },
      { word: "Alejandro Sanz", hint: "Lirismo" },
      { word: "David Bisbal", hint: "Mediatización" },
      { word: "Maluma", hint: "Reggaeton" },
      { word: "Bad Bunny", hint: "Iconoclastia" },
      { word: "J Balvin", hint: "Globalización" },
      { word: "Rauw Alejandro", hint: "Hibridación" },
      { word: "Karol G", hint: "Empoderamiento" },
      { word: "Myke Towers", hint: "Minimalismo" },
      
      // Personajes históricos guerras famosas
      { word: "Adolf Hitler", hint: "Totalitarismo" },
      { word: "Benito Mussolini", hint: "Imperialismo" },
      { word: "Napoleón Bonaparte", hint: "Ambición" },
      { word: "Winston Churchill", hint: "Resiliencia" },
      { word: "Franklin D. Roosevelt", hint: "Humanitarismo" },
      { word: "Joseph Stalin", hint: "Represión" },
      { word: "Ernesto Che Guevara", hint: "Idealismo" },
      { word: "Fidel Castro", hint: "Dogmatismo" },
      { word: "Osama bin Laden", hint: "Extremismo" },
      { word: "Carlomagno", hint: "Expansionismo" },
  
      
      { word: "David Beckham", hint: "Estilismo" },
      { word: "Zendaya", hint: "Minucia" },
      { word: "Justin Bieber", hint: "Idolatría" },
      { word: "Drake", hint: "Narrativa" },
      { word: "Cardi B", hint: "Autenticidad" },
      { word: "Rihanna", hint: "Multitarea" },
      { word: "Beyoncé", hint: "Perfeccionismo" },
      { word: "Miley Cyrus", hint: "Transformación" },
      { word: "Emma Watson", hint: "Feminismo" },
      { word: "Kendall Jenner", hint: "Privilegio" },
      { word: "Aitana Ocaña", hint: "Visualismo" },
      { word: "ElrubiusOMG", hint: "Entretenimiento" },
      { word: "TheGrefg", hint: "Gamificación" },
      { word: "Ibai Llanos", hint: "Espontaneidad" },
      { word: "AuronPlay", hint: "Ironía" },
      { word: "Willyrex", hint: "Nostalgia" },
      { word: "Vegetta777", hint: "Consistencia" }
    ]
  },

  "CLASH_ROYALE": {
    "label": "👑 Clash Royale",
    "hint": "Juego de Supercell",
    "words": [
      { word: "Mega Caballero", hint: "Magnificencia" },
      { word: "Montapuercos", hint: "Ingeniería" },
      { word: "Larry", hint: "Deificación" },
      { word: "Princesa", hint: "Estratificación" },
      { word: "Tronco", hint: "Arboricultura" },
      { word: "Espejo", hint: "Dualismo" },
      { word: "Cohete", hint: "Trayectoria" },
      { word: "Chispitas", hint: "Minutería" },
      { word: "Gigante Noble", hint: "Aristocracia" },
      { word: "Minero", hint: "Extracción" },
      { word: "Golem", hint: "Artificialidad" },
      { word: "Ejército de Esqueletos", hint: "Mortandad" },
      { word: "Sabueso de Lava", hint: "Magmatismo" },
      { word: "Bandida", hint: "Delincuencia" },
      { word: "P.E.K.K.A", hint: "Automatismo" },
      { word: "Mago Eléctrico", hint: "Conductividad" },
      { word: "Globo Bombástico", hint: "Flotabilidad" },
      { word: "Ballesta", hint: "Proyectilería" },
      { word: "Torre Infernal", hint: "Infierno" },
      { word: "Espíritu de Hielo", hint: "Criogenia" },
      { word: "Carta", hint: "Cartografía" },
      { word: "Elixir", hint: "Alquimia" },
      { word: "Arena", hint: "Desertificación" },
      { word: "Trofeos", hint: "Trofología" },
      { word: "Derrotado", hint: "Derrota" },
      { word: "Victoria", hint: "Triunfalismo" },
      { word: "Torreta", hint: "Fortificación" },
      { word: "Rey", hint: "Monarquía" },
      { word: "Reina", hint: "Matriarcado" },
      { word: "Mago", hint: "Hermetismo" },
      { word: "Arbusto Sospechoso", hint: "Camuflaje" },
      { word: "Arqueras", hint: "Arquería" },
      { word: "Bárbaros", hint: "Salvajismo" },
      { word: "Barril de Duendes", hint: "Contenedorización" },
      { word: "Barril de Esqueletos", hint: "Mortalidad" },
      { word: "Bola de Nieve", hint: "Alud" },
      { word: "Bombardero", hint: "Bombardeo" },
      { word: "Barbaros Evolucion", hint: "Mejoramiento" },
      { word: "Caballero", hint: "Equitación" },
      { word: "Campeones", hint: "Campeonato" },
      { word: "Cartas Comunes", hint: "Ordinaridad" },
      { word: "Cartas Especiales", hint: "Excepcionalidad" },
      { word: "Cartas Legendarias", hint: "Mitología" },
      { word: "Cartas Épicas", hint: "Epopeya" },
      { word: "Cazador", hint: "Caza" },
      { word: "Cañonero", hint: "Artillería" },
      { word: "Cañón", hint: "Ordenanza" },
      { word: "Cocinero Real", hint: "Gastronomía" },
      { word: "Cofres", hint: "Atesoramiento" },
      { word: "Coronas", hint: "Coronación" },
      { word: "Demoledor Duende", hint: "Demolición" },
      { word: "Dragón Eléctrico", hint: "Voltaísmo" },
      { word: "Dragón Infernal", hint: "Infernal" },
      { word: "Duende Lanzadardos", hint: "Dardismo" },
      { word: "Duendenstein", hint: "Frankenstein" },
      { word: "Duquesa de Dagas", hint: "Duquería" },
      { word: "Emperatriz Espiritual", hint: "Espiritismo" },
      { word: "Enredadera", hint: "Botánica" },
      { word: "Espíritu de Hielo", hint: "Glaciación" },
      { word: "Espíritu Sanador", hint: "Curación" },
      { word: "Evolución de Cartas", hint: "Evolución" },
      { word: "Fantasma Real", hint: "Espectrología" },
      { word: "Gigante Noble", hint: "Gigantismo" },
      { word: "Gigante Rúnica", hint: "Rúnica" },
      { word: "Horno", hint: "Combustión" },
      { word: "Leñador", hint: "Silvicultura" },
      { word: "Mazos", hint: "Juego" },
      { word: "Megacaballero", hint: "Megalomanía" },
      { word: "Mortero", hint: "Mortería" },
      { word: "Mosquetera", hint: "Mosquetería" },
      { word: "Murciélagos", hint: "Quiropterología" },
      { word: "Máquina Duende", hint: "Mecanización" },
      { word: "Pescador", hint: "Ictiología" },
      { word: "Princesa de Torre", hint: "Presidiaria" },
      { word: "Principito", hint: "Príncipe" },
      { word: "Puercos Reales", hint: "Suicultura" },
      { word: "Reclutas Reales", hint: "Reclutamiento" },
      { word: "Rompemuros", hint: "Demolición" },
      { word: "Vacío", hint: "Nihilidad" },
      { word: "Valquiria", hint: "Mitología" },
      { word: "Verdugo", hint: "Ejecución" }
    ]
  },
"FUTBOLISTAS": {
  "label": "🏃 Fútbol (Jugadores)",
  "hint": "Hemeroteca",
  "words": [
    // Balón de Oro y leyendas
    { word: "Messi", hint: "Argentum" },
    { word: "Cristiano Ronaldo", hint: "Lusitano" },
    { word: "Pelé", hint: "Tricéfalo" },
    { word: "Maradona", hint: "Albiceleste" },
    { word: "Zidane", hint: "Caligrafía" },
    { word: "Ronaldo", hint: "Fenómeno" },
    { word: "Ronaldinho", hint: "Sonrisa" },
    { word: "Platini", hint: "Hexágono" },
    { word: "Beckenbauer", hint: "Kaiser" },
    { word: "Cruyff", hint: "Herejía" },
    { word: "Gerd Müller", hint: "Depredador" },
    { word: "Johan Cruyff", hint: "Dialéctica" },
    { word: "Ferenc Puskás", hint: "Zurda" },
    { word: "Alfredo Di Stéfano", hint: "Hibridación" },
    { word: "Eusébio", hint: "Pantera" },

    // Españoles
    { word: "Iniesta", hint: "Silencio" },
    { word: "Xavi", hint: "Ritmo" },
    { word: "Piqué", hint: "Ironía" },
    { word: "Ramos", hint: "Épica" },
    { word: "Busquets", hint: "Inercia" },
    { word: "Puyol", hint: "Estoicismo" },
    { word: "Casillas", hint: "Reflejo" },
    { word: "Nacho Fernández", hint: "Versatilidad" },
    { word: "Valdés", hint: "Frialdad" },
    { word: "Gento", hint: "Vértigo" },
    { word: "Santillana", hint: "Remate" },
    { word: "Butarque", hint: "Anomalía" },

    // Compañeros Messi
    { word: "Suárez", hint: "Canino" },
    { word: "Neymar", hint: "Carnaval" },
    { word: "Busquets", hint: "Gravedad" },
    { word: "Piqué", hint: "Sarcasmo" },
    { word: "Alba", hint: "Diagonal" },
    { word: "Rakitić", hint: "Balcanes" },
    { word: "Xavi", hint: "Metrónomo" },
    { word: "Iniesta", hint: "Evaporación" },
    { word: "Puyol", hint: "Muralla" },
    { word: "Mascherano", hint: "Sacrificio" },

    { word: "Modric", hint: "Bóveda" },
    { word: "Benzema", hint: "Metamorfosis" },
    { word: "Ramos", hint: "Catarsis" },
    { word: "Xabi Alonso", hint: "Cartografía" },
    { word: "Buffon", hint: "Longevità" },
    { word: "Chiellini", hint: "Cemento" },
    { word: "Pirlo", hint: "Visión" },
    { word: "Totti", hint: "Eterno" },
    { word: "Del Piero", hint: "Clasicismo" },
    { word: "Gullit", hint: "Ecléctico" },
    { word: "Giggs", hint: "Persistencia" },
    { word: "Scholes", hint: "Precisión" },
    { word: "Gerrard", hint: "Pulmón" },
    { word: "Lampard", hint: "Llegada" },
    { word: "Vieira", hint: "Autoridad" },
    { word: "Henry", hint: "Elegancia" },
    { word: "Cannavaro", hint: "Anticipación" },
    { word: "Chiellini", hint: "Trinchera" },
    { word: "Bonucci", hint: "Salida" },
    { word: "Cafu", hint: "Autopista" },
    { word: "Roberto Carlos", hint: "Balística" },
    { word: "Thuram", hint: "Resistencia" },
    { word: "Pepe", hint: "Belicosidad" },
    { word: "Lahm", hint: "Polivalencia" },
    { word: "Alves", hint: "Hipercinesia" },
    { word: "Carvalho", hint: "Sobriedad" },

    // Liga Española e Inglesa actuales
    { word: "Mbappé", hint: "Explosión" },
    { word: "Haaland", hint: "Martillo" },
    { word: "Vinicius", hint: "Provocación" },
    { word: "Rodri", hint: "Ancla" },
    { word: "Bellingham", hint: "Ascenso" },
    { word: "Salah", hint: "Duna" },
    { word: "De Bruyne", hint: "Orfebre" },
    { word: "Van Dijk", hint: "Muralla" },
    { word: "Son Heung-min", hint: "Resorte" },
    { word: "Foden", hint: "Germen" },

    // Ganadores ligas nacionales
    { word: "Lewandowski", hint: "Instinto" },
    { word: "Neuer", hint: "Libero" },
    { word: "Müller", hint: "Oportunismo" },
    { word: "Bale", hint: "Latigazo" },
    { word: "Ibrahimovic", hint: "Narciso" },
    { word: "Cavani", hint: "Acecho" },
    { word: "Griezmann", hint: "Intersticio" },
    { word: "Agüero", hint: "Finalización" },
    { word: "Hazard", hint: "Intermitencia" },
    { word: "Panenka", hint: "Atrevimiento" },
    { word: "Yashin", hint: "Araña" },
    { word: "Gianluigi Buffon", hint: "Eternidad" },
    { word: "Cech", hint: "Casco" },
    { word: "Ter Stegen", hint: "Elasticidad" },
    { word: "Ederson", hint: "Osadía" },
    { word: "Alisson", hint: "Seguridad" },
    { word: "De Gea", hint: "Reflejos" },
    { word: "Donarumma", hint: "Gigantismo" },

    // Entrenadores que fueron jugadores
    { word: "Guardiola", hint: "Dogma" },
    { word: "Ancelotti", hint: "Templanza" },
    { word: "Zidane", hint: "Misticismo" },
    { word: "Mourinho", hint: "Antagonismo" },
    { word: "Simeone", hint: "Fervor" },
    { word: "Flick", hint: "Verticalidad" },
    { word: "Ten Hag", hint: "Estructura" },
    { word: "Pochettino", hint: "Intensidad" },
    { word: "Klopp", hint: "Presión" },
    { word: "Conte", hint: "Disciplina" },

  ]
},


  LA_PLAZA: {
        label: "🛒 La Plaza",
        hint: " (Vitamina D)",
        words: [
            // --- LUIS CRUZ ---
            { word: "Reiniciar el alfabeto", hint: "Didáctica" },
            { word: "Fade del guapo", hint: "Barbero" },
            { word: "Compruebalesbianas", hint: "Test" },
            { word: "Luis Cruz", hint: "Física" },
            { word: "Luis Cruz", hint: "Volante" }, // Por conducir mal

            // --- NACHO ---
            { word: "Chungar habitualmente", hint: "Fiesta" },
            { word: "Carnicero", hint: "Filetes" },
            { word: "Amor italiano", hint: "Erasmus" },
            { word: "Nacho", hint: "Charcutería" },
            { word: "Nacho", hint: "Entradas" },

            // --- ALBA CADELO ---
            { word: "Pinchar ruedas", hint: "Dos" },
            { word: "Racing de Santander", hint: "Sitio" },
            { word: "Racista", hint: "Alba Cadelo" },
            { word: "Las Cagigas", hint: "Ubicación" },
            { word: "Alba Cadelo", hint: "Fisioterapia" },
            { word: "Alba Cadelo", hint: "Rural" },

            // --- ALEJANDRA SILIÓ ---
            { word: "Poner correa", hint: "Mascota" },
            { word: "Odiar el garito", hint: "Antro" },
            { word: "Alejandra Silió", hint: "Embaucadora" },
            { word: "Alejandra Silió", hint: "Relaciones" },

            // --- BEA PRADO ---
            { word: "Killo", hint: "Limones" },
            { word: "Caras de asco", hint: "Expresión" },
            { word: "Zumba y Pilates", hint: "Gimnasio" },
            { word: "Bea Prado", hint: "Psicología" },
            { word: "Bea Prado", hint: "Militar" }, 

            // --- CARLOS (TÚ) ---
            { word: "Coche Autobús", hint: "Dimensiones" },
            { word: "Novio de Silvia", hint: "Cuñado" },
            { word: "Bluffer de Mus", hint: "Engaño" },
            { word: "Ex mujeriego", hint: "Pasado" },
            { word: "Carlos", hint: "Informático" },
            { word: "Carlos", hint: "Máster" },

            // --- DIEGO ACEBO (DAC) ---
            { word: "No tener bachiller", hint: "Estudios" },
            { word: "Paja táctica", hint: "Llegada" },
            { word: "Diego Acebo", hint: "Ron-cola" },
            { word: "Diego Acebo", hint: "Derrochador" },

            // --- JAPA ---
            { word: "Siete dioptrías", hint: "Ceguera" },
            { word: "Delincuente sale en el periódico", hint: "Prensa" },
            { word: "Cenicero de Potes", hint: "Tonto" },
            { word: "Villano de Setién", hint: "Antagonista" },
            { word: "Japa", hint: "Barba" },
            { word: "Japa", hint: "Leyenda" },

            // --- IKER ---
            { word: "Maestro del Poper", hint: "Nariz" },
            { word: "Queso de Potes", hint: "Olor" },
            { word: "Iker", hint: "Mecatrónico" },
            { word: "Iker", hint: "After" },

            // --- JAVIER MALIAÑO ---
            { word: "B1 de alemán", hint: "Idioma" },
            { word: "Jugador de pitos", hint: "Naipes" },
            { word: "Futuro trabajador de McDonald's", hint: "Ironía" },
            { word: "Javier Maliaño", hint: "Doble-Grado" },
            { word: "Javier Maliaño", hint: "Hamburguesa" },

            // --- LAURA ---
            { word: "La Chonda", hint: "Promiscua" },
            { word: "Fuera de juego", hint: "Reglamento" },
            { word: "Laura", hint: "Enfermería" },
            { word: "Laura", hint: "Gimnasio" },
            { word: "Laura Quintanal", hint: "Calentorra" },
            { word: "Laura", hint: "Salida" },
            { word: "Marián", hint: "Ombligo" },

            // --- LUCAS FERNÁNDEZ ---
            { word: "El Militar", hint: "Uniforme" },
            { word: "Lucas Fernández", hint: "Arma" },
            { word: "Lucas Fernández", hint: "Setién" },

            // --- LUCAS GONZÁLEZ ---
            { word: "Iceman", hint: "Sentimientos" },
            { word: "Tener Novia Andaluza", hint: "Sur" },
            { word: "Lucas González", hint: "Informático" },
            { word: "Lucas González", hint: "Hielo" },

            // --- MANUEL TRICIO ---
            { word: "Lancha de Pedreña", hint: "Bahía" },
            { word: "Aeronáutica", hint: "Aviones" },
            { word: "Manuel Tricio", hint: "Italia" },
            { word: "Manuel Tricio", hint: "Madrid" },

            // --- MARCOS FERNÁNDEZ ---
            { word: "Furgoneta gitana", hint: "Aceleración" },
            { word: "Niño Tiktok", hint: "Viral" },
            { word: "Marcos Fernández", hint: "Motor" },
            { word: "Marcos Fernández", hint: "Grado" },

            // --- MARIO GÁNDARA ---
            { word: "Meter un Sofá en el Audi", hint: "Tetris" },
            { word: "Habla ininteligible", hint: "Alcohol" },
            { word: "Mario Gándara", hint: "Correa" },
            { word: "Mario Gándara", hint: "Meca" },

            // --- MATEO VILLA ---
            { word: "Dejar la carrera", hint: "Alumno de Llados" },
            { word: "La única manera de evitar algo", hint: "Conversación" },
            { word: "Mateo Villa", hint: "Magisterio" },
            { word: "Mateo Villa", hint: "Mujeriego" },

            // --- PALOMA CADELO ---
            { word: "Polo", hint: "Vehículo" },
            { word: "Paloma Cadelo", hint: "Enfermera" },
            { word: "Paloma Cadelo", hint: "Trabajo" },

            // --- SILVIA ---
            { word: "Kai y Atos", hint: "Manada" },
            { word: "Silvia", hint: "Audi" },
            { word: "Silvia", hint: "Enfermería" },

            // --- TANIA GALLEGO ---
            { word: "Metro cincuenta", hint: "Estatura" },
            { word: "Tania Gallego", hint: "Psicología" },
            { word: "Tania Gallego", hint: "Hippie" },

            // --- TITO ---
            { word: "Mercedes", hint: "Merche" },
            { word: "Tito", hint: "Trabajo" },
            { word: "Tito", hint: "Coche" },

            // --- COMUNES Y LUGARES (CAOS TOTAL) ---
            { word: "Setién", hint: "Pueblo" }, // Japa y Lucas F
            { word: "Las Cagigas", hint: "Casas" }, 
            { word: "Mecatrónico", hint: "Taller" }, // Iker y Mario
            { word: "Enfermería", hint: "Salud" }, // Laura, Silvia, Paloma
            { word: "Audi A3", hint: "Modelo" }, // Silvia y Mario
            { word: "Generación 2003", hint: "Año" }, // Casi todos
            { word: "El Mus", hint: "Naipes" }, // Carlos, Javier, Dani
            { word: "Facultad de Ciencias", hint: "Universidad" }, // Japa y otros

            { word: "Acebo bebiendo a medias", hint: "joven" },
            { word: "Natos y Ron", hint: "alcohol" },
            { word: "Japa Y Acebo El Dia De La Paella", hint: "Legendario" },
            { word: "Ges", hint: "Solares" },
            { word: "Pienso en Ti", hint: "Laura" },
            { word: "Bobby", hint: "Perrito" },
            { word: "Play Robada Del Garito", hint: "Abierto" },
            { word: "Espejo de Óscar", hint: "Macro" },
            { word: "Garito", hint: "Te hodiste, no hay pista" },
            { word: "Ana López", hint: "Vecina" },
            { word: "El Rompe-Cazoletas", hint: "Tren" },
            { word: "Fordfi", hint: "faro" },
            { word: "Lupa", hint: "Investigación"},
            { word: "María", hint: "llamada" },
            { word: "Dani Villar", hint: "Mus" },
            { word: "Carlos", hint: "Cuñado" },
            { word: "Ratón del garito", hint: "asomar"},
            { word: "Emilio", hint: "comida" },
            { word: "Cogollo (el gato)", hint: "negro"},
            { word: "Tom", hint: "bar"},  
            { word: "David", hint: "barba"},
            { word: "Chamizo", hint: "bolsillo" },
            { word: "Farolillo", hint: "rabia" },
            { word: "Seat Toledo de Gutgun", hint: "Gratis" },
            { word: "Ferdinand", hint: "musero"},
            { word: "Monopoly en el garito", hint: "juego"},
            { word: "Plin y cierro", hint: "Laura" },
            { word: "Garito limpio", hint: "flis flis"},
            { word: "Coche de Acebo", hint: "fantasía" },
            { word: "Calcetines de marcos", hint: " '' rufles'' "},
            { word: "Noja", hint: "chupito"},
            { word: "Hacer un hoyo en la playa", hint: "delito" },
            { word: "Charlie", hint: "chuli"},
            { word: "Nico Portilla", hint: "Mediocentro inofesivo"},
            { word: "Erika", hint: "Apellido"},
            { word: "Casa de Javier Maliaño", hint: "Aura"},
            { word: "Laura conduciendo", hint: "Astucia"},
            { word: "La plaza", hint: "Suelo"},
            
            
          ]
    }
};
