module.exports = {
  "MIX": {
    "label": "🎲 Aleatorio (Mix)",
    "hint": "Cualquier cosa",
    "words": [] 
  },
  "COMIDA": {
    "label": "🍕 Comida y Bebida",
    "hint": "Es algo comestible o bebible",
    "words": [
      { word: "Pizza", hint: "Ptolemaico" },
      { word: "Sushi", hint: "Xenofobia" },
      { word: "Hamburguesa", hint: "Simetría" },
      { word: "Paella", hint: "Helicóptero" },
      { word: "Tacos", hint: "Metacarpo" },
      { word: "Espaguetis", hint: "Caligrafía" },
      { word: "Helado", hint: "Arqueología" },
      { word: "Chocolate", hint: "Epistemología" },
      { word: "Cerveza", hint: "Olfato" },
      { word: "Vino", hint: "Sedimentación" },
      { word: "Agua", hint: "Osmosis" },
      { word: "Café", hint: "Fototropismo" },
      { word: "Queso", hint: "Cuotidiano" },
      { word: "Jamón", hint: "Cetáceo" },
      { word: "Huevo Frito", hint: "Simetría" },
      { word: "Croquetas", hint: "Efervescencia" },
      { word: "Ensalada", hint: "Fotosíntesis" },
      { word: "Manzana", hint: "Manzana" },
      { word: "Plátano", hint: "Inclinómetro" },
      { word: "Kebab", hint: "Samurái" },
      { word: "Tortilla de Patatas", hint: "Cero" },
      { word: "Gazpacho", hint: "Isotermo" },
      { word: "Pancakes", hint: "Servidumbre" },
      { word: "Galletas", hint: "Litosfera" },
      { word: "Donuts", hint: "Topología" },
      { word: "Aceite de Oliva", hint: "Lubricitación" },
      { word: "Salchichón", hint: "Helicoide" },
      { word: "Lentejas", hint: "Dioptrías" },
      { word: "Arroz con Leche", hint: "Sinestesia" },
      { word: "Batido", hint: "Agitación" },
      { word: "Gominolas", hint: "Polímero" },
      { word: "Mofongo", hint: "Fusión" },
      { word: "Ceviche", hint: "Desnaturalización" },
      { word: "Ramen", hint: "Seísmo" },
      { word: "Falafel", hint: "Inmersión" },
      { word: "Miso", hint: "Bacteriología" },
      { word: "Tahini", hint: "Molturación" },
      { word: "Kimchi", hint: "Anaerobiosis" },
      { word: "Tempura", hint: "Subacuático" },
      { word: "Poutine", hint: "Criogénico" },
      { word: "Croissant", hint: "Tumefacción" },
      { word: "Tiramisú", hint: "Levitación" },
      { word: "Pavlova", hint: "Meringue" },
      { word: "Macarrón", hint: "Almohada" },
      { word: "Mozzarella", hint: "Viscoelástico" },
      { word: "Hummus", hint: "Licuefacción" },
      { word: "Wasabi", hint: "Capsaicina" },
      { word: "Quinua", hint: "Andino" }
    ]
  },
  "OBJETOS": {
    "label": "💡 Objetos Cotidianos",
    "hint": "Es un objeto inanimado",
    "words": [
      { word: "Mesa", hint: "Planaridad" },
      { word: "Silla", hint: "Ergonomía" },
      { word: "Teléfono", hint: "Frecuencia" },
      { word: "Ordenador", hint: "Algoritmo" },
      { word: "Cama", hint: "Homeostasis" },
      { word: "Cuchillo", hint: "Filo" },
      { word: "Tenedor", hint: "Prensión" },
      { word: "Coche", hint: "Combustión" },
      { word: "Reloj", hint: "Cronometría" },
      { word: "Gafas", hint: "Refracción" },
      { word: "Llaves", hint: "Cerradura" },
      { word: "Cartera", hint: "Portabilidad" },
      { word: "Mochila", hint: "Ergonomía" },
      { word: "Lámpara", hint: "Fotometría" },
      { word: "Espejo", hint: "Especularidad" },
      { word: "Cepillo de Dientes", hint: "Higiene" },
      { word: "Papel Higiénico", hint: "Celulosa" },
      { word: "Sartén", hint: "Conducción" },
      { word: "Toalla", hint: "Capilaridad" },
      { word: "Zapatos", hint: "Tracción" },
      { word: "Calcetines", hint: "Termorregulación" },
      { word: "Mando a Distancia", hint: "Infrarrojo" },
      { word: "Cargador", hint: "Amperaje" },
      { word: "Auriculares", hint: "Transductor" },
      { word: "Botella", hint: "Hermetismo" },
      { word: "Libro", hint: "Papirografía" },
      { word: "Bolígrafo", hint: "Capilaridad" },
      { word: "Tijeras", hint: "Palanca" },
      { word: "Microondas", hint: "Magnetrón" },
      { word: "Nevera", hint: "Ciclo Carnot" },
      { word: "Binoculares", hint: "Prisma" },
      { word: "Termómetro", hint: "Dilatación" },
      { word: "Brújula", hint: "Declinación" },
      { word: "Candado", hint: "Pasador" },
      { word: "Cadena", hint: "Anillo" },
      { word: "Candela", hint: "Luminancia" },
      { word: "Incienso", hint: "Volatilidad" },
      { word: "Espejo retrovisor", hint: "Perspectiva" },
      { word: "Extinguidor", hint: "Sofocación" },
      { word: "Enchufe", hint: "Voltaje" },
      { word: "Interruptor", hint: "Contacto" },
      { word: "Bombilla", hint: "Filamento" },
      { word: "Vela", hint: "Propulsión" },
      { word: "Mapamundi", hint: "Proyección" },
      { word: "Telescopio", hint: "Aberración" },
      { word: "Microscopio", hint: "Aumentro" },
      { word: "Lupa", hint: "Aumento" },
      { word: "Cinturón", hint: "Circunferencia" },
      { word: "Corbata", hint: "Nudo" },
      { word: "Pañuelo", hint: "Absorción" },
      { word: "Bufanda", hint: "Aislamiento" },
      { word: "Sombrero", hint: "Sombrilla" },
      { word: "Gorro", hint: "Recubrimiento" },
      { word: "Paraguas", hint: "Impermeabilidad" }
    ]
  },
  "ACCIONES": {
    "label": "🏃 Acciones (Verbos)",
    "hint": "Es algo que se hace",
    "words": [
      { word: "Correr", hint: "Cinética" },
      { word: "Saltar", hint: "Parábola" },
      { word: "Dormir", hint: "Letargo" },
      { word: "Comer", hint: "Ingesta" },
      { word: "Beber", hint: "Hidratación" },
      { word: "Leer", hint: "Decodificación" },
      { word: "Escribir", hint: "Caligrafía" },
      { word: "Cantar", hint: "Vibrato" },
      { word: "Bailar", hint: "Sincronización" },
      { word: "Cocinar", hint: "Maillard" },
      { word: "Llorar", hint: "Lacrimal" },
      { word: "Reír", hint: "Hilariedad" },
      { word: "Besar", hint: "Osculación" },
      { word: "Abrazar", hint: "Circunvalación" },
      { word: "Pelear", hint: "Confrontación" },
      { word: "Conducir", hint: "Tracción" },
      { word: "Nadar", hint: "Propulsión" },
      { word: "Volar", hint: "Sustentación" },
      { word: "Pintar", hint: "Pigmentación" },
      { word: "Estudiar", hint: "Mnemotécnica" },
      { word: "Trabajar", hint: "Producción" },
      { word: "Jugar", hint: "Lúdica" },
      { word: "Limpiar", hint: "Ablución" },
      { word: "Comprar", hint: "Transacción" },
      { word: "Vender", hint: "Enajenación" },
      { word: "Robar", hint: "Apropiación" },
      { word: "Mentir", hint: "Falseamiento" },
      { word: "Gritar", hint: "Fonación" },
      { word: "Susurrar", hint: "Murmuración" },
      { word: "Pensar", hint: "Cognición" },
      { word: "Estornudar", hint: "Expulsión" },
      { word: "Toser", hint: "Reflejo" },
      { word: "Suspirar", hint: "Exhalación" },
      { word: "Jadear", hint: "Disnea" },
      { word: "Bostezo", hint: "Bostezar" },
      { word: "Gruñir", hint: "Regustación" },
      { word: "Ronronear", hint: "Vibración" },
      { word: "Silbar", hint: "Frecuencia" },
      { word: "Tararear", hint: "Zumbido" },
      { word: "Murmurar", hint: "Susurración" },
      { word: "Tartamudear", hint: "Disartria" },
      { word: "Balbucear", hint: "Balbucencia" },
      { word: "Protestar", hint: "Objeción" },
      { word: "Suplicar", hint: "Petición" },
      { word: "Exigir", hint: "Imposición" },
      { word: "Implorar", hint: "Rogativa" },
      { word: "Amenazar", hint: "Conminación" },
      { word: "Perseguir", hint: "Persecución" },
      { word: "Tropezar", hint: "Escollo" },
      { word: "Arrastrarse", hint: "Reptación" },
      { word: "Escalar", hint: "Ascensión" },
      { word: "Sumergirse", hint: "Inmersión" },
      { word: "Deslizar", hint: "Deslizamiento" },
      { word: "Tambalear", hint: "Oscilación" }
    ]
  },
  "PERSONAJES_PUBLICOS": {
    "label": "🌍 Personajes Públicos",
    "hint": "Persona real conocida",
    "words": [
      { word: "Messi", hint: "Biomecánica" },
      { word: "Cristiano Ronaldo", hint: "Musculatura" },
      { word: "Shakira", hint: "Cadera" },
      { word: "Michael Jackson", hint: "Antigraviedad" },
      { word: "Einstein", hint: "Curvatura" },
      { word: "Picasso", hint: "Simultaneidad" },
      { word: "Napoleón", hint: "Cartografía" },
      { word: "Cleopatra", hint: "Ptolemaico" },
      { word: "Elon Musk", hint: "Fusión" },
      { word: "Bill Gates", hint: "Algoritmo" },
      { word: "Obama", hint: "Oratoria" },
      { word: "Trump", hint: "Mercadotecnia" },
      { word: "Newton", hint: "Gravitación" },
      { word: "Tesla", hint: "Electromagnética" },
      { word: "Mozart", hint: "Sinfonía" },
      { word: "Beethoven", hint: "Sordera" },
      { word: "Madonna", hint: "Provocación" },
      { word: "Beyoncé", hint: "Pirotecnia" },
      { word: "Leonardo da Vinci", hint: "Polímata" },
      { word: "Oprah Winfrey", hint: "Empoderación" },
      { word: "Kim Kardashian", hint: "Narcisismo" },
      { word: "Dwayne Johnson", hint: "Hipertrofia" },
      { word: "Taylor Swift", hint: "Narratología" },
      { word: "Ariana Grande", hint: "Rango" },
      { word: "The Weeknd", hint: "Nostalgia" },
      { word: "Kanye West", hint: "Megalomanía" },
      { word: "Rihanna", hint: "Reinvención" },
      { word: "Lady Gaga", hint: "Experimentación" },
      { word: "Coldplay", hint: "Melancolía" },
      { word: "The Beatles", hint: "Sincronización" },
      { word: "Freddie Mercury", hint: "Falsete" },
      { word: "David Bowie", hint: "Metamorfosis" },
      { word: "Pink Floyd", hint: "Psicodelia" },
      { word: "Steven Spielberg", hint: "Nostalgia" },
      { word: "Martin Scorsese", hint: "Violencia" },
      { word: "James Cameron", hint: "Tecnología" },
      { word: "Quentin Tarantino", hint: "Diálogos" },
      { word: "Christopher Nolan", hint: "Temporalidad" },
      { word: "Greta Thunberg", hint: "Activismo" },
      { word: "Malala Yousafzai", hint: "Educación" },
      { word: "Gal Gadot", hint: "Femineidad" },
      { word: "The Rock", hint: "Metamorfosis" },
      { word: "Tom Hanks", hint: "Empatía" },
      { word: "Meryl Streep", hint: "Versatilidad" },
      
      // Presidentes España desde 1980
      { word: "Adolfo Suárez", hint: "Cambio" },
      { word: "Leopoldo Calvo-Sotelo", hint: "Brevedad" },
      { word: "Felipe González", hint: "Ideología" },
      { word: "José María Aznar", hint: "Conservadurismo" },
      { word: "José Luis Rodríguez Zapatero", hint: "Reformismo" },
      { word: "Mariano Rajoy", hint: "Austeridad" },
      { word: "Pedro Sánchez", hint: "Adaptabilidad" },
      
      // Cantantes más famosos en España
      { word: "Julio Iglesias", hint: "Sentimentalismo" },
      { word: "Miguel Bosé", hint: "Androginia" },
      { word: "Enrique Iglesias", hint: "Globalización" },
      { word: "Rosalía", hint: "Hibridación" },
      { word: "Alejandro Sanz", hint: "Lirismo" },
      { word: "David Bisbal", hint: "Mediatización" },
      { word: "Leiva", hint: "Introspección" },
      { word: "Maluma", hint: "Reggaeton" },
      { word: "Bad Bunny", hint: "Iconoclastia" },
      { word: "J Balvin", hint: "Globalización" },
      { word: "Extremoduro", hint: "Radicalismo" },
      { word: "Dua Lipa", hint: "Modernidad" },
      { word: "Rauw Alejandro", hint: "Hibridación" },
      { word: "Karol G", hint: "Empoderamiento" },
      { word: "Myke Towers", hint: "Minimalismo" },
      
      // Personajes históricos guerras famosas
      { word: "Adolf Hitler", hint: "Totalitarismo" },
      { word: "Benito Mussolini", hint: "Imperialismo" },
      { word: "Napoleón Bonaparte", hint: "Ambición" },
      { word: "Winston Churchill", hint: "Resiliencia" },
      { word: "Franklin D. Roosevelt", hint: "Humanitarismo" },
      { word: "Joseph Stalin", hint: "Represión" },
      { word: "Ernesto Che Guevara", hint: "Idealismo" },
      { word: "Fidel Castro", hint: "Dogmatismo" },
      { word: "Saddam Hussein", hint: "Despotismo" },
      { word: "Osama bin Laden", hint: "Extremismo" },
      { word: "Aníbal Barca", hint: "Estrategia" },
      { word: "Carlomagno", hint: "Expansionismo" },
      { word: "Juana de Arco", hint: "Martirio" },
      { word: "Hernán Cortés", hint: "Invasión" },
      { word: "Francisco Pizarro", hint: "Conquista" },
      
      // Personajes bíblicos
      { word: "Jesús", hint: "Soteriología" },
      { word: "Moisés", hint: "Legislación" },
      { word: "Goliat", hint: "Gigantismo" },
      { word: "Sansón", hint: "Virilidad" },
      { word: "Dalila", hint: "Seducción" },
      { word: "Salomón", hint: "Prudencia" },
      { word: "Noé", hint: "Diluvio" },
      { word: "Adán", hint: "Génesis" },
      { word: "Eva", hint: "Tentación" },
      { word: "Caín", hint: "Fraticidio" },
      { word: "Abel", hint: "Inocencia" },
      { word: "Mateo", hint: "Conversion" },
      { word: "Simón Pedro", hint: "Impulsividad" },
      { word: "Judas Iscariote", hint: "Traición" },
      { word: "María Magdalena", hint: "Penitencia" },
      { word: "Belén", hint: "Humildad" },
      { word: "Herodes", hint: "Tiranía" },
      { word: "Pilato", hint: "Pusilanimidad" },
      
      // 30 Influencers más famosos
      { word: "Kylie Jenner", hint: "Emprendimiento" },
      { word: "Khloé Kardashian", hint: "Publicidad" },
      { word: "David Beckham", hint: "Estilismo" },
      { word: "Zendaya", hint: "Minucia" },
      { word: "Ariana Grande", hint: "Dibujo" },
      { word: "Billie Eilish", hint: "Nihilismo" },
      { word: "Justin Bieber", hint: "Idolatría" },
      { word: "Drake", hint: "Narrativa" },
      { word: "Nicki Minaj", hint: "Feminismo" },
      { word: "Cardi B", hint: "Autenticidad" },
      { word: "Rihanna", hint: "Multitarea" },
      { word: "Beyoncé", hint: "Perfeccionismo" },
      { word: "Taylor Swift", hint: "Reinvención" },
      { word: "Selena Gómez", hint: "Vulnerabilidad" },
      { word: "Miley Cyrus", hint: "Transformación" },
      { word: "Emma Watson", hint: "Feminismo" },
      { word: "Kendall Jenner", hint: "Privilegio" },
      { word: "Gigi Hadid", hint: "Cosmopolitismo" },
      { word: "Bella Hadid", hint: "Simetría" },
      { word: "Hailey Bieber", hint: "Minimalismo" },
      { word: "Priyanka Chopra", hint: "Globalización" },
      { word: "Aitana Ocaña", hint: "Visualismo" },
      { word: "ElrubiusOMG", hint: "Entretenimiento" },
      { word: "TheGrefg", hint: "Gamificación" },
      { word: "Ibai Llanos", hint: "Espontaneidad" },
      { word: "AuronPlay", hint: "Ironía" },
      { word: "Willyrex", hint: "Nostalgia" },
      { word: "Vegetta777", hint: "Consistencia" }
    ]
  },

  "CLASH_ROYALE": {
    "label": "👑 Clash Royale",
    "hint": "Juego de Supercell",
    "words": [
      { word: "Mega Caballero", hint: "Magnificencia" },
      { word: "Montapuercos", hint: "Ingeniería" },
      { word: "Larry", hint: "Deificación" },
      { word: "Princesa", hint: "Estratificación" },
      { word: "Tronco", hint: "Arboricultura" },
      { word: "Espejo", hint: "Dualismo" },
      { word: "Cohete", hint: "Trayectoria" },
      { word: "Chispitas", hint: "Minutería" },
      { word: "Gigante Noble", hint: "Aristocracia" },
      { word: "Minero", hint: "Extracción" },
      { word: "Golem", hint: "Artificialidad" },
      { word: "Ejército de Esqueletos", hint: "Mortandad" },
      { word: "Sabueso de Lava", hint: "Magmatismo" },
      { word: "Bandida", hint: "Delincuencia" },
      { word: "P.E.K.K.A", hint: "Automatismo" },
      { word: "Mago Eléctrico", hint: "Conductividad" },
      { word: "Globo Bombástico", hint: "Flotabilidad" },
      { word: "Ballesta", hint: "Proyectilería" },
      { word: "Torre Infernal", hint: "Infierno" },
      { word: "Espíritu de Hielo", hint: "Criogenia" },
      { word: "Carta", hint: "Cartografía" },
      { word: "Elixir", hint: "Alquimia" },
      { word: "Arena", hint: "Desertificación" },
      { word: "Trofeos", hint: "Trofología" },
      { word: "Derrotado", hint: "Derrota" },
      { word: "Victoria", hint: "Triunfalismo" },
      { word: "Torreta", hint: "Fortificación" },
      { word: "Rey", hint: "Monarquía" },
      { word: "Reina", hint: "Matriarcado" },
      { word: "Mago", hint: "Hermetismo" },
      { word: "Arbusto Sospechoso", hint: "Camuflaje" },
      { word: "Arqueras", hint: "Arquería" },
      { word: "Bárbaros", hint: "Salvajismo" },
      { word: "Barril de Duendes", hint: "Contenedorización" },
      { word: "Barril de Esqueletos", hint: "Mortalidad" },
      { word: "Bola de Nieve", hint: "Alud" },
      { word: "Bombardero", hint: "Bombardeo" },
      { word: "Barbaros Evolucion", hint: "Mejoramiento" },
      { word: "Caballero", hint: "Equitación" },
      { word: "Campeones", hint: "Campeonato" },
      { word: "Cartas Comunes", hint: "Ordinaridad" },
      { word: "Cartas Especiales", hint: "Excepcionalidad" },
      { word: "Cartas Legendarias", hint: "Mitología" },
      { word: "Cartas Épicas", hint: "Epopeya" },
      { word: "Cazador", hint: "Caza" },
      { word: "Cañonero", hint: "Artillería" },
      { word: "Cañón", hint: "Ordenanza" },
      { word: "Cocinero Real", hint: "Gastronomía" },
      { word: "Cofres", hint: "Atesoramiento" },
      { word: "Coronas", hint: "Coronación" },
      { word: "Demoledor Duende", hint: "Demolición" },
      { word: "Dragón Eléctrico", hint: "Voltaísmo" },
      { word: "Dragón Infernal", hint: "Infernal" },
      { word: "Duende Lanzadardos", hint: "Dardismo" },
      { word: "Duendenstein", hint: "Frankenstein" },
      { word: "Duquesa de Dagas", hint: "Duquería" },
      { word: "Emperatriz Espiritual", hint: "Espiritismo" },
      { word: "Enredadera", hint: "Botánica" },
      { word: "Espíritu de Hielo", hint: "Glaciación" },
      { word: "Espíritu Sanador", hint: "Curación" },
      { word: "Evolución de Cartas", hint: "Evolución" },
      { word: "Fantasma Real", hint: "Espectrología" },
      { word: "Gigante Noble", hint: "Gigantismo" },
      { word: "Gigante Rúnica", hint: "Rúnica" },
      { word: "Horno", hint: "Combustión" },
      { word: "Leñador", hint: "Silvicultura" },
      { word: "Mazos", hint: "Juego" },
      { word: "Megacaballero", hint: "Megalomanía" },
      { word: "Mortero", hint: "Mortería" },
      { word: "Mosquetera", hint: "Mosquetería" },
      { word: "Murciélagos", hint: "Quiropterología" },
      { word: "Máquina Duende", hint: "Mecanización" },
      { word: "Pescador", hint: "Ictiología" },
      { word: "Princesa de Torre", hint: "Presidiaria" },
      { word: "Principito", hint: "Príncipe" },
      { word: "Puercos Reales", hint: "Suicultura" },
      { word: "Reclutas Reales", hint: "Reclutamiento" },
      { word: "Rompemuros", hint: "Demolición" },
      { word: "Vacío", hint: "Nihilidad" },
      { word: "Valquiria", hint: "Mitología" },
      { word: "Verdugo", hint: "Ejecución" }
    ]
  },

  "MINECRAFT": {
    "label": "⛏️ Minecraft",
    "hint": "Bloques y cubos",
    "words": [
      { word: "Creeper", hint: "Explosividad" },
      { word: "Enderman", hint: "Teleportación" },
      { word: "Bedrock", hint: "Inamovibilidad" },
      { word: "Herobrine", hint: "Criptozoología" },
      { word: "Diamante", hint: "Preciosidad" },
      { word: "Nether", hint: "Infierno" },
      { word: "Aldeano", hint: "Comercialidad" },
      { word: "Lobo", hint: "Domesticabilidad" },
      { word: "Ghast", hint: "Gemebundidad" },
      { word: "Redstone", hint: "Electricalidad" },
      { word: "Obsidiana", hint: "Vulcanidad" },
      { word: "Steve", hint: "Pixelación" },
      { word: "Alex", hint: "Alternancia" },
      { word: "Slime", hint: "Viscosidad" },
      { word: "Warden", hint: "Custodialidad" },
      { word: "Axolote", hint: "Neotenia" },
      { word: "Hierro", hint: "Metalurgia" },
      { word: "Oro", hint: "Preciosidad" },
      { word: "Leche", hint: "Lactancia" },
      { word: "Farlands", hint: "Infinitud" },
      { word: "Madera", hint: "Silvicultura" },
      { word: "Piedra", hint: "Petrografía" },
      { word: "Arena", hint: "Arenación" },
      { word: "Grava", hint: "Fragmentación" },
      { word: "Tierra", hint: "Edafología" },
      { word: "Arenisca", hint: "Sedimentología" },
      { word: "Cristal", hint: "Vitrificación" },
      { word: "Riel", hint: "Ferrocarrilería" },
      { word: "Barriles", hint: "Coopería" },
      { word: "Cofre", hint: "Tesorería" },
      { word: "Horno", hint: "Calcinación" },
      { word: "Mesa de trabajo", hint: "Manufactura" },
      { word: "Alquitrán", hint: "Carbonería" },
      { word: "Magma", hint: "Magmatismo" },
      { word: "Tela de araña", hint: "Araneología" },
      { word: "Hierba", hint: "Botánica" },
      { word: "Flor", hint: "Floricultura" },
      { word: "Árbol", hint: "Dendrología" },
      { word: "Cactus", hint: "Cactología" },
      { word: "Lirio de agua", hint: "Limnología" },
      { word: "Caña de azúcar", hint: "Sacarificación" },
      { word: "Seta", hint: "Micología" },
      { word: "Bloque de comando", hint: "Programación" },
      { word: "Estructura", hint: "Arquitectónica" },
      { word: "Luz", hint: "Fotometría" },
      { word: "Dripleaf", hint: "Gotificación" },
      { word: "Mangrove", hint: "Paludismo" },
      { word: "Dripstone", hint: "Espeleología" },
      { word: "Amethyst", hint: "Cristalografía" },
      { word: "Calcita", hint: "Calcificación" },
      { word: "Blackstone", hint: "Melancolía" },
      { word: "Basalt", hint: "Basaltología" },
      { word: "Netherite", hint: "Rarificación" },
      { word: "Ancient Debris", hint: "Arqueología" },
      { word: "Deepslate", hint: "Profundidad" },
      { word: "Copper", hint: "Cuprería" },
      { word: "Lightning Rod", hint: "Parrayismo" },
      { word: "Pointed Dripstone", hint: "Acuidad" },
      { word: "Moss Block", hint: "Muscología" },
      { word: "Lush Cave", hint: "Frondosidad" },
      { word: "Sculk", hint: "Antigüedad" },
      { word: "Sculk Sensor", hint: "Sensorización" },
      { word: "Warped Blocks", hint: "Deformación" },
      { word: "Crimson Blocks", hint: "Carmesía" },
      { word: "Soul Block", hint: "Espiritualidad" },
      { word: "Beacon", hint: "Señalización" },
      { word: "Conduit", hint: "Conducción" },
      { word: "Dragon Egg", hint: "Oología" },
      { word: "Ender Crystal", hint: "Cristalería" },
      { word: "Nether Star", hint: "Astrología" },
      { word: "Enchanting Table", hint: "Encantología" },
      { word: "Anvil", hint: "Herrería" },
      { word: "Crafting Table", hint: "Manufactura" },
      { word: "Smithing Table", hint: "Smithería" },
      { word: "Brewing Stand", hint: "Cervecería" },
      { word: "Cauldron", hint: "Calderería" },
      { word: "Respawn Anchor", hint: "Resurrección" },
      { word: "Zombie", hint: "Necrología" },
      { word: "Skeleton", hint: "Osteología" },
      { word: "Spider", hint: "Araneología" },
      { word: "Witch", hint: "Brujería" },
      { word: "Husk", hint: "Desecación" },
      { word: "Drowned", hint: "Ahogamiento" },
      { word: "Phantom", hint: "Fantasmalería" },
      { word: "Guardian", hint: "Tutela" },
      { word: "Elder Guardian", hint: "Ancianidad" },
      { word: "Wither", hint: "Putrefacción" },
      { word: "Ender Dragon", hint: "Dracología" },
      { word: "Blaze", hint: "Inflamabilidad" },
      { word: "Piglin", hint: "Suoidea" },
      { word: "Zombified Piglin", hint: "Necrofilia" },
      { word: "Strider", hint: "Locomoción" },
      { word: "Hoglin", hint: "Agresividad" },
      { word: "Zoglin", hint: "Hybridación" },
      { word: "Pillager", hint: "Pillaje" },
      { word: "Vindicator", hint: "Vindicación" },
      { word: "Evoker", hint: "Evocación" },
      { word: "Shulker", hint: "Estratificación" },
      { word: "Silverfish", hint: "Argentieria" },
      { word: "Endermite", hint: "Acarología" },
      { word: "Vex", hint: "Irritación" },
      { word: "Ravager", hint: "Devastación" },
      { word: "Magma Cube", hint: "Cubificación" },
      { word: "Farm Automática", hint: "Automatización" },
      { word: "Granja Experencia", hint: "Experiencialidad" },
      { word: "Granja Grano", hint: "Cerealicultura" },
      { word: "Granja Calabaza", hint: "Cucurbitología" },
      { word: "Granja Melón", hint: "Meloniculturaña" },
      { word: "Granja Azúcar", hint: "Sacarificación" },
      { word: "Granja Nether", hint: "Netherología" },
      { word: "Granja Bambú", hint: "Bambuología" },
      { word: "Granja Mob", hint: "Mobifauna" },
      { word: "Granja Spawner", hint: "Generación" },
      { word: "Granja Araña", hint: "Araneicultura" },
      { word: "Granja Esqueleto", hint: "Osteifauna" },
      { word: "Granja Creeper", hint: "Explosivería" },
      { word: "Granja Zombie", hint: "Necrifauna" },
      { word: "Granja Enderman", hint: "Teleportología" },
      { word: "Granja Blaze", hint: "Pirofauna" },
      { word: "Granja Ghast", hint: "Llorería" },
      { word: "Granja AFK", hint: "Pasividad" },
      { word: "Granja Caña Automática", hint: "Mecanización" },
      { word: "Granja Seta", hint: "Micofauna" },
      { word: "Far Lands", hint: "Extraterritorialidad" },
      { word: "Chunk Error", hint: "Corrupción" },
      { word: "Dupe Glitch", hint: "Duplicación" },
      { word: "Nether Roof", hint: "Limitación" },
      { word: "Void", hint: "Nulidad" },
      { word: "Bedrock Break", hint: "Inviolabilidad" },
      { word: "Y-Level Glitch", hint: "Coordenalidad" },
      { word: "Mesa Infinite", hint: "Infinitud" },
      { word: "Block Update", hint: "Actualización" },
      { word: "Ghost Block", hint: "Invisibilidad" },
      { word: "Suffocation", hint: "Asfixia" },
      { word: "Piston Push Limit", hint: "Limitación" },
      { word: "XP Farm Lag", hint: "Ralentización" },
      { word: "Redstone Lag", hint: "Latencia" },
      { word: "Mob Despawn", hint: "Desaparición" },
      { word: "Chunk Corruption", hint: "Corruptibilidad" },
      { word: "Terrain Gen Bug", hint: "Generación" },
      { word: "Biome Blend", hint: "Graduación" },
      { word: "Light Update", hint: "Iluminación" },
      { word: "Forge", hint: "Modulación" },
      { word: "Fabric", hint: "Textilidad" },
      { word: "OptiFine", hint: "Optimización" },
      { word: "JourneyMap", hint: "Cartografía" },
      { word: "NEI", hint: "Enciclopedismo" },
      { word: "JEI", hint: "Suficiencia" },
      { word: "Botania", hint: "Botanología" },
      { word: "Thaumcraft", hint: "Taumaturgía" },
      { word: "Tinkers Construct", hint: "Artesanía" },
      { word: "Applied Energistics", hint: "Energética" },
      { word: "Thermal Expansion", hint: "Termología" },
      { word: "Mekanism", hint: "Mecanismo" },
      { word: "BuildCraft", hint: "Construccionismo" },
      { word: "IndustrialCraft", hint: "Industrialización" },
      { word: "Draconic Evolution", hint: "Dracología" },
      { word: "Mystical Agriculture", hint: "Agromancia" },
      { word: "Project E", hint: "Transmutatoria" },
      { word: "Chisel", hint: "Esculturación" },
      { word: "Biomes O Plenty", hint: "Biomatología" },
      { word: "Better Nether", hint: "Mejoramiento" },
      { word: "Better End", hint: "Perfeccionismo" },
      { word: "Twilight Forest", hint: "Crepuscularidad" },
      { word: "Aether", hint: "Eterealidad" },
      { word: "Mo Creatures", hint: "Creaturología" },
      { word: "Lycanites Mobs", hint: "Licantropología" },
      { word: "Roguelike Dungeons", hint: "Generación" },
      { word: "Advent of Ascension", hint: "Ascensionalidad" },
      { word: "Immersive Engineering", hint: "Inmersividad" }
    ]
  },
  "FUTBOL_GENERAL": {
    "label": "⚽ Fútbol (General)",
    "hint": "Deporte rey",
    "words": [
      { word: "VAR", hint: "Bar" }, // Fonética. Impostor piensa en cerveza
      { word: "Fuera de Juego", hint: "Bandera" }, // Juez de línea
      { word: "Penalti", hint: "Mancha" }, // Punto de penalti
      { word: "Corner", hint: "Olímpico" }, // Gol olímpico
      { word: "Tarjeta Roja", hint: "Calle" }, // "A la calle"
      { word: "Portería", hint: "Red" }, // Internet o pesca
      { word: "Balón", hint: "Cuero" }, // Material
      { word: "Árbitro", hint: "Gafas" }, // "Árbitro compra gafas"
      { word: "Banquillo", hint: "Frío" }, // Chupar banquillo
      { word: "Prórroga", hint: "Tiempo" }, // Extra
      { word: "Mundial", hint: "Cuatro" }, // Años
      { word: "Champions", hint: "Orejona" }, // La copa
      { word: "Fichaje", hint: "Humo" }, // Periodismo
      { word: "Grada", hint: "Ola" }, // Hacer la ola
      { word: "Cesión", hint: "Vuelta" }, // Tienen que volver
      { word: "Regate", hint: "Vaca" }, // "Romper la cintura"
      { word: "Caño", hint: "Sotana" }, // Pasar por debajo
      { word: "Chilena", hint: "Hugo" }, // Hugo Sánchez
      { word: "Escuadra", hint: "Telarañas" }, // Quitar las telarañas
      { word: "Descenso", hint: "Infierno" }, // Segunda división
      { word: "Offside", hint: "Posición adelantada castigo" },
      { word: "Tiro libre", hint: "Falta regla pared" },
      { word: "Saque de banda", hint: "Mano lateral fuera" },
      { word: "Saque de portería", hint: "Portero rebote inicio" },
      { word: "Cambio", hint: "Sustitución entrada salida" },
      { word: "Formación", hint: "Táctica números estrategia" },
      { word: "Pase", hint: "Compañero balón movimiento" },
      { word: "Disparo", hint: "Gol intención portería" },
      { word: "Cabezazo", hint: "Cabeza balón aire" },
      { word: "Control", hint: "Primer toque dominio" },
      { word: "Dribbling", hint: "Regates movimiento velocidad" },
      { word: "Finta", hint: "Engaño cuerpo contrario" },
      { word: "Volea", hint: "Aire sin bote disparo" },
      { word: "Chilena", hint: "Acrobacia aire estilo" },
      { word: "Vaselina", hint: "Arco portero elevado" },
      { word: "Tiro lejano", hint: "Distancia potencia gol" },
      { word: "Remate de cabeza", hint: "Aire defensa centro" },
      { word: "Carrera", hint: "Velocidad línea final" },
      { word: "Presión", hint: "Defensa agresivo robo" },
      { word: "Bloqueo", hint: "Cuerpo tiro defensa" },
      { word: "Entrada", hint: "Pierna contacto oponente" },
      { word: "Falta técnica", hint: "Mano antijuego castigo" },
      { word: "Remontada", hint: "Atrás victoria inesperada" },
      { word: "Empate", hint: "Igual goles indefinido" },
      { word: "Goleada", hint: "Muchos goles diferencia" }
    ]
  },

  "FUTBOL_JUGADORES": {
    "label": "🏃 Fútbol (Jugadores)",
    "hint": "Futbolista famoso",
    "words": [
      // Balón de Oro y leyendas
      { word: "Messi", hint: "Argentino Balón Oro" },
      { word: "Cristiano Ronaldo", hint: "Portugués Balón Oro" },
      { word: "Pelé", hint: "Brasil tres mundiales" },
      { word: "Maradona", hint: "Argentina campeón mundial" },
      { word: "Zidane", hint: "Francia Balón Oro campeón" },
      { word: "Ronaldo", hint: "Brasil fenómeno Balón Oro" },
      { word: "Ronaldinho", hint: "Brasil Balón Oro Barcelona" },
      { word: "Platini", hint: "Francia Balón Oro" },
      { word: "Beckenbauer", hint: "Alemania Balón Oro Kaiser" },
      { word: "Cruyff", hint: "Holanda Balón Oro" },
      { word: "Gerd Müller", hint: "Alemania goles Balón Oro" },
      { word: "Johan Cruyff", hint: "Holanda total fútbol" },
      { word: "Ferenc Puskás", hint: "Hungría zurdo Real Madrid" },
      { word: "Alfredo Di Stéfano", hint: "Real Madrid leyenda Champions" },
      { word: "Eusébio", hint: "Benfica Champions campeón" },
      
      // Españoles
      { word: "Iniesta", hint: "España Barcelona pase" },
      { word: "Xavi", hint: "España Barcelona control" },
      { word: "Piqué", hint: "España Barcelona defensa" },
      { word: "Ramos", hint: "España Real Madrid capitán" },
      { word: "Busquets", hint: "España Barcelona centrocampista" },
      { word: "Puyol", hint: "España Barcelona capitán" },
      { word: "Casillas", hint: "España Real Madrid portero" },
      { word: "Nacho Fernández", hint: "España Real Madrid" },
      { word: "Valdés", hint: "España Barcelona portero" },
      { word: "Gento", hint: "España Real Madrid leyenda" },
      { word: "Santillana", hint: "España Real Madrid" },
      { word: "Butarque", hint: "España delantero" },
      
      // Compañeros Messi (Barcelona/PSG/Inter Miami)
      { word: "Suárez", hint: "Uruguay Barcelona compañero Messi" },
      { word: "Neymar", hint: "Brasil Barcelona PSG compañero" },
      { word: "Busquets", hint: "España Barcelona Messi" },
      { word: "Piqué", hint: "España Barcelona Messi" },
      { word: "Alba", hint: "España Barcelona lateral Messi" },
      { word: "Rakitić", hint: "Croacia Barcelona Messi" },
      { word: "Xavi", hint: "España Barcelona Messi" },
      { word: "Iniesta", hint: "España Barcelona Messi" },
      { word: "Puyol", hint: "España Barcelona Messi" },
      { word: "Mascherano", hint: "Argentina Barcelona Messi" },
      
      // Compañeros Cristiano (Manchester/Real Madrid/Juventus)
      { word: "Modric", hint: "Croacia Real Madrid Cristiano" },
      { word: "Benzema", hint: "Francia Real Madrid Cristiano" },
      { word: "Ramos", hint: "España Real Madrid Cristiano" },
      { word: "Xavi Alonso", hint: "España Real Madrid Cristiano" },
      { word: "Van der Sar", hint: "Holanda Manchester Cristiano" },
      { word: "Evra", hint: "Francia Manchester Cristiano" },
      { word: "Vidic", hint: "Serbia Manchester Cristiano" },
      { word: "Buffon", hint: "Italia Juventus Cristiano" },
      { word: "Chiellini", hint: "Italia Juventus Cristiano" },
      
      // Ganadores Champions League
      { word: "Van Basten", hint: "Holanda Milan Champions" },
      { word: "Gullit", hint: "Holanda Milan Champions" },
      { word: "Rijkaard", hint: "Holanda Milan Champions" },
      { word: "Giggs", hint: "Gales Manchester Champions" },
      { word: "Scholes", hint: "Inglaterra Manchester Champions" },
      { word: "Gerrard", hint: "Inglaterra Liverpool Champions" },
      { word: "Lampard", hint: "Inglaterra Chelsea Champions" },
      { word: "Vieira", hint: "Francia Arsenal Champions" },
      { word: "Henry", hint: "Francia Arsenal invicto" },
      { word: "Bergkamp", hint: "Holanda Arsenal defensa" },
      { word: "Cannavaro", hint: "Italia Juventus Champions" },
      { word: "Chiellini", hint: "Italia Juventus Champions" },
      { word: "Bonucci", hint: "Italia Juventus Champions" },
      { word: "Cafu", hint: "Brasil Milan Champions" },
      { word: "Roberto Carlos", hint: "Brasil Milan Champions" },
      { word: "Canavaro", hint: "Italia Milan Champions" },
      { word: "Stam", hint: "Holanda Manchester Champions" },
      { word: "Nesta", hint: "Italia Milan Champions" },
      { word: "Thuram", hint: "Francia Juventus Champions" },
      { word: "Pepe", hint: "Portugal Real Madrid Champions" },
      { word: "Lahm", hint: "Alemania Bayern Champions" },
      { word: "Alves", hint: "Brasil Barcelona Champions" },
      { word: "Carvalho", hint: "Portugal Chelsea Champions" },
      { word: "Heinze", hint: "Argentina Manchester Champions" },
      { word: "Silvestre", hint: "Francia Manchester Champions" },
      
      // Liga Española e Inglesa actuales (selección de élite)
      { word: "Mbappé", hint: "Francia Real Madrid velocidad" },
      { word: "Haaland", hint: "Noruega Manchester goleador" },
      { word: "Vinicius", hint: "Brasil Real Madrid extremo" },
      { word: "Rodri", hint: "España Manchester control" },
      { word: "Bellingham", hint: "Inglaterra Real Madrid" },
      { word: "Salah", hint: "Egipto Liverpool velocidad" },
      { word: "De Bruyne", hint: "Bélgica Manchester maestría" },
      { word: "Van Dijk", hint: "Holanda Liverpool defensa" },
      { word: "Son Heung-min", hint: "Corea Tottenham velocidad" },
      { word: "Foden", hint: "Inglaterra Manchester talento" },
      
      // Ganadores ligas nacionales destacables
      { word: "Lewandowski", hint: "Polonia Bayern Balón Oro" },
      { word: "Neuer", hint: "Alemania Bayern portero" },
      { word: "Müller", hint: "Alemania Bayern goles" },
      { word: "Bale", hint: "Gales Real Madrid velocidad" },
      { word: "Ibrahimovic", hint: "Suecia PSG AC Milan" },
      { word: "Cavani", hint: "Uruguay PSG Napoli" },
      { word: "Griezmann", hint: "Francia Atlético Barcelona" },
      { word: "Agüero", hint: "Argentina Manchester goleador" },
      { word: "Hazard", hint: "Bélgica Chelsea Madrid" },
      { word: "Panenka", hint: "República Checa Balón Oro" },
      { word: "Kempes", hint: "Argentina Valencia mundial" },
      { word: "Simonsen", hint: "Dinamarca Balón Oro" },
      { word: "Van der Sar", hint: "Holanda Manchester portero" },
      { word: "Yashin", hint: "URSS Balón Oro portero" },
      { word: "Gianluigi Buffon", hint: "Italia Juventus leyenda" },
      { word: "Cech", hint: "Checa Arsenal Chelsea" },
      { word: "Ter Stegen", hint: "Alemania Barcelona portero" },
      { word: "Ederson", hint: "Brasil Manchester portero" },
      { word: "Alisson", hint: "Brasil Liverpool portero" },
      { word: "De Gea", hint: "España Manchester portero" },
      { word: "Donarumma", hint: "Italia Milan PSG" },
      
      // Entrenadores que fueron jugadores (añadidos)
      { word: "Guardiola", hint: "Técnico Manchester fue Barcelona" },
      { word: "Ancelotti", hint: "Técnico Real Madrid fue Milan" },
      { word: "Zidane", hint: "Técnico Real Madrid Balón Oro" },
      { word: "Mourinho", hint: "Técnico Chelsea fue portero" },
      { word: "Simeone", hint: "Técnico Atlético fue delantero" },
      { word: "Flick", hint: "Técnico Alemania fue delantero" },
      { word: "Ten Hag", hint: "Técnico Manchester fue Ajax" },
      { word: "Arteta", hint: "Técnico Arsenal fue centrocampista" },
      { word: "Pochettino", hint: "Técnico París fue defensa" },
      { word: "Nagelsmann", hint: "Técnico Bayern fue delantero" }
    ]
  },


  LA_PLAZA: {
        label: "La Plaza (Vitamina D)",
        words: [
            // --- LUIS CRUZ ---
            { word: "Reiniciar el alfabeto", hint: "Didáctica" },
            { word: "Fade del guapo", hint: "Barbero" },
            { word: "Compruebalesbianas", hint: "Test" },
            { word: "Luis Cruz", hint: "Física" },
            { word: "Luis Cruz", hint: "Volante" }, // Por conducir mal

            // --- NACHO ---
            { word: "La Chunga", hint: "Fiesta" },
            { word: "Carnicero del Lupa", hint: "Filetes" },
            { word: "Amor italiano", hint: "Erasmus" },
            { word: "Nacho", hint: "Charcutería" },
            { word: "Nacho", hint: "Entradas" },

            // --- ALBA CADELO ---
            { word: "Pinchar ruedas", hint: "Venganza" },
            { word: "Racing Genuine", hint: "Novio" },
            { word: "Las Cagigas", hint: "Ubicación" },
            { word: "Alba Cadelo", hint: "Fisioterapia" },
            { word: "Alba Cadelo", hint: "Rural" },

            // --- ALEJANDRA SILIÓ ---
            { word: "Tiene una correa", hint: "Mascota" },
            { word: "Odia el garito", hint: "Antro" },
            { word: "Ex adicta", hint: "Humo" },
            { word: "Alejandra Silió", hint: "Embaucadora" },
            { word: "Alejandra Silió", hint: "Relaciones" },

            // --- BEA PRADO ---
            { word: "Perro Killo", hint: "Limones" },
            { word: "Caras de asco", hint: "Expresión" },
            { word: "Zumba y Pilates", hint: "Gimnasio" },
            { word: "Bea Prado", hint: "Psicología" },
            { word: "Bea Prado", hint: "Militar" }, // Por el novio

            // --- CARLOS (TÚ) ---
            { word: "Coche Autobús", hint: "Dimensiones" },
            { word: "Novio de Silvia", hint: "Cuñado" },
            { word: "Farolero al Mus", hint: "Engaño" },
            { word: "Ex mujeriego", hint: "Pasado" },
            { word: "Carlos", hint: "Informático" },
            { word: "Carlos", hint: "Máster" },

            // --- DIEGO ACEBO (DAC) ---
            { word: "No tiene bachiller", hint: "Estudios" },
            { word: "Paja táctica", hint: "Llegada" },
            { word: "Fake fan", hint: "Bernabéu" },
            { word: "Diego Acebo", hint: "Ron-cola" },
            { word: "Diego Acebo", hint: "Derrochador" },

            // --- JAPA ---
            { word: "Siete dioptrías", hint: "Ceguera" },
            { word: "Delincuente en periódico", hint: "Prensa" },
            { word: "Conectar el HDMI", hint: "Ingeniero" },
            { word: "Villano de Setién", hint: "Antagonista" },
            { word: "Japa", hint: "Barba" },
            { word: "Japa", hint: "Leyenda" },

            // --- IKER ---
            { word: "Maestro del Poper", hint: "Nariz" },
            { word: "Queso de Potes", hint: "Olor" },
            { word: "Reality en el garito", hint: "Show" },
            { word: "Iker", hint: "Mecatrónico" },
            { word: "Iker", hint: "After" },

            // --- JAVIER MALIAÑO ---
            { word: "Falso alemán", hint: "Idioma" },
            { word: "Jugador de pitos", hint: "Naipes" },
            { word: "Futuro McDonald's", hint: "Ironía" },
            { word: "Javier Maliaño", hint: "Doble-Grado" },
            { word: "Javier Maliaño", hint: "Hamburguesa" },

            // --- LAURA ---
            { word: "La Chonda", hint: "Apodo" },
            { word: "Fuera de juego", hint: "Reglamento" },
            { word: "Laura", hint: "Enfermería" },
            { word: "Laura", hint: "Gimnasio" },

            // --- LUCAS FERNÁNDEZ ---
            { word: "Tiene pistola", hint: "Licencia" },
            { word: "El Militar", hint: "Uniforme" },
            { word: "Lucas Fernández", hint: "Arma" },
            { word: "Lucas Fernández", hint: "Setién" },

            // --- LUCAS GONZÁLEZ ---
            { word: "Iceman", hint: "Sentimientos" },
            { word: "Apagar y encender", hint: "Soporte" },
            { word: "Novia andaluza", hint: "Sur" },
            { word: "Lucas González", hint: "Informático" },
            { word: "Lucas González", hint: "Hielo" },

            // --- MANUEL TRICIO ---
            { word: "Lancha de Pedreña", hint: "Bahía" },
            { word: "Aeronáutica", hint: "Aviones" },
            { word: "Manuel Tricio", hint: "Italia" },
            { word: "Manuel Tricio", hint: "Madrid" },

            // --- MARCOS FERNÁNDEZ ---
            { word: "Furgoneta gitana", hint: "Aceleración" },
            { word: "Niño Tiktok", hint: "Viral" },
            { word: "Marcos Fernández", hint: "Motor" },
            { word: "Marcos Fernández", hint: "Grado" },

            // --- MARIO GÁNDARA ---
            { word: "Sofá en el Audi", hint: "Tetris" },
            { word: "Habla ininteligible", hint: "Alcohol" },
            { word: "Mario Gándara", hint: "Correa" }, // Por Alejandra
            { word: "Mario Gándara", hint: "Mecatrónico" },

            // --- MATEO VILLA ---
            { word: "Dejó la ingeniería", hint: "Abandono" },
            { word: "Intervención puntual", hint: "Conversación" },
            { word: "Mateo Villa", hint: "Magisterio" },
            { word: "Mateo Villa", hint: "Mujeriego" },

            // --- PALOMA CADELO ---
            { word: "Turno de guardia", hint: "Hospital" },
            { word: "Volkswagen Polo", hint: "Vehículo" },
            { word: "Paloma Cadelo", hint: "Enfermera" },
            { word: "Paloma Cadelo", hint: "Trabajo" },

            // --- SILVIA ---
            { word: "Kai y Atos", hint: "Manada" },
            { word: "Ya ha madurado", hint: "Cambio" },
            { word: "Silvia", hint: "Audi" },
            { word: "Silvia", hint: "Enfermería" },

            // --- TANIA GALLEGO ---
            { word: "Metro cincuenta", hint: "Estatura" },
            { word: "Hermano gallo", hint: "Corral" },
            { word: "Disociando", hint: "Mente" },
            { word: "Tania Gallego", hint: "Psicología" },
            { word: "Tania Gallego", hint: "Hippie" },

            // --- TITO ---
            { word: "Mandíbula rota", hint: "Puño" },
            { word: "Conduce un Mercedes", hint: "Lujo" },
            { word: "Desaparecido", hint: "Ausencia" },
            { word: "Tito", hint: "Trabajo" },
            { word: "Tito", hint: "Coche" },

            // --- COMUNES Y LUGARES (CAOS TOTAL) ---
            { word: "Setién", hint: "Pueblo" }, // Japa y Lucas F
            { word: "Las Cagigas", hint: "Casas" }, 
            { word: "Mecatrónico", hint: "Taller" }, // Iker y Mario
            { word: "Enfermería", hint: "Salud" }, // Laura, Silvia, Paloma
            { word: "Audi A3", hint: "Modelo" }, // Silvia y Mario
            { word: "Generación 2003", hint: "Año" }, // Casi todos
            { word: "El Mus", hint: "Naipes" }, // Carlos, Javier, Dani
            { word: "Facultad de Ciencias", hint: "Universidad" } // Japa y otros
            // Sin revisar:
          ]
    }
};
