module.exports = {
  "MIX": {
    "label": "🎲 Aleatorio (Mix)",
    "hint": "Cualquier cosa",
    "words": [] 
  },
  
  "FÁCILES": {
    "label": "⭐ Palabras Fáciles",
    "hint": "Para todos los públicos",
    "words": [
        { word: "Sol", hint: "Círculo" },
        { word: "Luna", hint: "Media" },
        { word: "Estrella", hint: "Picos" },
        { word: "Nube", hint: "Algodón" },
        { word: "Árbol", hint: "Tronco y círculo" },
        { word: "Flor", hint: "Pétalos simples" },
        { word: "Casa", hint: "Cuadrado con triángulo" },
        { word: "Puerta", hint: "Rectángulo" },
        { word: "Ventana", hint: "Cuadrado con cruz" },
        { word: "Coche", hint: "Rectángulo" },
        { word: "Rueda", hint: "Círculo" },
        { word: "Pelota", hint: "Círculo" },
        { word: "Corazón", hint: "Forma clásica" },
        { word: "Flecha", hint: "Línea con punta" },
        { word: "Montaña", hint: "Triángulos" },
        { word: "Río", hint: "Línea ondulada" },
        { word: "Sol con gafas", hint: "Sol + dos rayas" },
        { word: "Sombrero", hint: "Óvalo con ala" },
        { word: "Gafas", hint: "Dos" },
        { word: "Zapato", hint: "Forma curva" },
        { word: "Calcetín", hint: "L invertida" },
        { word: "Manzana", hint: "Círculo" },
        { word: "Plátano", hint: "Media" },
        { word: "Pera", hint: "bola" },
        { word: "Botella", hint: "Rectángulo" },
        { word: "Vaso", hint: "Trapecio" },
        { word: "Taza", hint: "Círculo" },
        { word: "Llave", hint: "dientes" },
        { word: "Candado", hint: "U invertida" },
        { word: "Reloj", hint: "palos" },
        { word: "Teléfono", hint: "Rectángulo" },
        { word: "Libro", hint: "abierto" },
        { word: "Lápiz", hint: "punta" },
        { word: "Papel", hint: "Rectángulo" },
        { word: "Cama", hint: "Rectángulo" },
        { word: "Mesa", hint: "Rectángulo" },
        { word: "Silla", hint: "Cuatro palos" },
        { word: "Escalera", hint: "Rayas" },
        { word: "Puente", hint: "Arco" },
        { word: "Caracol", hint: "Espiral" },
        { word: "Serpiente", hint: "Línea en S" },
        { word: "Pez", hint: "Óvalo con cola" },
        { word: "Barco", hint: "Triángulo sobre línea" },
        { word: "Avión", hint: "Cruz" },
        { word: "Cohete", hint: "Triángulo con fuego" },
        { word: "Bandera", hint: "Palo" },
        { word: "Semáforo", hint: "Tres" },
        { word: "Cactus", hint: "Palos" },
        { word: "Helado", hint: "bola" },
        { word: "Pastel", hint: "Capas" },
        { word: "Guitarra", hint: "Cuerpo y mástil" },
        { word: "Batería", hint: "Círculos" },
        { word: "Micrófono", hint: "palo" }
    ]
  },

  "COMIDA": {
    "label": "🍕 Comida y Bebida",
    "hint": "Es algo comestible o bebible",
    "words": [
      { word: "Pizza", hint: "Ptolemaico" },
      { word: "Sushi", hint: "Xenofobia" },
      { word: "Hamburguesa", hint: "Simetría" },
      { word: "Paella", hint: "Helicóptero" },
      { word: "Tacos", hint: "Metacarpo" },
      { word: "Espaguetis", hint: "Caligrafía" },
      { word: "Helado", hint: "Arqueología" },
      { word: "Chocolate", hint: "Epistemología" },
      { word: "Cerveza", hint: "Olfato" },
      { word: "Vino", hint: "Sedimentación" },
      { word: "Agua", hint: "Osmosis" },
      { word: "Café", hint: "Fototropismo" },
      { word: "Queso", hint: "Cuotidiano" },
      { word: "Jamón", hint: "Cetáceo" },
      { word: "Huevo Frito", hint: "Simetría" },
      { word: "Croquetas", hint: "Efervescencia" },
      { word: "Ensalada", hint: "Fotosíntesis" },
      { word: "Manzana", hint: "Manzana" },
      { word: "Plátano", hint: "Inclinómetro" },
      { word: "Kebab", hint: "Samurái" },
      { word: "Tortilla de Patatas", hint: "Cero" },
      { word: "Gazpacho", hint: "Isotermo" },
      { word: "Pancakes", hint: "Servidumbre" },
      { word: "Galletas", hint: "Litosfera" },
      { word: "Donuts", hint: "Topología" },
      { word: "Aceite de Oliva", hint: "Lubricitación" },
      { word: "Salchichón", hint: "Helicoide" },
      { word: "Lentejas", hint: "Dioptrías" },
      { word: "Arroz con Leche", hint: "Sinestesia" },
      { word: "Batido", hint: "Agitación" },
      { word: "Gominolas", hint: "Polímero" },
      { word: "Mofongo", hint: "Fusión" },
      { word: "Ceviche", hint: "Desnaturalización" },
      { word: "Ramen", hint: "Seísmo" },
      { word: "Falafel", hint: "Inmersión" },
      { word: "Miso", hint: "Bacteriología" },
      { word: "Tahini", hint: "Molturación" },
      { word: "Kimchi", hint: "Anaerobiosis" },
      { word: "Tempura", hint: "Subacuático" },
      { word: "Poutine", hint: "Criogénico" },
      { word: "Croissant", hint: "Tumefacción" },
      { word: "Tiramisú", hint: "Levitación" },
      { word: "Pavlova", hint: "Meringue" },
      { word: "Macarrón", hint: "Almohada" },
      { word: "Mozzarella", hint: "Viscoelástico" },
      { word: "Hummus", hint: "Licuefacción" },
      { word: "Wasabi", hint: "Capsaicina" },
      { word: "Quinua", hint: "Andino" },
      { word: "Lasaña", hint: "Estratificación" },
      { word: "Risotto", hint: "Amilosa" },
      { word: "Burrito", hint: "Cilindro" },
      { word: "Nachos", hint: "Triangular" },
      { word: "Empanadilla", hint: "Pleura" },
      { word: "Arepa", hint: "Altiplano" },
      { word: "Canelones", hint: "Tubular" },
      { word: "Sopa", hint: "Convección" },
      { word: "Caldo", hint: "Infusión" },
      { word: "Guiso", hint: "Ebullición" },
      { word: "Filete", hint: "Mioglobina" },
      { word: "Pollo Asado", hint: "Rotación" },
      { word: "Costillas", hint: "Arqueamiento" },
      { word: "Albóndigas", hint: "Esfericidad" },
      { word: "Churros", hint: "Extrusión" },
      { word: "Crepes", hint: "Laminado" },
      { word: "Flan", hint: "Coagulación" },
      { word: "Natillas", hint: "Gelificación" },
      { word: "Bizcocho", hint: "Porosidad" },
      { word: "Brownie", hint: "Densidad" },
      { word: "Cupcake", hint: "Capitel" },
      { word: "Magdalena", hint: "Cúpula" },
      { word: "Tarta de Queso", hint: "Isotropía" },
      { word: "Gelatina", hint: "Coloide" },
      { word: "Yogur", hint: "Lactobacillus" },
      { word: "Leche", hint: "Emulsión" },
      { word: "Mantequilla", hint: "Saponificación" },
      { word: "Mayonesa", hint: "Lecitina" },
      { word: "Ketchup", hint: "Viscosidad" },
      { word: "Mostaza", hint: "Isotiocianato" },
      { word: "Pan", hint: "Fermentación" },
      { word: "Pan Integral", hint: "Salvado" },
      { word: "Baguette", hint: "Alveolado" },
      { word: "Pretzel", hint: "Alcalinidad" },
      { word: "Tortitas", hint: "Capilaridad" },
      { word: "Waffles", hint: "Retícula" },
      { word: "Curry", hint: "Polifonía" },
      { word: "Chili", hint: "Capsicum" },
      { word: "Gambas", hint: "Quitina" },
      { word: "Pulpo", hint: "Cefalópodo" },
      { word: "Calamares", hint: "Tentáculo" },
      { word: "Mejillones", hint: "Bivalvo" },
      { word: "Ostras", hint: "Filtración" },
      { word: "Salmón", hint: "Anádromo" },
      { word: "Atún", hint: "Migratorio" },
      { word: "Bacalao", hint: "Salazón" },
      { word: "Empanada", hint: "Encapsulación" },
      { word: "Cachopo", hint: "Superposición" },
      { word: "Fabada", hint: "Leguminosa" },
      { word: "Callos", hint: "Colágeno" },
      { word: "Chorizo", hint: "Pimentón" },
      { word: "Morcilla", hint: "Coagulado" },
      { word: "Pimientos Rellenos", hint: "Oclusión" },
      { word: "Patatas Bravas", hint: "Acrilamida" },
      { word: "Alioli", hint: "Aglutinante" },
      { word: "Guacamole", hint: "Persea" },
      { word: "Frijoles", hint: "Endospermo" },
      { word: "Granizado", hint: "Cristalización" },
      { word: "Limonada", hint: "Citrato" }
    ]
  },

  "OBJETOS": {
    "label": "💡 Objetos Cotidianos",
    "hint": "Es un objeto inanimado",
    "words": [
      { word: "Mesa", hint: "Planaridad" },
      { word: "Silla", hint: "Ergonomía" },
      { word: "Teléfono", hint: "Frecuencia" },
      { word: "Ordenador", hint: "Algoritmo" },
      { word: "Cama", hint: "Homeostasis" },
      { word: "Cuchillo", hint: "Filo" },
      { word: "Tenedor", hint: "Prensión" },
      { word: "Coche", hint: "Combustión" },
      { word: "Reloj", hint: "Cronometría" },
      { word: "Gafas", hint: "Refracción" },
      { word: "Llaves", hint: "Cerradura" },
      { word: "Cartera", hint: "Portabilidad" },
      { word: "Mochila", hint: "Ergonomía" },
      { word: "Lámpara", hint: "Fotometría" },
      { word: "Espejo", hint: "Especularidad" },
      { word: "Cepillo de Dientes", hint: "Higiene" },
      { word: "Papel Higiénico", hint: "Celulosa" },
      { word: "Sartén", hint: "Conducción" },
      { word: "Toalla", hint: "Capilaridad" },
      { word: "Zapatos", hint: "Tracción" },
      { word: "Calcetines", hint: "Termorregulación" },
      { word: "Mando a Distancia", hint: "Infrarrojo" },
      { word: "Cargador", hint: "Amperaje" },
      { word: "Auriculares", hint: "Transductor" },
      { word: "Botella", hint: "Hermetismo" },
      { word: "Libro", hint: "Papirografía" },
      { word: "Bolígrafo", hint: "Capilaridad" },
      { word: "Tijeras", hint: "Palanca" },
      { word: "Microondas", hint: "Magnetrón" },
      { word: "Nevera", hint: "Ciclo Carnot" },
      { word: "Binoculares", hint: "Prisma" },
      { word: "Termómetro", hint: "Dilatación" },
      { word: "Brújula", hint: "Declinación" },
      { word: "Candado", hint: "Pasador" },
      { word: "Cadena", hint: "Anillo" },
      { word: "Candela", hint: "Luminancia" },
      { word: "Incienso", hint: "Volatilidad" },
      { word: "Espejo retrovisor", hint: "Perspectiva" },
      { word: "Extinguidor", hint: "Sofocación" },
      { word: "Enchufe", hint: "Voltaje" },
      { word: "Interruptor", hint: "Contacto" },
      { word: "Bombilla", hint: "Filamento" },
      { word: "Vela", hint: "Propulsión" },
      { word: "Mapamundi", hint: "Proyección" },
      { word: "Telescopio", hint: "Aberración" },
      { word: "Microscopio", hint: "Aumentro" },
      { word: "Lupa", hint: "Aumento" },
      { word: "Cinturón", hint: "Circunferencia" },
      { word: "Corbata", hint: "Nudo" },
      { word: "Pañuelo", hint: "Absorción" },
      { word: "Bufanda", hint: "Aislamiento" },
      { word: "Sombrero", hint: "Sombrilla" },
      { word: "Gorro", hint: "Recubrimiento" },
      { word: "Paraguas", hint: "Impermeabilidad" }
    ]
  },

  "INFORMATICA": {
  "label": "💻 Informática",
  "hint": "Computación y sistemas",
  "words": [
    { word: "Sistema Operativo", hint: "Orquestación" },
    { word: "Kernel", hint: "Núcleo" },
    { word: "Proceso", hint: "Ejecución" },
    { word: "Hilo", hint: "Concurrencia" },
    { word: "Planificador", hint: "Despacho" },
    { word: "Interrupción", hint: "Asincronía" },
    { word: "Memoria RAM", hint: "Volatilidad" },
    { word: "Memoria Caché", hint: "Latencia" },
    { word: "Paginación", hint: "Segmentación" },
    { word: "Swapping", hint: "Intercambio" },
    { word: "Sistema de Archivos", hint: "Persistencia" },
    { word: "Inodo", hint: "Metadato" },
    { word: "Permisos", hint: "Autorización" },
    { word: "Usuario", hint: "Identidad" },
    { word: "Grupo", hint: "Cohorte" },
    { word: "Shell", hint: "Intérprete" },
    { word: "Terminal", hint: "Consola" },
    { word: "Script", hint: "Automatización" },
    { word: "Daemon", hint: "Residente" },
    { word: "Servicio", hint: "Disponibilidad" },

    { word: "Programación", hint: "Algoritmia" },
    { word: "Algoritmo", hint: "Finitud" },
    { word: "Complejidad", hint: "Asintótica" },
    { word: "Big-O", hint: "Cota" },
    { word: "Recursividad", hint: "Auto-referencia" },
    { word: "Iteración", hint: "Bucle" },
    { word: "Compilador", hint: "Traducción" },
    { word: "Intérprete", hint: "Evaluación" },
    { word: "Lenguaje", hint: "Sintaxis" },
    { word: "Paradigma", hint: "Abstracción" },
    { word: "Orientado a Objetos", hint: "Encapsulación" },
    { word: "Funcional", hint: "Inmutabilidad" },
    { word: "Procedimental", hint: "Secuencia" },
    { word: "Concurrente", hint: "Paralelismo" },
    { word: "Variable", hint: "Mutabilidad" },
    { word: "Constante", hint: "Invariancia" },
    { word: "Tipo de Dato", hint: "Dominio" },
    { word: "Puntero", hint: "Referencia" },
    { word: "Heap", hint: "Montículo" },
    { word: "Stack", hint: "Pila" },

    { word: "Software", hint: "Lógica" },
    { word: "Hardware", hint: "Físico" },
    { word: "Firmware", hint: "Intermedio" },
    { word: "Driver", hint: "Controlador" },
    { word: "Aplicación", hint: "Utilidad" },
    { word: "Biblioteca", hint: "Reutilización" },
    { word: "Framework", hint: "Estructura" },
    { word: "API", hint: "Interfaz" },
    { word: "SDK", hint: "Desarrollo" },
    { word: "Licencia", hint: "Legalidad" },
    { word: "Código Abierto", hint: "Transparencia" },
    { word: "Software Libre", hint: "Libertad" },
    { word: "Actualización", hint: "Parcheo" },
    { word: "Bug", hint: "Anomalía" },
    { word: "Debug", hint: "Depuración" },
    { word: "Testing", hint: "Validación" },
    { word: "Unit Test", hint: "Aislamiento" },
    { word: "Integración Continua", hint: "Automatismo" },
    { word: "Despliegue", hint: "Publicación" },

    { word: "Procesador", hint: "Cómputo" },
    { word: "CPU", hint: "Centralidad" },
    { word: "Núcleo", hint: "Multicore" },
    { word: "Hiperhilo", hint: "Simultaneidad" },
    { word: "Registro", hint: "Inmediatez" },
    { word: "ALU", hint: "Aritmética" },
    { word: "Pipeline", hint: "Segmentación" },
    { word: "Placa Base", hint: "Interconexión" },
    { word: "Chipset", hint: "Coordinación" },
    { word: "Bus", hint: "Canal" },
    { word: "PCIe", hint: "Expansión" },
    { word: "BIOS", hint: "Arranque" },
    { word: "UEFI", hint: "Inicialización" },
    { word: "Refrigeración", hint: "Disipación" },
    { word: "Fuente de Alimentación", hint: "Estabilidad" },
    { word: "Disco Duro", hint: "Persistencia" },
    { word: "SSD", hint: "Velocidad" },
    { word: "NVMe", hint: "Throughput" },
    { word: "RAID", hint: "Redundancia" },

    { word: "Periférico", hint: "EntradaSalida" },
    { word: "Teclado", hint: "Entrada" },
    { word: "Ratón", hint: "Puntería" },
    { word: "Monitor", hint: "Visualización" },
    { word: "Impresora", hint: "Materialización" },
    { word: "Escáner", hint: "Digitalización" },
    { word: "Altavoces", hint: "Sonorización" },
    { word: "Micrófono", hint: "Captación" },
    { word: "Webcam", hint: "Videografía" },
    { word: "USB", hint: "Universalidad" },

    { word: "Red", hint: "Interconexión" },
    { word: "Protocolo", hint: "Normativa" },
    { word: "TCP/IP", hint: "Encapsulación" },
    { word: "UDP", hint: "Datagrama" },
    { word: "IP", hint: "Direccionamiento" },
    { word: "DNS", hint: "Resolución" },
    { word: "HTTP", hint: "Hipertexto" },
    { word: "HTTPS", hint: "Cifrado" },
    { word: "Firewall", hint: "Filtrado" },
    { word: "Router", hint: "Enrutamiento" },
    { word: "Switch", hint: "Conmutación" },
    { word: "Latencia", hint: "Retardo" },
    { word: "Ancho de Banda", hint: "Capacidad" },

    { word: "Seguridad", hint: "Protección" },
    { word: "Cifrado", hint: "Criptografía" },
    { word: "Hash", hint: "Dispersión" },
    { word: "Autenticación", hint: "Verificación" },
    { word: "Autorización", hint: "Permiso" },
    { word: "Backdoor", hint: "Intrusión" },
    { word: "Malware", hint: "Malicia" },
    { word: "Virus", hint: "Replicación" },
    { word: "Ransomware", hint: "Extorsión" },

    { word: "Ingeniería del Software", hint: "Metodología" },
    { word: "Arquitectura", hint: "Estructura" },
    { word: "Patrón de Diseño", hint: "Plantilla" },
    { word: "MVC", hint: "Separación" },
    { word: "Microservicios", hint: "Desacoplo" },
    { word: "Monolito", hint: "Centralización" },
    { word: "Escalabilidad", hint: "Crecimiento" },
    { word: "Rendimiento", hint: "Eficiencia" },
    { word: "Optimización", hint: "Ajuste" },
    { word: "Refactorización", hint: "Claridad" },

    { word: "Base de Datos", hint: "Persistencia" },
    { word: "SQL", hint: "Relacional" },
    { word: "NoSQL", hint: "EsquemaLibre" },
    { word: "Índice", hint: "Aceleración" },
    { word: "Consulta", hint: "Selección" },
    { word: "Transacción", hint: "Atomicidad" },
    { word: "ACID", hint: "Consistencia" },
    { word: "Backup", hint: "Respaldo" },

    { word: "Virtualización", hint: "Abstracción" },
    { word: "Máquina Virtual", hint: "Emulación" },
    { word: "Contenedor", hint: "Encapsulado" },
    { word: "Docker", hint: "Portabilidad" },
    { word: "Cloud", hint: "Elasticidad" },
    { word: "IaaS", hint: "Infraestructura" },
  ]
  },

  "PERSONAJES_PUBLICOS": {
    "label": "🌍 Personajes Públicos",
    "hint": "Persona real conocida",
    "words": [
      { word: "Messi", hint: "Biomecánica" },
      { word: "Cristiano Ronaldo", hint: "Musculatura" },
      { word: "Shakira", hint: "Cadera" },
      { word: "Michael Jackson", hint: "Antigraviedad" },
      { word: "Einstein", hint: "Curvatura" },
      { word: "Picasso", hint: "Simultaneidad" },
      { word: "Napoleón", hint: "Cartografía" },
      { word: "Cleopatra", hint: "Ptolemaico" },
      { word: "Elon Musk", hint: "Fusión" },
      { word: "Bill Gates", hint: "Algoritmo" },
      { word: "Obama", hint: "Oratoria" },
      { word: "Trump", hint: "Mercadotecnia" },
      { word: "Newton", hint: "Gravitación" },
      { word: "Tesla", hint: "Electromagnética" },
      { word: "Mozart", hint: "Sinfonía" },
      { word: "Leonardo da Vinci", hint: "Polímata" },
      { word: "Dwayne Johnson", hint: "Hipertrofia" },
      { word: "Taylor Swift", hint: "Narratología" },
      { word: "Ariana Grande", hint: "Rango" },
      { word: "The Weeknd", hint: "Nostalgia" },
      { word: "Kanye West", hint: "Megalomanía" },
      { word: "Coldplay", hint: "Melancolía" },
      { word: "The Beatles", hint: "Sincronización" },
      { word: "Freddie Mercury", hint: "Falsete" },
      { word: "Pink Floyd", hint: "Psicodelia" },
      { word: "Greta Thunberg", hint: "Activismo" },
      { word: "The Rock", hint: "Metamorfosis" },
      
      // Presidentes España desde 1980
      { word: "Adolfo Suárez", hint: "Cambio" },
      { word: "Leopoldo Calvo-Sotelo", hint: "Brevedad" },
      { word: "Felipe González", hint: "Ideología" },
      { word: "José María Aznar", hint: "Conservadurismo" },
      { word: "José Luis Rodríguez Zapatero", hint: "Reformismo" },
      { word: "Mariano Rajoy", hint: "Austeridad" },
      { word: "Pedro Sánchez", hint: "Adaptabilidad" },
      
      // Cantantes más famosos en España¡
      { word: "Enrique Iglesias", hint: "Globalización" },
      { word: "Rosalía", hint: "Hibridación" },
      { word: "Alejandro Sanz", hint: "Lirismo" },
      { word: "David Bisbal", hint: "Mediatización" },
      { word: "Maluma", hint: "Reggaeton" },
      { word: "Bad Bunny", hint: "Iconoclastia" },
      { word: "J Balvin", hint: "Globalización" },
      { word: "Rauw Alejandro", hint: "Hibridación" },
      { word: "Karol G", hint: "Empoderamiento" },
      { word: "Myke Towers", hint: "Minimalismo" },
      
      // Personajes históricos guerras famosas
      { word: "Adolf Hitler", hint: "Totalitarismo" },
      { word: "Benito Mussolini", hint: "Imperialismo" },
      { word: "Napoleón Bonaparte", hint: "Ambición" },
      { word: "Ernesto Che Guevara", hint: "Idealismo" },
      { word: "Fidel Castro", hint: "Dogmatismo" },
      { word: "Osama bin Laden", hint: "Extremismo" },
  
      
      { word: "David Beckham", hint: "Estilismo" },
      { word: "Zendaya", hint: "Minucia" },
      { word: "Justin Bieber", hint: "Idolatría" },
      { word: "Drake", hint: "Narrativa" },
      { word: "Cardi B", hint: "Autenticidad" },
      { word: "Rihanna", hint: "Multitarea" },
      { word: "Beyoncé", hint: "Perfeccionismo" },
      { word: "Miley Cyrus", hint: "Transformación" },
      { word: "Emma Watson", hint: "Feminismo" },
      { word: "Kendall Jenner", hint: "Privilegio" },
      { word: "Aitana Ocaña", hint: "Visualismo" },
      { word: "ElrubiusOMG", hint: "Entretenimiento" },
      { word: "TheGrefg", hint: "Gamificación" },
      { word: "Ibai Llanos", hint: "Espontaneidad" },
      { word: "AuronPlay", hint: "Ironía" },
      { word: "Willyrex", hint: "Nostalgia" },
      { word: "Vegetta777", hint: "Consistencia" }
    ]
  },
  
  "FUTBOLISTAS": {
    "label": "🏃 Fútbol (Jugadores)",
    "hint": "Hemeroteca",
    "words": [
      // Balón de Oro y leyendas
      { word: "Messi", hint: "Argentum" },
      { word: "Cristiano Ronaldo", hint: "Lusitano" },
      { word: "Pelé", hint: "Tricéfalo" },
      { word: "Maradona", hint: "Albiceleste" },
      { word: "Zidane", hint: "Caligrafía" },
      { word: "Ronaldo", hint: "Fenómeno" },
      { word: "Ronaldinho", hint: "Sonrisa" },
      { word: "Platini", hint: "Hexágono" },
      { word: "Beckenbauer", hint: "Kaiser" },
      { word: "Cruyff", hint: "Herejía" },
      { word: "Gerd Müller", hint: "Depredador" },
      { word: "Johan Cruyff", hint: "Dialéctica" },
      { word: "Ferenc Puskás", hint: "Zurda" },
      { word: "Alfredo Di Stéfano", hint: "Hibridación" },
      { word: "Eusébio", hint: "Pantera" },

      // Españoles
      { word: "Iniesta", hint: "Silencio" },
      { word: "Xavi", hint: "Ritmo" },
      { word: "Piqué", hint: "Ironía" },
      { word: "Ramos", hint: "Épica" },
      { word: "Busquets", hint: "Inercia" },
      { word: "Puyol", hint: "Estoicismo" },
      { word: "Casillas", hint: "Reflejo" },
      { word: "Nacho Fernández", hint: "Versatilidad" },
      { word: "Valdés", hint: "Frialdad" },
      { word: "Gento", hint: "Vértigo" },
      { word: "Santillana", hint: "Remate" },
      { word: "Butarque", hint: "Anomalía" },

      // Compañeros Messi
      { word: "Suárez", hint: "Canino" },
      { word: "Neymar", hint: "Carnaval" },
      { word: "Busquets", hint: "Gravedad" },
      { word: "Piqué", hint: "Sarcasmo" },
      { word: "Alba", hint: "Diagonal" },
      { word: "Rakitić", hint: "Balcanes" },
      { word: "Xavi", hint: "Metrónomo" },
      { word: "Iniesta", hint: "Evaporación" },
      { word: "Puyol", hint: "Muralla" },
      { word: "Mascherano", hint: "Sacrificio" },

      { word: "Modric", hint: "Bóveda" },
      { word: "Benzema", hint: "Metamorfosis" },
      { word: "Ramos", hint: "Catarsis" },
      { word: "Xabi Alonso", hint: "Cartografía" },
      { word: "Buffon", hint: "Longevità" },
      { word: "Chiellini", hint: "Cemento" },
      { word: "Pirlo", hint: "Visión" },
      { word: "Totti", hint: "Eterno" },
      { word: "Del Piero", hint: "Clasicismo" },
      { word: "Gullit", hint: "Ecléctico" },
      { word: "Giggs", hint: "Persistencia" },
      { word: "Scholes", hint: "Precisión" },
      { word: "Gerrard", hint: "Pulmón" },
      { word: "Lampard", hint: "Llegada" },
      { word: "Vieira", hint: "Autoridad" },
      { word: "Henry", hint: "Elegancia" },
      { word: "Cannavaro", hint: "Anticipación" },
      { word: "Chiellini", hint: "Trinchera" },
      { word: "Bonucci", hint: "Salida" },
      { word: "Cafu", hint: "Autopista" },
      { word: "Roberto Carlos", hint: "Balística" },
      { word: "Thuram", hint: "Resistencia" },
      { word: "Pepe", hint: "Belicosidad" },
      { word: "Lahm", hint: "Polivalencia" },
      { word: "Alves", hint: "Hipercinesia" },
      { word: "Carvalho", hint: "Sobriedad" },

      // Liga Española e Inglesa actuales
      { word: "Mbappé", hint: "Explosión" },
      { word: "Haaland", hint: "Martillo" },
      { word: "Vinicius", hint: "Provocación" },
      { word: "Rodri", hint: "Ancla" },
      { word: "Bellingham", hint: "Ascenso" },
      { word: "Salah", hint: "Duna" },
      { word: "De Bruyne", hint: "Orfebre" },
      { word: "Van Dijk", hint: "Muralla" },
      { word: "Son Heung-min", hint: "Resorte" },
      { word: "Foden", hint: "Germen" },

      // Ganadores ligas nacionales
      { word: "Lewandowski", hint: "Instinto" },
      { word: "Neuer", hint: "Libero" },
      { word: "Müller", hint: "Oportunismo" },
      { word: "Bale", hint: "Latigazo" },
      { word: "Ibrahimovic", hint: "Narciso" },
      { word: "Cavani", hint: "Acecho" },
      { word: "Griezmann", hint: "Intersticio" },
      { word: "Agüero", hint: "Finalización" },
      { word: "Hazard", hint: "Intermitencia" },
      { word: "Panenka", hint: "Atrevimiento" },
      { word: "Yashin", hint: "Araña" },
      { word: "Gianluigi Buffon", hint: "Eternidad" },
      { word: "Cech", hint: "Casco" },
      { word: "Ter Stegen", hint: "Elasticidad" },
      { word: "Ederson", hint: "Osadía" },
      { word: "Alisson", hint: "Seguridad" },
      { word: "De Gea", hint: "Reflejos" },
      { word: "Donarumma", hint: "Gigantismo" },

      // Entrenadores que fueron jugadores
      { word: "Guardiola", hint: "Dogma" },
      { word: "Ancelotti", hint: "Templanza" },
      { word: "Zidane", hint: "Misticismo" },
      { word: "Mourinho", hint: "Antagonismo" },
      { word: "Simeone", hint: "Fervor" },
      { word: "Flick", hint: "Verticalidad" },
      { word: "Ten Hag", hint: "Estructura" },
      { word: "Pochettino", hint: "Intensidad" },
      { word: "Klopp", hint: "Presión" },
      { word: "Conte", hint: "Disciplina" },

    ]
  },


  LA_PLAZA: {
        label: "🛒 La Plaza",
        hint: " (Vitamina D)",
        words: [
            // --- LUIS CRUZ ---
            { word: "Fade del guapo", hint: "Barbero" },
            { word: "Compruebalesbianas", hint: "Test" },
            { word: "Luis Cruz", hint: "Física" },
            { word: "Luis Cruz", hint: "Volante" }, // Por conducir mal

            // --- NACHO ---
            { word: "Chungar habitualmente", hint: "Fiesta" },
            { word: "Carnicero", hint: "Filetes" },
            { word: "Nacho", hint: "Charcutería" },
            { word: "Nacho", hint: "Entradas" },

            // --- ALBA CADELO ---
            { word: "Racing de Santander", hint: "Sitio" },
            { word: "Racismo", hint: "Alba Cadelo" },
            { word: "Las Cagigas", hint: "Ubicación" },
            { word: "Alba Cadelo", hint: "Fisioterapia" },
            { word: "Alba Cadelo", hint: "Rural" },

            // --- ALEJANDRA SILIÓ ---
            { word: "Alejandra Silió", hint: "Embaucadora" },
            { word: "Alejandra Silió", hint: "Relaciones" },

            // --- BEA PRADO ---
            { word: "Killo", hint: "Limones" },
            { word: "Bea Prado", hint: "Psicología" },
            { word: "Bea Prado", hint: "Militar" }, 

            // --- CARLOS (TÚ) ---
            { word: "Bluffer de Mus", hint: "Engaño" },
            { word: "Ex mujeriego", hint: "Pasado" },
            { word: "Carlos", hint: "Informático" },
            { word: "Carlos", hint: "Máster" },

            // --- DIEGO ACEBO (DAC) ---
            { word: "Paja táctica", hint: "Llegada" },
            { word: "Diego Acebo", hint: "Ron-cola" },
            { word: "Diego Acebo", hint: "Derrochador" },

            // --- JAPA ---
            { word: "Siete dioptrías", hint: "Ceguera" },
            { word: "Persecución policial", hint: "Prensa" },
            { word: "Cenicero de Potes", hint: "Tonto" },
            { word: "Villano de Setién", hint: "Antagonista" },
            { word: "Japa", hint: "Barba" },
            { word: "Japa", hint: "Leyenda" },

            // --- IKER ---
            { word: "Poper", hint: "Nariz" },
            { word: "Queso de Potes", hint: "Olor" },
            { word: "Iker", hint: "Mecatrónico" },
            { word: "Iker", hint: "After" },

            // --- JAVIER MALIAÑO ---
            { word: "B1 de alemán", hint: "Idioma" },
            { word: "Jugador de pitos", hint: "Naipes" },
            { word: "Javier Maliaño", hint: "Doble-Grado" },
            { word: "Javier Maliaño", hint: "Hamburguesa" },

            // --- LAURA ---
            { word: "La Chonda", hint: "Promiscua" },
            { word: "Laura", hint: "Enfermería" },
            { word: "Laura", hint: "Gimnasio" },
            { word: "Laura Quintanal", hint: "Calentorra" },
            { word: "Laura", hint: "Salida" },
            { word: "Marián", hint: "Ombligo" },

            // --- LUCAS FERNÁNDEZ ---
            { word: "Lucas Fernández", hint: "Arma" },
            { word: "Lucas Fernández", hint: "Setién" },

            // --- LUCAS GONZÁLEZ ---
            { word: "Iceman", hint: "Sentimientos" },
            { word: "Lucas González", hint: "Informático" },
            { word: "Lucas González", hint: "Hielo" },

            // --- MANUEL TRICIO ---
            { word: "Lancha de Pedreña", hint: "Bahía" },
            { word: "Manuel Tricio", hint: "Italia" },
            { word: "Manuel Tricio", hint: "Madrid" },

            // --- MARCOS FERNÁNDEZ ---
            { word: "Furgoneta gitana", hint: "Aceleración" },
            { word: "Marcos Fernández", hint: "Motor" },
            { word: "Marcos Fernández", hint: "Grado" },

            // --- MARIO GÁNDARA ---
            { word: "Habla ininteligible", hint: "Alcohol" },
            { word: "Mario Gándara", hint: "Correa" },
            { word: "Mario Gándara", hint: "Meca" },

            // --- MATEO VILLA ---
            { word: "Dejar la carrera", hint: "Alumno de Llados" },
            { word: "La única manera de evitar algo", hint: "Conversación" },
            { word: "Mateo Villa", hint: "Magisterio" },
            { word: "Mateo Villa", hint: "Mujeriego" },

            // --- PALOMA CADELO ---
            { word: "Polo", hint: "Vehículo" },
            { word: "Paloma Cadelo", hint: "Enfermera" },
            { word: "Paloma Cadelo", hint: "Trabajo" },

            // --- SILVIA ---
            { word: "Kai y Atos", hint: "Manada" },
            { word: "Silvia", hint: "Audi" },

            // --- TANIA GALLEGO ---
            { word: "Metro cincuenta", hint: "Estatura" },
            { word: "Tania Gallego", hint: "Psicología" },
            { word: "Tania Gallego", hint: "Hippie" },

            // --- TITO ---
            { word: "Mercedes", hint: "Merche" },
            { word: "Tito", hint: "Trabajo" },
            { word: "Tito", hint: "Coche" },

            // --- COMUNES Y LUGARES (CAOS TOTAL) ---
            { word: "Setién", hint: "Pueblo" }, // Japa y Lucas F
            { word: "Las Cagigas", hint: "Casas" }, 
            { word: "Enfermería", hint: "Salud" }, // Laura, Silvia, Paloma
            { word: "Audi A3", hint: "Modelo" }, // Silvia y Mario
            { word: "Generación 2003", hint: "Año" }, // Casi todos
            { word: "El Mus", hint: "Naipes" }, // Carlos, Javier, Dani
            { word: "Facultad de Ciencias", hint: "Universidad" }, // Japa y otros

            { word: "Acebo bebiendo a medias", hint: "joven" },
            { word: "Natos y Ron", hint: "alcohol" },
            { word: "Ges", hint: "Solares" },
            { word: "Pienso en Ti", hint: "Laura" },
            { word: "Bobby", hint: "Perrito" },
            { word: "Espejo de Óscar", hint: "Macro" },
            { word: "Garito", hint: "Te hodiste, no hay pista" },
            { word: "Ana López", hint: "Vecina" },
            { word: "Carlos", hint: "Cuñado" },
            { word: "Ratón del garito", hint: "asomar"},
            { word: "Emilio", hint: "comida" },
            { word: "Cogollo (el gato)", hint: "negro"},
            { word: "Tom", hint: "bar"},  
            { word: "Chamizo", hint: "bolsillo" },
            { word: "Farolillo", hint: "rabia" },
            { word: "Seat Toledo de Gutgun", hint: "Gratis" },
            { word: "Ferdinand", hint: "musero"},
            { word: "Plin y cierro", hint: "Laura" },
            { word: "Garito limpio", hint: "flis flis"},
            { word: "Coche de Acebo", hint: "fantasía" },
            { word: "Calcetines de marcos", hint: " '' rufles'' "},
            { word: "Noja", hint: "chupito"},
            { word: "Charlie", hint: "chuli"},
            { word: "Nico Portilla", hint: "Mediocentro inofesivo"},
            { word: "Erika", hint: "Apellido"},
            
            
          ]
    }
};
