module.exports = [
    // 1–20
    "¿Quién tiene el historial de búsqueda más turbio?",
    "¿Quién moriría primero en un apocalipsis zombie?",
    "¿Quién se casaría por dinero?",
    "¿Quién tiene más probabilidades de acabar en la cárcel?",
    "¿Quién tiene el ego más grande que su cabeza?",
    "¿Quién es más probable que se una a una secta?",
    "¿Quién tiene peor gusto vistiendo?",
    "¿Quién sería el peor presidente del gobierno?",
    "¿Quién tiene más probabilidades de tener un hijo secreto?",
    "¿Quién finge más orgasmos?",
    "¿Quién llora con películas de Disney?",
    "¿Quién tiene más energía de protagonista porno?",
    "¿Quién es el más falso del grupo?",
    "¿Quién sobreviviría más tiempo en una isla desierta?",
    "¿Quién se ríe de los chistes más inapropiados?",
    "¿Quién liga más cuando sale de fiesta?",
    "¿Quién es más probable que vomite esta noche?",
    "¿Quién es el más tacaño?",
    "¿Quién se haría rico por accidente?",
    "¿Quién es el más cuñado?",

    // 21–40
    "¿Quién tarda más en pillar indirectas?",
    "¿Quién enviaría un nude al grupo por error?",
    "¿Quién acabaría siendo influencer sin querer?",
    "¿Quién sería el peor compañero de piso?",
    "¿Quién se engancharía a una estafa piramidal?",
    "¿Quién miente peor?",
    "¿Quién se enamora más rápido?",
    "¿Quién se quedaría dormido en su propia boda?",
    "¿Quién gastaría 500€ en algo inútil?",
    "¿Quién haría ghosting sin remordimientos?",
    "¿Quién tiene más probabilidades de acabar cancelado?",
    "¿Quién siempre llega tarde?",
    "¿Quién se pierde incluso con GPS?",
    "¿Quién tiene más exs?",
    "¿Quién sería peor guardando un secreto?",
    "¿Quién se creería una fake news?",
    "¿Quién haría el ridículo en una primera cita?",
    "¿Quién se olvidaría su propio cumpleaños?",
    "¿Quién sería peor padre/madre?",
    "¿Quién ligaría con alguien solo por interés?",

    // 41–60
    "¿Quién se pelearía con un camarero?",
    "¿Quién lloraría borracho a las 4 a.m.?",
    "¿Quién tiene más probabilidades de ser infiel?",
    "¿Quién sería expulsado de un reality show?",
    "¿Quién tiene menos autocontrol?",
    "¿Quién se ofende por todo?",
    "¿Quién tiene menos filtro al hablar?",
    "¿Quién acabaría viviendo con sus padres a los 40?",
    "¿Quién es más probable que mienta en el currículum?",
    "¿Quién se haría un tatuaje horrible borracho?",
    "¿Quién sería peor jefe?",
    "¿Quién se cree más listo de lo que es?",
    "¿Quién copiaría en un examen?",
    "¿Quién se enamora de quien no debe?",
    "¿Quién se vendería por fama?",
    "¿Quién sería el peor testigo en un juicio?",
    "¿Quién siempre exagera sus historias?",
    "¿Quién no aguanta nada el alcohol?",
    "¿Quién siempre pierde el móvil?",
    "¿Quién sería peor espía?",

    // 61–80
    "¿Quién sería el primero en caer en una estafa online?",
    "¿Quién se gastaría todo el sueldo el primer día?",
    "¿Quién tiene menos fuerza de voluntad?",
    "¿Quién sería peor jugador de póker?",
    "¿Quién no sabría cuidar una planta?",
    "¿Quién acabaría viviendo en una furgoneta?",
    "¿Quién sería peor compañero de trabajo?",
    "¿Quién hablaría solo en voz alta?",
    "¿Quién tendría un podcast horrible?",
    "¿Quién es más probable que robe toallas de hoteles?",
    "¿Quién siempre se hace la víctima?",
    "¿Quién sería peor profesor?",
    "¿Quién se reiría en un funeral?",
    "¿Quién tiene menos paciencia?",
    "¿Quién sería peor conductor?",
    "¿Quién se olvidaría de pagar una multa?",
    "¿Quién acabaría en una discusión absurda?",
    "¿Quién tiene más probabilidades de ser despedido?",
    "¿Quién sería peor detective?",
    "¿Quién se rendiría primero en un reto?",

    // 81–100
    "¿Quién no sobreviviría sin WiFi?",
    "¿Quién sería peor cirujano?",
    "¿Quién se perdería en su propio barrio?",
    "¿Quién tendría más problemas con la ley?",
    "¿Quién no sabe guardar dinero?",
    "¿Quién tiene más probabilidades de arruinar una sorpresa?",
    "¿Quién sería peor político?",
    "¿Quién se haría famoso por algo vergonzoso?",
    "¿Quién mentiría en una cita?",
    "¿Quién sería peor astronauta?",
    "¿Quién no sabe cocinar ni pasta?",
    "¿Quién acabaría discutiendo con un policía?",
    "¿Quién se enfada por perder en un juego?",
    "¿Quién sería peor en un escape room?",
    "¿Quién se dejaría manipular más fácil?",
    "¿Quién siempre busca excusas?",
    "¿Quién tendría más multas acumuladas?",
    "¿Quién sería peor influencer?",
    "¿Quién se queja más?",
    "¿Quién no aguanta una crítica?",

    "¿Quién se metería en un lío solo por curiosidad?",
    "¿Quién tiene más probabilidades de stalkear a su ex?",
    "¿Quién mentiría para quedar bien?",
    "¿Quién se cree protagonista de una serie?",
    "¿Quién haría drama por la cosa más pequeña?",
    "¿Quién se enamora del camarero?",
    "¿Quién sería peor guardián de un secreto?",
    "¿Quién se haría amigo de alguien solo por interés?",
    "¿Quién tiene más probabilidades de discutir por política?",
    "¿Quién se iría de una fiesta sin avisar?",
    "¿Quién siempre promete y nunca cumple?",
    "¿Quién sería el primero en rendirse?",
    "¿Quién exagera más cuando cuenta algo?",
    "¿Quién se ofende aunque sea broma?",
    "¿Quién tiene más probabilidades de desaparecer sin dar señales?",
    "¿Quién se cree más interesante de lo que es?",
    "¿Quién sería peor en una discusión seria?",
    "¿Quién se inventaría una excusa absurda?",
    "¿Quién sería capaz de robar comida del plato de otro?",
    "¿Quién siempre quiere llamar la atención?",

    "¿Quién se arrepiente de escribir mensajes borracho?",
    "¿Quién se pondría celoso sin motivo?",
    "¿Quién tiene más probabilidades de liarla en Navidad?",
    "¿Quién sería el peor organizando un viaje?",
    "¿Quién siempre deja todo para última hora?",
    "¿Quién tiene menos vergüenza?",
    "¿Quién se metería donde no le llaman?",
    "¿Quién acabaría discutiendo con un desconocido?",
    "¿Quién es más probable que se quede sin batería?",
    "¿Quién cancelaría planes en el último momento?",
    "¿Quién haría trampas en un juego de mesa?",
    "¿Quién sería peor compañero de equipo?",
    "¿Quién se pone más pesado cuando bebe?",
    "¿Quién sería incapaz de guardar una sorpresa?",
    "¿Quién tiene más probabilidades de decir algo fuera de lugar?",
    "¿Quién se cree todas las teorías conspiranoicas?",
    "¿Quién se liaría con alguien solo por aburrimiento?",
    "¿Quién se pondría nervioso mintiendo?",
    "¿Quién tiene menos sentido común?",
    "¿Quién se metería en problemas por hablar de más?",

    "¿Quién haría el ridículo delante de mucha gente?",
    "¿Quién se engancharía a un juego absurdo?",
    "¿Quién sería el peor dando consejos?",
    "¿Quién se hace el interesante constantemente?",
    "¿Quién acabaría discutiendo con el GPS?",
    "¿Quién sería incapaz de improvisar?",
    "¿Quién se estresa más sin motivo?",
    "¿Quién siempre quiere tener la última palabra?",
    "¿Quién se frustraría jugando algo fácil?",
    "¿Quién sería peor manteniendo la calma?",
    "¿Quién se dejaría llevar por la presión del grupo?",
    "¿Quién acabaría hablando solo en público?",
    "¿Quién sería peor negociando?",
    "¿Quién se pondría dramático por un mensaje en visto?",
    "¿Quién tiene más probabilidades de malinterpretar todo?",
    "¿Quién sería peor compañero de viaje?",
    "¿Quién se rayaría por nada?",
    "¿Quién se obsesiona más?",
    "¿Quién sería el más intenso?",
    "¿Quién acabaría pidiendo perdón sin saber por qué?",

    // 111–210 (100 preguntas nuevas)
    "¿Quién olería peor después de no ducharse una semana?",
    "¿Quién se comería un sándwich del suelo?",
    "¿Quién sería más probable que tropiece con nada?",
    "¿Quién habla como si fuera la cosa más importante del mundo?",
    "¿Quién tiene el sentido del humor más retrasado?",
    "¿Quién se da de cabezazos contra las puertas?",
    "¿Quién se pondría a llorar viendo un anuncio de seguros?",
    "¿Quién sería peor haciendo un baile viral?",
    "¿Quién se cae subiendo escaleras?",
    "¿Quién se merecería una patada en el culo regularmente?",
    "¿Quién confundiría la sal con el azúcar en la sopa?",
    "¿Quién llamaría a la policía por comida fría?",
    "¿Quién tiene un fetiche vergonzoso?",
    "¿Quién se pegaría con una puerta automática?",
    "¿Quién se quedaría atrapado en un armario?",
    "¿Quién baila como si tuviera un espasmo?",
    "¿Quién se comería la pasta sin cocinar?",
    "¿Quién diría la ley de Murphy como consejo de vida?",
    "¿Quién se haría pis en el sofá riéndose?",
    "¿Quién sería incapaz de abrir una lata de conservas?",
    "¿Quién llamaría al servicio técnico para reiniciar el móvil?",
    "¿Quién se pondría a llorar jugando videojuegos en modo fácil?",
    "¿Quién se acuerda de toda en el grupo menos de los cumpleaños?",
    "¿Quién se cree que su mal humor es una personalidad?",
    "¿Quién buscaría 'cómo respirar' en Google?",
    "¿Quién diría 'no duele' justo antes de desmayarse?",
    "¿Quién sería más probable que se quemara una tostada?",
    "¿Quién se cae por intentar ir guay?",
    "¿Quién vería un video de miedo y tendría pesadillas una semana?",
    "¿Quién perdería la batalla contra un troll de internet?",
    "¿Quién se quedaría con hambre porque la comida 'se ve extraña'?",
    "¿Quién sería la mascota perfecta para un asilo?",
    "¿Quién se engancharía a un juego para móviles tipo Candy Crush?",
    "¿Quién se burlaba en redes de alguien que luego conoce?",
    "¿Quién tiene fotos de su mascota en el carnet de identidad?",
    "¿Quién se ahogaría con agua?",
    "¿Quién sería más probable que ganara una tragaperra?",
    "¿Quién diría 'soy muy guapo/a' en serio?",
    "¿Quién sería peor en un karaoke?",
    "¿Quién se olvidaría el nombre de alguien mirándole a la cara?",
    "¿Quién se cree que todo es una señal del universo?",
    "¿Quién se haría análisis de sangre por un moretón?",
    "¿Quién se vestiría con pijama a una boda?",
    "¿Quién diría mentiras piadosas constantemente?",
    "¿Quién se comportaría como un pequeño tirano borracho?",
    "¿Quién gritaría viendo una película de terror?",
    "¿Quién pedazo de carne es con personalidad de lechuga?",
    "¿Quién haría un TikTok horrible?",
    "¿Quién se burlaría de su mejor amigo en las redes?",
    "¿Quién tendría un feed lleno de contenido cringe?",
    "¿Quién se cree millonario siendo pobre?",
    "¿Quién se quejaría de estar cansado sin hacer nada?",
    "¿Quién sería peor en una fuga de la cárcel?",
    "¿Quién se cree que sabe de ciencia viendo TikToks?",
    "¿Quién se tatuaría un error ortográfico?",
    "¿Quién dejaría morir una planta cactus?",
    "¿Quién sería la peor persona para pedir dinero prestado?",
    "¿Quién se lo gastaría todo en cosas inútiles de Wish?",
    "¿Quién lidaría con la noticia de que come algo de lo que tiene alergia?",
    "¿Quién se tropezaría en una cuerda invisible?",
    "¿Quién diría que necesita 'vibraciones positivas'?",
    "¿Quién se creería adivino después de acertar algo una vez?",
    "¿Quién sería más probable que cagase en un examen oral?",
    "¿Quién se comería toda la comida del congelador porque se aburre?",
    "¿Quién sería incapaz de despedirse de una llamada telefónica?",
    "¿Quién se bufaría por WhatsApp?",
    "¿Quién se rascaría en los sitios más inapropiados?",
    "¿Quién sería peor en un job interview?",
    "¿Quién se vestiría con chanclas a una reunión importante?",
    "¿Quién tendría un olor corporal insoportable?",
    "¿Quién se deprimiría por una pregunta de un quiz de internet?",
    "¿Quién sería el primero en borrar sus chats?",
    "¿Quién presionaría los botones del ascensor múltiples veces?",
    "¿Quién se engancharía a una serie basura?",
    "¿Quién comería directamente de la olla?",
    "¿Quién sería más probable que se durmiera en una conversación?",
    "¿Quién se cree que su comida hecha mal es un arte?",
    "¿Quién gritaría en un cine?",
    "¿Quién se comeríaun cubo de hielo en un restaurante fancy?",
    "¿Quién sería peor limpiando?",
    "¿Quién sería incapaz de seguir instrucciones simples?",
    "¿Quién abriría la puerta del frigorífico 50 veces en 5 minutos?",
    "¿Quién se perdería en IKEA?",
    "¿Quién se comería toda una caja de galletas de una sentada?",
    "¿Quién sería peor armando un mueble?",
    "¿Quién se cree que es superior pero no puede ni atarse los cordones?",
    "¿Quién diría 'no tenía hambre' comiendo todo?",
    "¿Quién se ofrecería a llevar algo y no lo haría?",
    "¿Quién se cree que la música que escucha es superior a la de todos?",
    "¿Quién se enamora después de la primera cita?",
    "¿Quién confunde cariño con obsesión?",
    "¿Quién se ilusiona demasiado rápido?",
    "¿Quién se enamora de personas imposibles?",
    "¿Quién tiene peor gusto eligiendo pareja?",
    "¿Quién se queda enganchado a su ex?",
    "¿Quién se enamora del primer halago?",
    "¿Quién mezcla amor con dependencia?",
    "¿Quién se ilusiona aunque sepa que no hay futuro?",
    "¿Quién se hace películas en la cabeza?",
    "¿Quién se enamora del amor, no de la persona?",
    "¿Quién manda mensajes a las 3 a.m. arrepintiéndose luego?",
    "¿Quién se pone celoso sin motivo?",
    "¿Quién idealiza demasiado a su pareja?",
    "¿Quién se enamora de quien no le conviene?",
    "¿Quién confunde atracción con amor eterno?",
    "¿Quién vuelve con su ex por aburrimiento?",
    "¿Quién se declara borracho?",
    "¿Quién se enamora del camarero?",
    "¿Quién se engancha emocionalmente demasiado fácil?",
    "¿Quién sufre más por amor?",
    "¿Quién se enamora de alguien que no le hace caso?",
    "¿Quién se hace la víctima en relaciones?",
    "¿Quién se enamora por mensajes?",
    "¿Quién se ilusiona con señales inexistentes?",
    "¿Quién se ralla por no recibir respuesta?",
    "¿Quién se cree en una peli romántica?",
    "¿Quién se enamora en vacaciones?",
    "¿Quién se flipa con el amor a distancia?",
    "¿Quién se enamora de la idea de alguien?",
    "¿Quién se pone intenso demasiado pronto?",
    "¿Quién confunde pasión con drama?",
    "¿Quién se enamora del físico solamente?",
    "¿Quién se ilusiona con promesas vacías?",
    "¿Quién se enamora del que pasa de él/ella?",
    "¿Quién se cree que el amor lo arregla todo?",
    "¿Quién se engancha emocionalmente sin pensar?",
    "¿Quién se enamora cada dos semanas?",
    "¿Quién dramatiza por amor?",
    "¿Quién sufre por personas que no lo merecen?",
    "¿Quién se enamora aunque le hagan daño?",
    "¿Quién vuelve a caer siempre?",
    "¿Quién confunde costumbre con amor?",
    "¿Quién vive el amor como una telenovela?",
    "¿Quién se obsesiona más en pareja?",
    "¿Quién se enamora sin usar la cabeza?",
    "¿Quién ama más de lo que recibe?",
    "¿Quién se ralla por amor constantemente?",
    "¿Quién se ilusiona aunque todo vaya mal?",

    // videojuegos (50)
    "¿Quién se pica más perdiendo una partida?",
    "¿Quién culpa al lag siempre?",
    "¿Quién rompe el mando jugando?",
    "¿Quién se flipa jugando en modo fácil?",
    "¿Quién dice que juega mejor de lo que juega?",
    "¿Quién se enfada por perder en un juego?",
    "¿Quién abandona la partida si va perdiendo?",
    "¿Quién se cree pro sin serlo?",
    "¿Quién grita más jugando online?",
    "¿Quién se toma los videojuegos demasiado en serio?",
    "¿Quién se engancha a juegos absurdos?",
    "¿Quién se queda jugando hasta las 6 a.m.?",
    "¿Quién miente diciendo 'una partida más'?",
    "¿Quién se frustra con el tutorial?",
    "¿Quién no pasa del primer nivel?",
    "¿Quién se pica hasta con el Mario Kart?",
    "¿Quién insulta al NPC?",
    "¿Quién se estresa jugando algo fácil?",
    "¿Quién se engancha a juegos pay-to-win?",
    "¿Quién gasta dinero real en skins?",
    "¿Quién pierde siempre y se enfada?",
    "¿Quién no sabe usar los controles?",
    "¿Quién juega sin leer las instrucciones?",
    "¿Quién se enfada con el equipo?",
    "¿Quién se cree líder del grupo?",
    "¿Quién muere primero en cualquier partida?",
    "¿Quién se cae por no mirar el mapa?",
    "¿Quién no sabe guardar la partida?",
    "¿Quién se queja del juego pero no deja de jugar?",
    "¿Quién se flipa con su personaje?",
    "¿Quién se queda AFK?",
    "¿Quién siempre juega con el mismo personaje?",
    "¿Quién culpa al mando?",
    "¿Quién se pica con los niños online?",
    "¿Quién se cree hacker?",
    "¿Quién se frustra más rápido?",
    "¿Quién juega peor bajo presión?",
    "¿Quién no entiende la historia?",
    "¿Quién se pierde en mundos abiertos?",
    "¿Quién se engancha a juegos de móvil?",
    "¿Quién se cree estratega sin pensar?",
    "¿Quién se desespera en puzzles?",
    "¿Quién abandona sin guardar?",
    "¿Quién se enfada con la IA?",
    "¿Quién juega con volumen máximo?",
    "¿Quién se cree invencible?",
    "¿Quién se pica en cooperativo?",
    "¿Quién no acepta consejos?",
    "¿Quién ragequittea más?",

    // vergüenza (50)
    "¿Quién haría el ridículo en público?",
    "¿Quién tropieza delante de todo el mundo?",
    "¿Quién dice cosas fuera de lugar?",
    "¿Quién se equivoca de nombre siempre?",
    "¿Quién habla cuando no debe?",
    "¿Quién manda mensajes al chat equivocado?",
    "¿Quién se cae en silencio incómodo?",
    "¿Quién saluda a alguien que no le saludaba?",
    "¿Quién cuenta un chiste que nadie entiende?",
    "¿Quién se equivoca de puerta?",
    "¿Quién se pone rojo con facilidad?",
    "¿Quién se equivoca de conversación?",
    "¿Quién se queda en blanco hablando?",
    "¿Quién hace comentarios inapropiados?",
    "¿Quién se equivoca de persona saludando?",
    "¿Quién se equivoca de grupo de WhatsApp?",
    "¿Quién se ríe cuando no toca?",
    "¿Quién se queda mirando sin saber qué hacer?",
    "¿Quién se equivoca leyendo en voz alta?",
    "¿Quién se pone nervioso hablando?",
    "¿Quién se tropieza con nada?",
    "¿Quién se confunde en público?",
    "¿Quién se queda sin saber dónde meterse?",
    "¿Quién se equivoca pidiendo comida?",
    "¿Quién se queda pillado mirando?",
    "¿Quién se equivoca entrando al baño?",
    "¿Quién habla demasiado alto sin darse cuenta?",
    "¿Quién se ríe solo?",
    "¿Quién se equivoca en una presentación?",
    "¿Quién se bloquea al hablar?",
    "¿Quién dice 'igualmente' cuando no toca?",
    "¿Quién se equivoca contestando?",
    "¿Quién se queda congelado?",
    "¿Quién se equivoca de asiento?",
    "¿Quién se confunde de día?",
    "¿Quién se queda mirando el móvil sin cobertura?",
    "¿Quién se equivoca de turno?",
    "¿Quién se queda sin saber qué decir?",
    "¿Quién se pone nervioso al pedir algo?",
    "¿Quién se equivoca de palabra?",
    "¿Quién se confunde de idioma?",
    "¿Quién se ríe por nervios?",
    "¿Quién se equivoca dando las gracias?",
    "¿Quién se queda en silencio incómodo?",
    "¿Quién se equivoca contando algo personal?",
    "¿Quién se equivoca de contexto?",
    "¿Quién se pone más nervioso?",
    "¿Quién se equivoca al presentarse?",
    "¿Quién se queda sin reacción?",
    "¿Quién pasa más vergüenza?",

    // deporte (50)
    "¿Quién se cansa antes entrenando?",
    "¿Quién pone excusas para no entrenar?",
    "¿Quién se lesiona calentando?",
    "¿Quién odia correr?",
    "¿Quién dice que va al gym y no va?",
    "¿Quién abandona el deporte a la semana?",
    "¿Quién se cree atleta sin entrenar?",
    "¿Quién se rinde antes?",
    "¿Quién se pica más compitiendo?",
    "¿Quién hace trampas jugando?",
    "¿Quién se enfada perdiendo?",
    "¿Quién se lesiona con facilidad?",
    "¿Quién llega tarde a entrenar?",
    "¿Quién no calienta nunca?",
    "¿Quién se cansa subiendo escaleras?",
    "¿Quién presume sin resultados?",
    "¿Quién se queja del ejercicio?",
    "¿Quién odia sudar?",
    "¿Quién se rinde al primer esfuerzo?",
    "¿Quién se flipa con su rendimiento?",
    "¿Quién falta más a entrenar?",
    "¿Quién se lesiona por no estirar?",
    "¿Quién se pica jugando?",
    "¿Quién abandona el partido?",
    "¿Quién se cansa rápido?",
    "¿Quién odia competir?",
    "¿Quién se toma el deporte demasiado en serio?",
    "¿Quién se pica con árbitros?",
    "¿Quién se cree entrenador?",
    "¿Quién se enfada con el equipo?",
    "¿Quién no acepta perder?",
    "¿Quién se queja del árbitro?",
    "¿Quién se rinde mentalmente?",
    "¿Quién abandona por pereza?",
    "¿Quién se lesiona haciendo el tonto?",
    "¿Quién se cree profesional?",
    "¿Quién se pica más entrenando?",
    "¿Quién no sigue el plan?",
    "¿Quién se cansa antes que nadie?",
    "¿Quién abandona primero?",
    "¿Quién se frustra rápido?",
    "¿Quién pone más excusas?",
    "¿Quién se toma descansos eternos?",
    "¿Quién se queja más?",
    "¿Quién se cree mejor de lo que es?",
    "¿Quién se pica en pachangas?",
    "¿Quién se enfada perdiendo?",
    "¿Quién no entrena nada?",
    "¿Quién presume más?",
    "¿Quién dura menos?",

    // pobreza (50)
    "¿Quién siempre está sin dinero?",
    "¿Quién llega a fin de mes por milagro?",
    "¿Quién vive diciendo que no tiene un euro?",
    "¿Quién gasta sin pensar?",
    "¿Quién se queda sin dinero el primer día?",
    "¿Quién siempre pide prestado?",
    "¿Quién nunca devuelve dinero?",
    "¿Quién vive endeudado?",
    "¿Quién compra cosas inútiles?",
    "¿Quién se queja de no tener dinero pero gasta?",
    "¿Quién vive al límite siempre?",
    "¿Quién no sabe ahorrar?",
    "¿Quién se queda sin saldo?",
    "¿Quién vive mirando ofertas?",
    "¿Quién compra lo más barato siempre?",
    "¿Quién estira el dinero al máximo?",
    "¿Quién no controla gastos?",
    "¿Quién siempre va justo?",
    "¿Quién se gasta el sueldo en tonterías?",
    "¿Quién vive con cero ahorros?",
    "¿Quién siempre está en números rojos?",
    "¿Quién pide dinero constantemente?",
    "¿Quién vive quejándose de pobreza?",
    "¿Quién se queda sin dinero en vacaciones?",
    "¿Quién no sabe gestionar su dinero?",
    "¿Quién gasta antes de cobrar?",
    "¿Quién vive contando monedas?",
    "¿Quién no llega a fin de mes?",
    "¿Quién siempre paga lo justo?",
    "¿Quién nunca tiene efectivo?",
    "¿Quién se gasta todo en caprichos?",
    "¿Quién vive con miedo a gastar?",
    "¿Quién siempre dice 'estoy tieso'?",
    "¿Quién vive improvisando económicamente?",
    "¿Quién no ahorra nada?",
    "¿Quién se queda sin dinero saliendo?",
    "¿Quién vive pidiendo favores?",
    "¿Quién siempre debe dinero?",
    "¿Quién se gasta lo que no tiene?",
    "¿Quién vive sin planificación?",
    "¿Quién nunca llega holgado?",
    "¿Quién se queda sin dinero a mitad de mes?",
    "¿Quién vive sobreviviendo?",
    "¿Quién no controla su cuenta?",
    "¿Quién se queja más de dinero?",
    "¿Quién vive de ofertas?",
    "¿Quién compra sin pensar?",
    "¿Quién siempre va justo?",
    "¿Quién nunca ahorra?",
    "¿Quién vive en modo supervivencia?",

    // aventura (50)
    "¿Quién se perdería viajando?",
    "¿Quién se metería en líos por curiosidad?",
    "¿Quién se apunta a cualquier plan loco?",
    "¿Quién se pierde sin GPS?",
    "¿Quién se mete donde no debe?",
    "¿Quién se lanza sin pensar?",
    "¿Quién se pierde en ciudades nuevas?",
    "¿Quién se mete en aventuras absurdas?",
    "¿Quién se apunta a planes peligrosos?",
    "¿Quién se mete en problemas viajando?",
    "¿Quién se perdería en el campo?",
    "¿Quién improvisa sin pensar?",
    "¿Quién se mete en sitios raros?",
    "¿Quién se fía demasiado?",
    "¿Quién se apunta a lo desconocido?",
    "¿Quién se lanza sin plan?",
    "¿Quién se pierde explorando?",
    "¿Quién se mete en líos por aburrimiento?",
    "¿Quién se apunta a cualquier aventura?",
    "¿Quién se pierde en excursiones?",
    "¿Quién se lanza sin medir riesgos?",
    "¿Quién se mete en situaciones raras?",
    "¿Quién improvisa siempre?",
    "¿Quién se fía de desconocidos?",
    "¿Quién se mete en problemas sin querer?",
    "¿Quién se pierde en viajes?",
    "¿Quién se apunta a planes sin pensar?",
    "¿Quién se lanza primero?",
    "¿Quién se mete en aventuras innecesarias?",
    "¿Quién se pierde con facilidad?",
    "¿Quién se apunta a cualquier cosa?",
    "¿Quién improvisa mal?",
    "¿Quién se mete en líos viajando?",
    "¿Quién se lanza sin miedo?",
    "¿Quién se pierde en rutas fáciles?",
    "¿Quién se apunta a aventuras absurdas?",
    "¿Quién se fía demasiado?",
    "¿Quién se mete en problemas por curiosidad?",
    "¿Quién se pierde explorando?",
    "¿Quién se lanza sin pensar?",
    "¿Quién improvisa todo?",
    "¿Quién se mete en líos sin querer?",
    "¿Quién se pierde en viajes cortos?",
    "¿Quién se apunta a cualquier plan?",
    "¿Quién se lanza primero siempre?",
    "¿Quién se mete en aventuras sin sentido?",
    "¿Quién se pierde aunque sea fácil?",
    "¿Quién improvisa demasiado?",
    "¿Quién se mete en problemas por aventura?",
    "¿Quién se apunta a todo?",

    // maldad / rabia / odio (50)
    "¿Quién se enfada con facilidad?",
    "¿Quién guarda rencor?",
    "¿Quién se pica por tonterías?",
    "¿Quién explota sin motivo?",
    "¿Quién se enfada perdiendo?",
    "¿Quién no perdona nada?",
    "¿Quién se cabrea rápido?",
    "¿Quién guarda odio?",
    "¿Quién se pica en discusiones?",
    "¿Quién se enfada por nada?",
    "¿Quién se vuelve borde?",
    "¿Quién se pica con facilidad?",
    "¿Quién responde mal siempre?",
    "¿Quién se enfada sin razón?",
    "¿Quién guarda resentimiento?",
    "¿Quién estalla rápido?",
    "¿Quién se cabrea conduciendo?",
    "¿Quién se enfada con comentarios?",
    "¿Quién no sabe relajarse?",
    "¿Quién se pica discutiendo?",
    "¿Quién se enfada perdiendo juegos?",
    "¿Quién se pone agresivo hablando?",
    "¿Quién guarda odio mucho tiempo?",
    "¿Quién explota emocionalmente?",
    "¿Quién se pica con bromas?",
    "¿Quién se enfada fácilmente?",
    "¿Quién no controla la rabia?",
    "¿Quién se enfada por mensajes?",
    "¿Quién se pica sin sentido?",
    "¿Quién guarda rencores antiguos?",
    "¿Quién se enfada en discusiones?",
    "¿Quién explota rápido?",
    "¿Quién se pica con críticas?",
    "¿Quién se enfada por todo?",
    "¿Quién no sabe perdonar?",
    "¿Quién se cabrea rápido?",
    "¿Quién se pica siempre?",
    "¿Quién se enfada hablando?",
    "¿Quién guarda odio innecesario?",
    "¿Quién explota por tonterías?",
    "¿Quién se enfada sin pensar?",
    "¿Quién se pica con todo?",
    "¿Quién no controla el enfado?",
    "¿Quién se enfada fácilmente?",
    "¿Quién guarda rencor siempre?",
    "¿Quién se cabrea por nada?",
    "¿Quién se pica rápido?",
    "¿Quién explota hablando?",
    "¿Quién se enfada sin motivo?",
    "¿Quién vive enfadado?",

    // felicidad (50)
    "¿Quién se ríe más?",
    "¿Quién disfruta de las pequeñas cosas?",
    "¿Quién sonríe todo el tiempo?",
    "¿Quién contagia buen rollo?",
    "¿Quién se ríe de todo?",
    "¿Quién siempre ve el lado bueno?",
    "¿Quién disfruta cualquier plan?",
    "¿Quién se ríe incluso en problemas?",
    "¿Quién transmite felicidad?",
    "¿Quién siempre está de buen humor?",
    "¿Quién se ríe con facilidad?",
    "¿Quién disfruta del momento?",
    "¿Quién sonríe sin motivo?",
    "¿Quién se toma todo con humor?",
    "¿Quién siempre anima al grupo?",
    "¿Quién se ríe hasta llorar?",
    "¿Quién disfruta de cualquier tontería?",
    "¿Quién vive más feliz?",
    "¿Quién sonríe más?",
    "¿Quién contagia alegría?",
    "¿Quién disfruta incluso del caos?",
    "¿Quién se ríe de sí mismo?",
    "¿Quién siempre está positivo?",
    "¿Quién disfruta la vida?",
    "¿Quién sonríe aunque vaya mal?",
    "¿Quién se ríe más fuerte?",
    "¿Quién disfruta de planes simples?",
    "¿Quién transmite paz?",
    "¿Quién siempre está contento?",
    "¿Quién se ríe con cualquier cosa?",
    "¿Quién ve todo con humor?",
    "¿Quién disfruta estar con amigos?",
    "¿Quién sonríe constantemente?",
    "¿Quién siempre anima?",
    "¿Quién disfruta cualquier situación?",
    "¿Quién vive más relajado?",
    "¿Quién se ríe incluso solo?",
    "¿Quién transmite buena vibra?",
    "¿Quién disfruta el día a día?",
    "¿Quién sonríe aunque esté cansado?",
    "¿Quién siempre encuentra algo bueno?",
    "¿Quién se ríe hasta de problemas?",
    "¿Quién disfruta sin complicarse?",
    "¿Quién vive más feliz?",
    "¿Quién sonríe más veces al día?",
    "¿Quién contagia sonrisas?",
    "¿Quién disfruta cualquier momento?",
    "¿Quién vive con alegría?",
    "¿Quién se ríe más?",
    "¿Quién es más feliz?",
  "¿Quién ha buscado su propio nombre en Google demasiadas veces?",
  "¿Quién se ha reído solo recordando algo vergonzoso?",
  "¿Quién finge escuchar audios en x1 pero los oye en x2?",
  "¿Quién ha ensayado una discusión solo en la ducha?",
  "¿Quién escribe ‘jajaja’ con cara seria?",
  "¿Quién ha contestado ‘igualmente’ cuando no tocaba?",
  "¿Quién ha stalkeado a alguien y ha dado like sin querer?",
  "¿Quién borra mensajes tres veces antes de enviarlos?",
  "¿Quién se ha puesto guapo para ir al súper?",
  "¿Quién ha dicho ‘ya voy’ sin haberse levantado?",
  "¿Quién ha mirado el móvil fingiendo una llamada?",
  "¿Quién ha practicado sonrisas frente al espejo?",
  "¿Quién ha olvidado por qué entró a la cocina?",
  "¿Quién se ha despedido y ha seguido andando en la misma dirección?",
  "¿Quién ha buscado un objeto con el objeto en la mano?",
  "¿Quién ha reído por compromiso y no entendió el chiste?",
  "¿Quién ha fingido saber de un tema por orgullo?",
  "¿Quién ha enviado un audio y lo ha odiado al instante?",
  "¿Quién ha abierto la nevera esperando que aparezca comida nueva?",
  "¿Quién ha dicho ‘cinco minutos’ y han sido cuarenta?",
  "¿Quién ha llorado con un anuncio random?",
  "¿Quién ha hablado con su mascota como si entendiera todo?",
  "¿Quién ha revisado si cerró la puerta tres veces?",
  "¿Quién ha ensayado cómo pedir perdón sin saber por qué?",
  "¿Quién ha pensado ‘si digo esto quedo genial’ y salió fatal?",
  "¿Quién ha dicho ‘me da igual’ pero le importaba muchísimo?",
  "¿Quién ha buscado síntomas y se ha autodiagnosticado mortal?",
  "¿Quién ha mirado a alguien esperando que adivine algo?",
  "¿Quién ha dicho ‘no tengo hambre’ y se comió todo?",
  "¿Quién ha contestado un mensaje con el chat equivocado abierto?",
  "¿Quién ha sentido vergüenza ajena por sí mismo?",
  "¿Quién ha rehecho una historia para que suene mejor?",
  "¿Quién ha dicho ‘es la última’ y no era verdad?",
  "¿Quién ha llegado temprano y ha esperado escondido?",
  "¿Quién ha fingido entender una broma interna?",
  "¿Quién ha dicho ‘sí, claro’ sin escuchar?",
  "¿Quién ha mirado el reloj para no mirar a alguien?",
  "¿Quién ha puesto una alarma y la ha ignorado?",
  "¿Quién ha ensayado una llamada importante y la ha evitado?",
  "¿Quién ha escrito un mensaje larguísimo y lo ha borrado?",
  "¿Quién ha abierto WhatsApp por inercia?",
  "¿Quién ha puesto música triste para sufrir a gusto?",
  "¿Quién ha buscado consejos obvios en Google?",
  "¿Quién ha mentido diciendo ‘estaba ocupado’?",
  "¿Quién ha fingido reírse por audio?",
  "¿Quién ha guardado memes como si fueran oro?",
  "¿Quién ha prometido ‘mañana empiezo’?",
  "¿Quién ha mirado historias esperando aparecer?",
  "¿Quién ha pensado ‘qué hago con mi vida’ a las 3 a.m.?",
  "¿Quién ha comparado su vida con la de Instagram?",
  "¿Quién ha contestado rápido para parecer interesante?",
  "¿Quién ha releído una conversación antigua?",
  "¿Quién ha dejado en visto por pánico?",
  "¿Quién ha escrito ‘ok’ con mil significados?",
  "¿Quién ha puesto excusas creativas?",
  "¿Quién ha fingido confianza sin tenerla?",
  "¿Quién ha hecho drama por un ‘visto’?",
  "¿Quién ha pensado ‘esto no lo supero’ y sí lo superó?",
  "¿Quién ha dicho ‘no pasa nada’ y sí pasaba?",
  "¿Quién ha hablado solo caminando por la calle?",
  "¿Quién ha practicado respuestas ingeniosas tarde?",
  "¿Quién ha puesto cara de interés profesional?",
  "¿Quién ha evitado un saludo incómodo?",
  "¿Quién ha sonreído para no llorar?",
  "¿Quién ha enviado un meme para romper el hielo?",
  "¿Quién ha hecho scroll infinito sin motivo?",
  "¿Quién ha olvidado lo que iba a decir a mitad?",
  "¿Quién ha usado sarcasmo y no se entendió?",
  "¿Quién ha fingido seguridad en una decisión?",
  "¿Quién ha pensado ‘qué acabo de decir’?",
  "¿Quién ha respirado hondo antes de responder?",
  "¿Quién ha ensayado un ‘hola’ perfecto?",
  "¿Quién ha cambiado de opinión en 2 segundos?",
  "¿Quién ha dicho ‘soy así’ como excusa?",
  "¿Quién ha puesto música para motivarse y no hizo nada?",
  "¿Quién ha pensado que un mensaje iba con indirecta?",
  "¿Quién ha respondido con un emoji por miedo?",
  "¿Quién ha buscado validación sutil?",
  "¿Quién ha dicho ‘no me afecta’ y le afectó?",
  "¿Quién ha exagerado un poco ‘sin querer’?",
  "¿Quién ha borrado una foto por inseguridad?",
  "¿Quién ha fingido que no vio a alguien?",
  "¿Quién ha cambiado de tema estratégicamente?",
  "¿Quién ha mirado al suelo para evitar contacto?",
  "¿Quién ha pensado ‘me voy a arrepentir’ y fue así?",
  "¿Quién ha dicho ‘confía en mí’ sin plan?",
  "¿Quién ha pedido consejo y no lo siguió?",
  "¿Quién ha puesto cara neutra por dentro en pánico?",
  "¿Quién ha dicho ‘todo bien’ y no?",
  "¿Quién ha buscado señales donde no había?",
  "¿Quién ha pensado demasiado una respuesta simple?",
  "¿Quién ha enviado un mensaje y ha bloqueado el móvil?",
  "¿Quién ha usado humor para tapar nervios?",
  "¿Quién ha hecho una promesa optimista?",
  "¿Quién ha llegado tarde por llegar pronto?",
  "¿Quién ha fingido no saber para evitar algo?",
  "¿Quién ha dicho ‘yo invito’ y se arrepintió?",
  "¿Quién ha ensayado un ‘no’ educado?",
  "¿Quién ha buscado aprobación con una broma?",
  "¿Quién ha pensado ‘nadie se dará cuenta’?",
  "¿Quién ha evitado una conversación necesaria?",
  "¿Quién ha dicho ‘luego te cuento’ y nunca?",
  "¿Quién ha cambiado de tema con elegancia dudosa?",
  "¿Quién ha fingido sorpresa?",
  "¿Quién ha puesto excusas por cansancio social?",
  "¿Quién ha pensado ‘mejor no digo nada’?",
  "¿Quién ha sonreído por educación extrema?",
  "¿Quién ha dramatizado internamente?",
  "¿Quién ha buscado el momento perfecto y no llegó?",
  "¿Quién ha contestado tarde a propósito?",
  "¿Quién ha hecho un chiste malo con seguridad?",
  "¿Quién ha dicho ‘no soy celoso’?",
  "¿Quién ha sentido mariposas sin motivo?",
  "¿Quién ha hecho un plan y se quedó en casa?",
  "¿Quién ha practicado un ‘sí’ valiente?",
  "¿Quién ha dicho ‘no me juzgues’ primero?",
  "¿Quién ha pensado ‘esto es una señal’?",
  "¿Quién ha fingido desinterés estratégico?",
  "¿Quién ha buscado una excusa elegante?",
  "¿Quién ha puesto una playlist para una conversación?",
  "¿Quién ha sobrepensado un emoji?",
  "¿Quién ha hecho ghosting por ansiedad?",
  "¿Quién ha enviado un ‘jaja’ defensivo?",
  "¿Quién ha cambiado de asiento por comodidad social?",
  "¿Quién ha dicho ‘te escribo luego’?",
  "¿Quién ha evitado el contacto visual heroicamente?",
  "¿Quién ha respirado profundo antes de mandar un meme?",
  "¿Quién ha ensayado una confesión y la guardó?",
  "¿Quién ha dicho ‘no me importa’ mintiendo?",
  "¿Quién ha sentido alivio al cancelar planes?",
  "¿Quién ha fingido entusiasmo con café?",
  "¿Quién ha pensado ‘soy un desastre’ riéndose?",
  "¿Quién ha convertido el caos en anécdota?",
  "¿Quién ha usado humor negro para sobrevivir?",
  "¿Quién ha dicho ‘soy así’ con cariño?",
  "¿Quién ha hecho de tripas corazón?",
  "¿Quién ha aprendido a reírse de sí mismo?",
  "¿Quién ha dicho ‘todo pasa’ y tenía razón?",
  "¿Quién ha abrazado el cringe propio?",
  "¿Quién ha elegido paz antes que razón?",
  "¿Quién ha encontrado felicidad en lo simple?",
  "¿Quién ha brindado por sobrevivir al día?",
  "¿Quién ha reído en el momento menos esperado?",
  "¿Quién ha pensado ‘estoy bien así’?",
  "¿Quién ha celebrado pequeñas victorias?",
  "¿Quién ha sido honesto consigo mismo?",
  "¿Quién ha soltado el control un poco?",
  "¿Quién ha elegido quererse más?"
];
