module.exports = [
  // 1–300: Preguntas seleccionadas
  "¿Quién tiene el historial de búsqueda más turbio?",
  "¿Quién moriría primero en un apocalipsis zombie?",
  "¿Quién se casaría por dinero?",
  "¿Quién tiene más probabilidades de acabar en la cárcel?",
  "¿Quién tiene el ego más grande que su cabeza?",
  "¿Quién es más probable que se una a una secta?",
  "¿Quién tiene peor gusto vistiendo?",
  "¿Quién sería el peor presidente del gobierno?",
  "¿Quién tiene más probabilidades de tener un hijo secreto?",
  "¿Quién finge más orgasmos?",
  "¿Quién llora con películas de Disney?",
  "¿Quién tiene más energía de protagonista porno?",
  "¿Quién es el más falso del grupo?",
  "¿Quién sobreviviría más tiempo en una isla desierta?",
  "¿Quién se ríe de los chistes más inapropiados?",
  "¿Quién liga más cuando sale de fiesta?",
  "¿Quién es más probable que vomite esta noche?",
  "¿Quién es el más tacaño?",
  "¿Quién se haría rico por accidente?",
  "¿Quién es el más cuñado?",
  "¿Quién tarda más en pillar indirectas?",
  "¿Quién enviaría un nude al grupo por error?",
  "¿Quién acabaría siendo influencer sin querer?",
  "¿Quién sería el peor compañero de piso?",
  "¿Quién se engancharía a una estafa piramidal?",
  "¿Quién miente peor?",
  "¿Quién se enamora más rápido?",
  "¿Quién se quedaría dormido en su propia boda?",
  "¿Quién gastaría 500€ en algo inútil?",
  "¿Quién haría ghosting sin remordimientos?",
  "¿Quién tiene más probabilidades de acabar cancelado?",
  "¿Quién siempre llega tarde?",
  "¿Quién se pierde incluso con GPS?",
  "¿Quién tiene más exs?",
  "¿Quién sería peor guardando un secreto?",
  "¿Quién se creería una fake news?",
  "¿Quién haría el ridículo en una primera cita?",
  "¿Quién se olvidaría su propio cumpleaños?",
  "¿Quién sería peor padre/madre?",
  "¿Quién ligaría con alguien solo por interés?",
  "¿Quién se pelearía con un camarero?",
  "¿Quién lloraría borracho a las 4 a.m.?",
  "¿Quién tiene más probabilidades de ser infiel?",
  "¿Quién sería expulsado de un reality show?",
  "¿Quién tiene menos autocontrol?",
  "¿Quién se ofende por todo?",
  "¿Quién tiene menos filtro al hablar?",
  "¿Quién acabaría viviendo con sus padres a los 40?",
  "¿Quién es más probable que mienta en el currículum?",
  "¿Quién se haría un tatuaje horrible borracho?",
  "¿Quién sería peor jefe?",
  "¿Quién se cree más listo de lo que es?",
  "¿Quién copiaría en un examen?",
  "¿Quién se enamora de quien no debe?",
  "¿Quién se vendería por fama?",
  "¿Quién sería el peor testigo en un juicio?",
  "¿Quién siempre exagera sus historias?",
  "¿Quién no aguanta nada el alcohol?",
  "¿Quién siempre pierde el móvil?",
  "¿Quién sería peor espía?",
  "¿Quién sería el primero en caer en una estafa online?",
  "¿Quién se gastaría todo el sueldo el primer día?",
  "¿Quién tiene menos fuerza de voluntad?",
  "¿Quién sería peor jugador de póker?",
  "¿Quién no sabría cuidar una planta?",
  "¿Quién acabaría viviendo en una furgoneta?",
  "¿Quién sería peor compañero de trabajo?",
  "¿Quién hablaría solo en voz alta?",
  "¿Quién tendría un podcast horrible?",
  "¿Quién es más probable que robe toallas de hoteles?",
  "¿Quién siempre se hace la víctima?",
  "¿Quién sería peor profesor?",
  "¿Quién se reiría en un funeral?",
  "¿Quién tiene menos paciencia?",
  "¿Quién sería peor conductor?",
  "¿Quién se olvidaría de pagar una multa?",
  "¿Quién acabaría en una discusión absurda?",
  "¿Quién tiene más probabilidades de ser despedido?",
  "¿Quién sería peor detective?",
  "¿Quién se rendiría primero en un reto?",
  "¿Quién no sobreviviría sin WiFi?",
  "¿Quién sería peor cirujano?",
  "¿Quién se perdería en su propio barrio?",
  "¿Quién tendría más problemas con la ley?",
  "¿Quién no sabe guardar dinero?",
  "¿Quién tiene más probabilidades de arruinar una sorpresa?",
  "¿Quién sería peor político?",
  "¿Quién se haría famoso por algo vergonzoso?",
  "¿Quién mentiría en una cita?",
  "¿Quién sería peor astronauta?",
  "¿Quién no sabe cocinar ni pasta?",
  "¿Quién acabaría discutiendo con un policía?",
  "¿Quién se enfada por perder en un juego?",
  "¿Quién sería peor en un escape room?",
  "¿Quién se dejaría manipular más fácil?",
  "¿Quién siempre busca excusas?",
  "¿Quién tendría más multas acumuladas?",
  "¿Quién sería peor influencer?",
  "¿Quién se queja más?",
  "¿Quién no aguanta una crítica?",
  "¿Quién se metería en un lío solo por curiosidad?",
  "¿Quién tiene más probabilidades de stalkear a su ex?",
  "¿Quién mentiría para quedar bien?",
  "¿Quién se cree protagonista de una serie?",
  "¿Quién haría drama por la cosa más pequeña?",
  "¿Quién se enamora del camarero?",
  "¿Quién sería peor guardián de un secreto?",
  "¿Quién se haría amigo de alguien solo por interés?",
  "¿Quién tiene más probabilidades de discutir por política?",
  "¿Quién se iría de una fiesta sin avisar?",
  "¿Quién siempre promete y nunca cumple?",
  "¿Quién sería el primero en rendirse?",
  "¿Quién exagera más cuando cuenta algo?",
  "¿Quién se ofende aunque sea broma?",
  "¿Quién tiene más probabilidades de desaparecer sin dar señales?",
  "¿Quién se cree más interesante de lo que es?",
  "¿Quién sería peor en una discusión seria?",
  "¿Quién se inventaría una excusa absurda?",
  "¿Quién sería capaz de robar comida del plato de otro?",
  "¿Quién siempre quiere llamar la atención?",
  "¿Quién se arrepiente de escribir mensajes borracho?",
  "¿Quién se pondría celoso sin motivo?",
  "¿Quién tiene más probabilidades de liarla en Navidad?",
  "¿Quién sería el peor organizando un viaje?",
  "¿Quién siempre deja todo para última hora?",
  "¿Quién tiene menos vergüenza?",
  "¿Quién se metería donde no le llaman?",
  "¿Quién acabaría discutiendo con un desconocido?",
  "¿Quién es más probable que se quede sin batería?",
  "¿Quién cancelaría planes en el último momento?",
  "¿Quién haría trampas en un juego de mesa?",
  "¿Quién sería peor compañero de equipo?",
  "¿Quién se pone más pesado cuando bebe?",
  "¿Quién sería incapaz de guardar una sorpresa?",
  "¿Quién tiene más probabilidades de decir algo fuera de lugar?",
  "¿Quién se cree todas las teorías conspiranoicas?",
  "¿Quién se liaría con alguien solo por aburrimiento?",
  "¿Quién se pondría nervioso mintiendo?",
  "¿Quién tiene menos sentido común?",
  "¿Quién se metería en problemas por hablar de más?",
  "¿Quién haría el ridículo delante de mucha gente?",
  "¿Quién se engancharía a un juego absurdo?",
  "¿Quién sería el peor dando consejos?",
  "¿Quién se hace el interesante constantemente?",
  "¿Quién acabaría discutiendo con el GPS?",
  "¿Quién sería incapaz de improvisar?",
  "¿Quién se estresa más sin motivo?",
  "¿Quién siempre quiere tener la última palabra?",
  "¿Quién se frustraría jugando algo fácil?",
  "¿Quién sería peor manteniendo la calma?",
  "¿Quién se dejaría llevar por la presión del grupo?",
  "¿Quién acabaría hablando solo en público?",
  "¿Quién sería peor negociando?",
  "¿Quién se pondría dramático por un mensaje en visto?",
  "¿Quién tiene más probabilidades de malinterpretar todo?",
  "¿Quién sería peor compañero de viaje?",
  "¿Quién se rayaría por nada?",
  "¿Quién se obsesiona más?",
  "¿Quién sería el más intenso?",
  "¿Quién acabaría pidiendo perdón sin saber por qué?",
  "¿Quién olería peor después de no ducharse una semana?",
  "¿Quién se comería un sándwich del suelo?",
  "¿Quién sería más probable que tropiece con nada?",
  "¿Quién habla como si fuera la cosa más importante del mundo?",
  "¿Quién tiene el sentido del humor más retrasado?",
  "¿Quién se da de cabezazos contra las puertas?",
  "¿Quién se pondría a llorar viendo un anuncio de seguros?",
  "¿Quién sería peor haciendo un baile viral?",
  "¿Quién se cae subiendo escaleras?",
  "¿Quién se merecería una patada en el culo regularmente?",
  "¿Quién confundiría la sal con el azúcar en la sopa?",
  "¿Quién llamaría a la policía por comida fría?",
  "¿Quién tiene un fetiche vergonzoso?",
  "¿Quién se pegaría con una puerta automática?",
  "¿Quién se quedaría atrapado en un armario?",
  "¿Quién baila como si tuviera un espasmo?",
  "¿Quién se comería la pasta sin cocinar?",
  "¿Quién diría la ley de Murphy como consejo de vida?",
  "¿Quién se haría pis en el sofá riéndose?",
  "¿Quién sería incapaz de abrir una lata de conservas?",
  "¿Quién llamaría al servicio técnico para reiniciar el móvil?",
  "¿Quién se pondría a llorar jugando videojuegos en modo fácil?",
  "¿Quién se acuerda de toda en el grupo menos de los cumpleaños?",
  "¿Quién se cree que su mal humor es una personalidad?",
  "¿Quién buscaría 'cómo respirar' en Google?",
  "¿Quién diría 'no duele' justo antes de desmayarse?",
  "¿Quién sería más probable que se quemara una tostada?",
  "¿Quién se cae por intentar ir guay?",
  "¿Quién vería un video de miedo y tendría pesadillas una semana?",
  "¿Quién perdería la batalla contra un troll de internet?",
  "¿Quién se quedaría con hambre porque la comida 'se ve extraña'?",
  "¿Quién sería la mascota perfecta para un asilo?",
  "¿Quién se engancharía a un juego para móviles tipo Candy Crush?",
  "¿Quién se burlaba en redes de alguien que luego conoce?",
  "¿Quién tiene fotos de su mascota en el carnet de identidad?",
  "¿Quién se ahogaría con agua?",
  "¿Quién sería más probable que ganara una tragaperra?",
  "¿Quién diría 'soy muy guapo/a' en serio?",
  "¿Quién sería peor en un karaoke?",
  "¿Quién se olvidaría el nombre de alguien mirándole a la cara?",
  "¿Quién se cree que todo es una señal del universo?",
  "¿Quién se haría análisis de sangre por un moretón?",
  "¿Quién se vestiría con pijama a una boda?",
  "¿Quién diría mentiras piadosas constantemente?",
  "¿Quién se comportaría como un pequeño tirano borracho?",
  "¿Quién gritaría viendo una película de terror?",
  "¿Quién haría un TikTok horrible?",
  "¿Quién se burlaría de su mejor amigo en las redes?",
  "¿Quién tendría un feed lleno de contenido cringe?",
  "¿Quién se cree millonario siendo pobre?",
  "¿Quién se quejaría de estar cansado sin hacer nada?",
  "¿Quién sería peor en una fuga de la cárcel?",
  "¿Quién se cree que sabe de ciencia viendo TikToks?",
  "¿Quién se tatuaría un error ortográfico?",
  "¿Quién dejaría morir una planta cactus?",
  "¿Quién sería la peor persona para pedir dinero prestado?",
  "¿Quién se lo gastaría todo en cosas inútiles de Wish?",
  "¿Quién lidaría con la noticia de que come algo de lo que tiene alergia?",
  "¿Quién se tropezaría en una cuerda invisible?",
  "¿Quién diría que necesita 'vibraciones positivas'?",
  "¿Quién se creería adivino después de acertar algo una vez?",
  "¿Quién sería más probable que cagase en un examen oral?",
  "¿Quién se comería toda la comida del congelador porque se aburre?",
  "¿Quién sería incapaz de despedirse de una llamada telefónica?",
  "¿Quién se bufaría por WhatsApp?",
  "¿Quién se rascaría en los sitios más inapropiados?",
  "¿Quién sería peor en un job interview?",
  "¿Quién se vestiría con chanclas a una reunión importante?",
  "¿Quién tendría un olor corporal insoportable?",
  "¿Quién se deprimiría por una pregunta de un quiz de internet?",
  "¿Quién sería el primero en borrar sus chats?",
  "¿Quién presionaría los botones del ascensor múltiples veces?",
  "¿Quién se engancharía a una serie basura?",
  "¿Quién comería directamente de la olla?",
  "¿Quién sería más probable que se durmiera en una conversación?",
  "¿Quién se cree que su comida hecha mal es un arte?",
  "¿Quién gritaría en un cine?",
  "¿Quién se comería un cubo de hielo en un restaurante fancy?",
  "¿Quién sería peor limpiando?",
  "¿Quién sería incapaz de seguir instrucciones simples?",
  "¿Quién abriría la puerta del frigorífico 50 veces en 5 minutos?",
  "¿Quién se perdería en IKEA?",
  "¿Quién se comería toda una caja de galletas de una sentada?",
  "¿Quién sería peor armando un mueble?",
  "¿Quién se cree que es superior pero no puede ni atarse los cordones?",
  "¿Quién diría 'no tenía hambre' comiendo todo?",
  "¿Quién se ofrecería a llevar algo y no lo haría?",
  "¿Quién se cree que la música que escucha es superior a la de todos?",
  "¿Quién se enamora después de la primera cita?",
  "¿Quién confunde cariño con obsesión?",
  "¿Quién se ilusiona demasiado rápido?",
  "¿Quién se enamora de personas imposibles?",
  "¿Quién tiene peor gusto eligiendo pareja?",
  "¿Quién se queda enganchado a su ex?",
  "¿Quién se enamora del primer halago?",
  "¿Quién mezcla amor con dependencia?",
  "¿Quién se ilusiona aunque sepa que no hay futuro?",
  "¿Quién se hace películas en la cabeza?",
  "¿Quién se enamora del amor, no de la persona?",
  "¿Quién manda mensajes a las 3 a.m. arrepintiéndose luego?",
  "¿Quién se pone celoso sin motivo?",
  "¿Quién idealiza demasiado a su pareja?",
  "¿Quién se enamora de quien no le conviene?",
  "¿Quién confunde atracción con amor eterno?",
  "¿Quién vuelve con su ex por aburrimiento?",
  "¿Quién se declara borracho?",
  "¿Quién se enamora del camarero?",
  "¿Quién se engancha emocionalmente demasiado fácil?",
  "¿Quién sufre más por amor?",
  "¿Quién se enamora de alguien que no le hace caso?",
  "¿Quién se hace la víctima en relaciones?",
  "¿Quién se enamora por mensajes?",
  "¿Quién se ilusiona con señales inexistentes?",
  "¿Quién se ralla por no recibir respuesta?",
  "¿Quién se cree en una peli romántica?",
  "¿Quién se enamora en vacaciones?",
  "¿Quién se flipa con el amor a distancia?",
  "¿Quién se enamora de la idea de alguien?",
  "¿Quién se pone intenso demasiado pronto?",
  "¿Quién confunde pasión con drama?",
  "¿Quién se enamora del físico solamente?",
  "¿Quién se ilusiona con promesas vacías?",
  "¿Quién se enamora del que pasa de él/ella?",
  "¿Quién se cree que el amor lo arregla todo?",
  "¿Quién se engancha emocionalmente sin pensar?",
  "¿Quién se enamora cada dos semanas?",
  "¿Quién dramatiza por amor?",
  "¿Quién sufre por personas que no lo merecen?",
  "¿Quién se enamora aunque le hagan daño?",
  "¿Quién vuelve a caer siempre?",
  "¿Quién confunde costumbre con amor?",
  "¿Quién vive el amor como una telenovela?",
  "¿Quién se obsesiona más en pareja?",
  "¿Quién se enamora sin usar la cabeza?",
  "¿Quién ama más de lo que recibe?",
  "¿Quién se ralla por amor constantemente?",
  "¿Quién se ilusiona aunque todo vaya mal?",
  "¿Quién se ha enamorado de alguien imposible de alcanzar?",
  "¿Quién envía mensajes de amor sin esperar respuesta?",
  "¿Quién ha enviado un mensaje romántico por error al grupo?",
  "¿Quién se ha declarado borracho/a sin pensarlo?",
  "¿Quién ha revisado el móvil de su pareja sin permiso?",
  "¿Quién se ilusiona por una sola mirada?",
  "¿Quién ha hecho un stalkeo nocturno en redes?",
  "¿Quién se obsesiona con un crush durante semanas?",
  "¿Quién confunde atracción con amor eterno?",
  "¿Quién ha coqueteado por aburrimiento?",
  "¿Quién ha tenido citas solo por interés?",
  "¿Quién ha hecho drama por celos sin motivo?",
  "¿Quién se ha enamorado de un amigo?",
  "¿Quién ha mandado emojis insinuantes por error?",
  "¿Quién ha fingido amor para conseguir algo?",
  "¿Quién se cree protagonista de una historia romántica?",
  "¿Quién se engancha emocionalmente en vacaciones?",
  "¿Quién ha idealizado a alguien demasiado rápido?",
  "¿Quién vuelve con su ex solo por nostalgia?",
  "¿Quién escribe poemas que nadie pide?",
  "¿Quién se enamora de su propio reflejo?",
  "¿Quién confunde una amistad con romance?",
  "¿Quién se obsesiona con cada ‘me gusta’ recibido?",
  "¿Quién ha hecho drama por un mensaje no contestado?",
  "¿Quién se pone celoso por cualquier tontería?",
  "¿Quién envía fotos para llamar la atención?",
  "¿Quién ha coqueteado con alguien comprometido?",
  "¿Quién se ilusiona con promesas vacías?",
  "¿Quién ha revisado el historial de mensajes de alguien?",
  "¿Quién ha hecho ‘ghosting’ alguna vez?",
  "¿Quién se enamora del físico sin conocer nada más?",
  "¿Quién ha enviado nudes sin querer?",
  "¿Quién ha fingido interés romántico para conseguir comida?",
  "¿Quién se ralla por mensajes antiguos?",
  "¿Quién ha enviado un mensaje incómodo pensando que era gracioso?",
  "¿Quién se ha enamorado de alguien que no le habla?",
  "¿Quién manda stickers románticos sin contexto?",
  "¿Quién se ilusiona por una conversación de 2 minutos?",
  "¿Quién ha hecho drama por un like no recibido?",
  "¿Quién ha idealizado un crush de Instagram?",
  "¿Quién ha dicho ‘te amo’ sin sentirlo realmente?",
  "¿Quién se obsesiona con cada comentario de su pareja?",
  "¿Quién hace indirectas públicas por alguien?",
  "¿Quién se pone intenso en chats grupales románticos?",
  "¿Quién ha inventado historias de amor para impresionar?",
  "¿Quién ha revisado exs de sus amigos por curiosidad?",
  "¿Quién ha hecho un plan romántico absurdo?",
  "¿Quién se ilusiona con personas que no le conocen?",
  "¿Quién se pone nervioso/a enviando un simple mensaje?",
  "¿Quién ha enviado un audio romántico sin querer?",
  "¿Quién se enamora del mismo crush varias veces?",
  "¿Quién dramatiza por amor aunque todo esté bien?",

  // 51–100 Vergüenza / situaciones incómodas
  "¿Quién se ha caído en público y se ha reído?",
  "¿Quién ha hablado solo en la calle?",
  "¿Quién ha saludado a alguien que no conocía?",
  "¿Quién se ha quedado bloqueado al hablar con extraños?",
  "¿Quién ha enviado un mensaje al chat equivocado?",
  "¿Quién ha tenido un chiste que nadie entendió?",
  "¿Quién ha hecho un comentario inapropiado sin querer?",
  "¿Quién ha confundido nombres en público?",
  "¿Quién se ha reído en el momento menos adecuado?",
  "¿Quién ha contado un secreto por error?",
  "¿Quién ha dado like a algo vergonzoso en redes?",
  "¿Quién ha caminado hacia la dirección equivocada?",
  "¿Quién ha saludado a alguien que no le saludaba?",
  "¿Quién se ha tropezado en silencio incómodo?",
  "¿Quién ha enviado mensajes que luego se arrepintió?",
  "¿Quién se ha confundido de conversación de grupo?",
  "¿Quién ha quedado en blanco hablando?",
  "¿Quién ha cometido un error al presentar a alguien?",
  "¿Quién se ha bloqueado al hablar frente a alguien importante?",
  "¿Quién ha puesto el micrófono abierto por accidente?",
  "¿Quién se ha confundido de baño?",
  "¿Quién ha dicho algo que nadie entendió?",
  "¿Quién ha olvidado lo que iba a decir?",
  "¿Quién ha enviado memes inapropiados por accidente?",
  "¿Quién ha bailado ridículamente sin darse cuenta?",
  "¿Quién ha hecho TikTok vergonzoso y se arrepintió?",
  "¿Quién ha puesto un filtro ridículo sin querer?",
  "¿Quién se ha reído de algo serio sin querer?",
  "¿Quién ha escrito algo que parecía gracioso y no lo era?",
  "¿Quién ha mostrado fotos vergonzosas por error?",
  "¿Quién ha cantado mal en público?",
  "¿Quién ha hecho drama por tonterías delante de todos?",
  "¿Quién ha enviado un audio mal interpretado?",
  "¿Quién ha contestado mal por confusión?",
  "¿Quién ha mostrado emociones exageradas en público?",
  "¿Quién ha reaccionado tarde a algo importante?",
  "¿Quién ha hecho gestos ridículos sin darse cuenta?",
  "¿Quién se ha confundido de grupo al hablar?",
  "¿Quién ha hecho ruido embarazoso sin querer?",
  "¿Quién ha leído mal algo y reaccionó mal?",
  "¿Quién ha dicho algo fuera de contexto y nadie entendió?",
  "¿Quién ha actuado raro por vergüenza?",
  "¿Quién ha respondido ‘sí’ sin escuchar?",
  "¿Quién ha perdido el hilo en medio de la historia?",
  "¿Quién se ha confundido al pedir comida?",
  "¿Quién ha actuado dramáticamente por nada?",
  "¿Quién ha hecho muecas raras sin querer?",
  "¿Quién ha imitado mal a alguien y quedó ridículo?",
  "¿Quién se ha quedado atrapado en un momento incómodo?",
  "¿Quién ha confundido señales sociales y reaccionó mal?",

  // 101–150 Videojuegos / frikis
  "¿Quién se enfada perdiendo en Mario Kart?",
  "¿Quién rompe el mando jugando?",
  "¿Quién se pica con facilidad en juegos online?",
  "¿Quién abandona partidas si va perdiendo?",
  "¿Quién grita al jugar multijugador?",
  "¿Quién se obsesiona con conseguir logros absurdos?",
  "¿Quién juega hasta altas horas de la noche?",
  "¿Quién se frustra con tutoriales?",
  "¿Quién no entiende la historia de los videojuegos?",
  "¿Quién culpa al lag siempre?",
  "¿Quién juega sin seguir instrucciones?",
  "¿Quién juega con volumen demasiado alto?",
  "¿Quién se cree pro y no lo es?",
  "¿Quién ragequittea constantemente?",
  "¿Quién se obsesiona con su personaje favorito?",
  "¿Quién se pica con jugadores novatos?",
  "¿Quién gasta dinero en skins innecesarias?",
  "¿Quién juega mientras hace otra cosa y pierde?",
  "¿Quién insulta NPCs sin motivo?",
  "¿Quién se engancha a juegos absurdos de móvil?",
  "¿Quién discute con compañeros de equipo online?",
  "¿Quién se toma los videojuegos demasiado en serio?",
  "¿Quién presume de victorias exageradas?",
  "¿Quién pierde siempre y se enfada?",
  "¿Quién intenta hacer trucos imposibles y falla?",
  "¿Quién grita a la pantalla sin motivo?",
  "¿Quién se obsesiona con rankings y puntos?",
  "¿Quién juega mientras come y derrama todo?",
  "¿Quién intenta engañar al juego sin éxito?",
  "¿Quién se emociona demasiado por historias del juego?",
  "¿Quién culpa al mando aunque no sea su culpa?",
  "¿Quién se frustra con puzzles fáciles?",
  "¿Quién juega solo por venganza en línea?",
  "¿Quién se enoja perdiendo partidas simples?",
  "¿Quién intenta hacer speedrun sin entrenar?",
  "¿Quién se obsesiona con coleccionables inútiles?",
  "¿Quién se frustra con misiones sencillas?",
  "¿Quién se distrae mientras juega y muere?",
  "¿Quién se toma juegos cooperativos demasiado en serio?",
  "¿Quién se enfada por errores de otros jugadores?",
  "¿Quién se obsesiona con hacks y mods?",
  "¿Quién se queda AFK en momentos importantes?",
  "¿Quién abandona juegos por tonterías?",
  "¿Quién se pone nervioso con enemigos fáciles?",
  "¿Quién no respeta las reglas del juego?",
  "¿Quién se obsesiona con niveles que ya pasó?",
  "¿Quién se frustra al perder loot?",
  "¿Quién intenta copiar estrategias y falla?",
  "¿Quién grita de alegría por victorias pequeñas?",
  "¿Quién se enfada por bugs del juego?",

  // 151–200 Locuras / impulsos absurdos
  "¿Quién haría un viaje sin planear nada?",
  "¿Quién se apuntaría a retos peligrosos por aburrimiento?",
  "¿Quién haría cosas solo por curiosidad?",
  "¿Quién improvisa planes sin pensarlo?",
  "¿Quién se lanza a aventuras sin medir riesgos?",
  "¿Quién hace locuras por ganar likes?",
  "¿Quién confía demasiado en desconocidos?",
  "¿Quién se pierde fácilmente explorando?",
  "¿Quién se mete en problemas por diversión?",
  "¿Quién hace bromas que salen mal?",
  "¿Quién arruina sorpresas por curiosidad?",
  "¿Quién intenta cosas imposibles sin ayuda?",
  "¿Quién se mete donde no le llaman?",
  "¿Quién se lanza a experiencias absurdas?",
  "¿Quién improvisa todo sin pensar en consecuencias?",
  "¿Quién participa en planes raros solo por moda?",
  "¿Quién se mete en aventuras sin razón?",
  "¿Quién se lanza primero a cualquier actividad?",
  "¿Quién intenta hacer trucos sin práctica?",
  "¿Quién se apunta a planes arriesgados?",
  "¿Quién improvisa con todo tipo de comida?",
  "¿Quién se mete en problemas por probar cosas nuevas?",
  "¿Quién actúa sin pensar en público?",
  "¿Quién arruina juegos o retos por curiosidad?",
  "¿Quién hace experimentos tontos en casa?",
  "¿Quién confía en todo el mundo demasiado rápido?",
  "¿Quién improvisa viajes sin preparación?",
  "¿Quién se lanza a cualquier plan absurdo?",
  "¿Quién se mete en líos por aburrimiento?",
  "¿Quién se lanza a cualquier aventura absurda?",
  "¿Quién confía en planes que parecen imposibles?",
  "¿Quién improvisa sin plan B?",
  "¿Quién hace apuestas absurdas y pierde?",
  "¿Quién se mete en peleas sin motivo?",
  "¿Quién intenta hacer retos virales y fracasa?",
  "¿Quién se lanza a actividades peligrosas sin miedo?",
  "¿Quién improvisa cualquier cosa y sale mal?",
  "¿Quién se mete en aventuras innecesarias?",
  "¿Quién confía demasiado en sus amigos para cosas arriesgadas?",
  "¿Quién actúa sin pensar en las consecuencias?",
  "¿Quién hace cosas ridículas solo por diversión?",
  "¿Quién se lanza a planes improvisados?",
  "¿Quién se mete en situaciones absurdas sin querer?",
  "¿Quién hace experimentos peligrosos en casa?",
  "¿Quién intenta superar retos imposibles?",
  "¿Quién se apunta a cualquier aventura por impulsos?",
  "¿Quién improvisa incluso en situaciones serias?",
  "¿Quién actúa como si nada pudiera salir mal?",
  "¿Quién se mete en problemas por curiosidad?",
  "¿Quién se lanza sin medir riesgos?",

  // 201–250 Maldad / rabia / odio / venganza
  "¿Quién se venganza por tonterías?",
  "¿Quién guarda secretos para usarlos después?",
  "¿Quién se enfada por comentarios pequeños?",
  "¿Quién explota por nada?",
  "¿Quién se pone agresivo en discusiones?",
  "¿Quién no sabe perdonar nunca?",
  "¿Quién se obsesiona con rencores pasados?",
  "¿Quién se cabrea sin razón?",
  "¿Quién se pica con bromas tontas?",
  "¿Quién explota en redes sociales?",
  "¿Quién responde mal siempre?",
  "¿Quién se enfada con facilidad?",
  "¿Quién se vuelve borde sin motivo?",
  "¿Quién se obsesiona con críticas recibidas?",
  "¿Quién guarda resentimiento mucho tiempo?",
  "¿Quién se enoja fácilmente jugando?",
  "¿Quién se cabrea conduciendo sin motivo?",
  "¿Quién se enfada en discusiones de grupo?",
  "¿Quién no controla la rabia?",
  "¿Quién explota emocionalmente sin aviso?",
  "¿Quién se pica por comentarios sin importancia?",
  "¿Quién guarda odio innecesario?",
  "¿Quién se cabrea por mensajes absurdos?",
  "¿Quién se enfada con desconocidos sin razón?",
  "¿Quién explota hablando sin control?",
  "¿Quién se obsesiona con venganzas pequeñas?",
  "¿Quién se enfada por todo?",
  "¿Quién se pica fácilmente en juegos o retos?",
  "¿Quién explota emocionalmente con cualquier situación?",
  "¿Quién guarda rencores antiguos?",
  "¿Quién se pone agresivo hablando?",
  "¿Quién se enfada con amigos sin motivo?",
  "¿Quién se obsesiona con problemas pequeños?",
  "¿Quién explota cuando alguien se equivoca?",
  "¿Quién se enfada por tonterías del día a día?",
  "¿Quién se cabrea con facilidad en grupo?",
  "¿Quién se pica con comentarios de conocidos?",
  "¿Quién se enfada con facilidad en redes?",
  "¿Quién no deja pasar nada sin molestarse?",
  "¿Quién se obsesiona con injusticias pequeñas?",
  "¿Quién explota por discusiones ridículas?",
  "¿Quién se cabrea cuando alguien no le escucha?",
  "¿Quién guarda rencor aunque pase el tiempo?",
  "¿Quién se enfada por detalles insignificantes?",
  "¿Quién se pica por nada?",
  "¿Quién explota por comentarios absurdos?",
  "¿Quién se cabrea aunque la situación sea trivial?",
  "¿Quién se obsesiona con enemigos imaginarios?",
  "¿Quién se enfada más de la cuenta?",
  "¿Quién guarda rencor aunque no le importe realmente?",

  // 251–300 Hábitos raros / absurdos / curiosos
  "¿Quién se lava los dientes cantando?",
  "¿Quién habla con la comida antes de comer?",
  "¿Quién hace listas de todo por compulsión?",
  "¿Quién guarda objetos inútiles por nostalgia?",
  "¿Quién se acuesta con luces encendidas por miedo?",
  "¿Quién hace rituales tontos antes de dormir?",
  "¿Quién habla solo en la ducha?",
  "¿Quién se prueba ropa absurda antes de salir?",
  "¿Quién se obsesiona con la limpieza de manera ridícula?",
  "¿Quién colecciona cosas inútiles?",
  "¿Quién verifica cosas 10 veces antes de salir?",
  "¿Quién habla con plantas creyendo que entienden?",
  "¿Quién tiene manías extrañas al comer?",
  "¿Quién ordena objetos sin sentido?",
  "¿Quién se toma selfies en situaciones absurdas?",
  "¿Quién sigue rutinas absurdas sin motivo?",
  "¿Quién habla con objetos como si fueran amigos?",
  "¿Quién se ríe de sí mismo constantemente?",
  "¿Quién se obsesiona con sonidos molestos?",
  "¿Quién hace experimentos caseros sin sentido?",
  "¿Quién se inventa historias para impresionar?",
  "¿Quién revisa cosas que ya revisó?",
  "¿Quién toca cosas innecesariamente varias veces?",
  "¿Quién hace drama por cosas mínimas?",
  "¿Quién prueba comidas raras por aburrimiento?",
  "¿Quién colecciona stickers sin usar?",
  "¿Quién guarda mensajes absurdos por nostalgia?",
  "¿Quién se obsesiona con colores de objetos?",
  "¿Quién organiza cosas por categorías ridículas?",
  "¿Quién se pone nervioso sin razón?",
  "¿Quién intenta hacer malabares sin saber?",
  "¿Quién se obsesiona con detalles mínimos?",
  "¿Quién hace bromas que nadie entiende?",
  "¿Quién toma notas de todo lo que hace?",
  "¿Quién se inventa reglas en juegos?",
  "¿Quién sigue rutinas absurdas diariamente?",
  "¿Quién habla consigo mismo para motivarse?",
  "¿Quién hace caras raras mientras come?",
  "¿Quién organiza su habitación de manera extrema?",
  "¿Quién colecciona cosas rotas?",
  "¿Quién hace chistes malos y se ríe solo?",
  "¿Quién repite palabras sin darse cuenta?",
  "¿Quién se obsesiona con patrones absurdos?",
  "¿Quién prueba objetos como si fueran comida?",
  "¿Quién actúa como si todo fuera un reto?",
  "¿Quién hace listas de compras ridículas?",
  "¿Quién se inventa conversaciones imaginarias?",
  "¿Quién se obsesiona con emojis específicos?",
  "¿Quién se ríe de chistes que no entendió?",
  "¿Quién intenta imitar animales en público?",
  "¿Quién colecciona basura por diversión?",
  "¿Quién se obsesiona con su reflejo en cualquier espejo?",
];
