module.exports = [
    // 1–20
    "¿Quién tiene el historial de búsqueda más turbio?",
    "¿Quién moriría primero en un apocalipsis zombie?",
    "¿Quién se casaría por dinero?",
    "¿Quién tiene más probabilidades de acabar en la cárcel?",
    "¿Quién tiene el ego más grande que su cabeza?",
    "¿Quién es más probable que se una a una secta?",
    "¿Quién tiene peor gusto vistiendo?",
    "¿Quién sería el peor presidente del gobierno?",
    "¿Quién tiene más probabilidades de tener un hijo secreto?",
    "¿Quién finge más orgasmos?",
    "¿Quién llora con películas de Disney?",
    "¿Quién tiene más energía de protagonista porno?",
    "¿Quién es el más falso del grupo?",
    "¿Quién sobreviviría más tiempo en una isla desierta?",
    "¿Quién se ríe de los chistes más inapropiados?",
    "¿Quién liga más cuando sale de fiesta?",
    "¿Quién es más probable que vomite esta noche?",
    "¿Quién es el más tacaño?",
    "¿Quién se haría rico por accidente?",
    "¿Quién es el más cuñado?",

    // 21–40
    "¿Quién tarda más en pillar indirectas?",
    "¿Quién enviaría un nude al grupo por error?",
    "¿Quién acabaría siendo influencer sin querer?",
    "¿Quién sería el peor compañero de piso?",
    "¿Quién se engancharía a una estafa piramidal?",
    "¿Quién miente peor?",
    "¿Quién se enamora más rápido?",
    "¿Quién se quedaría dormido en su propia boda?",
    "¿Quién gastaría 500€ en algo inútil?",
    "¿Quién haría ghosting sin remordimientos?",
    "¿Quién tiene más probabilidades de acabar cancelado?",
    "¿Quién siempre llega tarde?",
    "¿Quién se pierde incluso con GPS?",
    "¿Quién tiene más exs?",
    "¿Quién sería peor guardando un secreto?",
    "¿Quién se creería una fake news?",
    "¿Quién haría el ridículo en una primera cita?",
    "¿Quién se olvidaría su propio cumpleaños?",
    "¿Quién sería peor padre/madre?",
    "¿Quién ligaría con alguien solo por interés?",

    // 41–60
    "¿Quién se pelearía con un camarero?",
    "¿Quién lloraría borracho a las 4 a.m.?",
    "¿Quién tiene más probabilidades de ser infiel?",
    "¿Quién sería expulsado de un reality show?",
    "¿Quién tiene menos autocontrol?",
    "¿Quién se ofende por todo?",
    "¿Quién tiene menos filtro al hablar?",
    "¿Quién acabaría viviendo con sus padres a los 40?",
    "¿Quién es más probable que mienta en el currículum?",
    "¿Quién se haría un tatuaje horrible borracho?",
    "¿Quién sería peor jefe?",
    "¿Quién se cree más listo de lo que es?",
    "¿Quién copiaría en un examen?",
    "¿Quién se enamora de quien no debe?",
    "¿Quién se vendería por fama?",
    "¿Quién sería el peor testigo en un juicio?",
    "¿Quién siempre exagera sus historias?",
    "¿Quién no aguanta nada el alcohol?",
    "¿Quién siempre pierde el móvil?",
    "¿Quién sería peor espía?",

    // 61–80
    "¿Quién sería el primero en caer en una estafa online?",
    "¿Quién se gastaría todo el sueldo el primer día?",
    "¿Quién tiene menos fuerza de voluntad?",
    "¿Quién sería peor jugador de póker?",
    "¿Quién no sabría cuidar una planta?",
    "¿Quién acabaría viviendo en una furgoneta?",
    "¿Quién sería peor compañero de trabajo?",
    "¿Quién hablaría solo en voz alta?",
    "¿Quién tendría un podcast horrible?",
    "¿Quién es más probable que robe toallas de hoteles?",
    "¿Quién siempre se hace la víctima?",
    "¿Quién sería peor profesor?",
    "¿Quién se reiría en un funeral?",
    "¿Quién tiene menos paciencia?",
    "¿Quién sería peor conductor?",
    "¿Quién se olvidaría de pagar una multa?",
    "¿Quién acabaría en una discusión absurda?",
    "¿Quién tiene más probabilidades de ser despedido?",
    "¿Quién sería peor detective?",
    "¿Quién se rendiría primero en un reto?",

    // 81–100
    "¿Quién no sobreviviría sin WiFi?",
    "¿Quién sería peor cirujano?",
    "¿Quién se perdería en su propio barrio?",
    "¿Quién tendría más problemas con la ley?",
    "¿Quién no sabe guardar dinero?",
    "¿Quién tiene más probabilidades de arruinar una sorpresa?",
    "¿Quién sería peor político?",
    "¿Quién se haría famoso por algo vergonzoso?",
    "¿Quién mentiría en una cita?",
    "¿Quién sería peor astronauta?",
    "¿Quién no sabe cocinar ni pasta?",
    "¿Quién acabaría discutiendo con un policía?",
    "¿Quién se enfada por perder en un juego?",
    "¿Quién sería peor en un escape room?",
    "¿Quién se dejaría manipular más fácil?",
    "¿Quién siempre busca excusas?",
    "¿Quién tendría más multas acumuladas?",
    "¿Quién sería peor influencer?",
    "¿Quién se queja más?",
    "¿Quién no aguanta una crítica?",

    "¿Quién se metería en un lío solo por curiosidad?",
    "¿Quién tiene más probabilidades de stalkear a su ex?",
    "¿Quién mentiría para quedar bien?",
    "¿Quién se cree protagonista de una serie?",
    "¿Quién haría drama por la cosa más pequeña?",
    "¿Quién se enamora del camarero?",
    "¿Quién sería peor guardián de un secreto?",
    "¿Quién se haría amigo de alguien solo por interés?",
    "¿Quién tiene más probabilidades de discutir por política?",
    "¿Quién se iría de una fiesta sin avisar?",
    "¿Quién siempre promete y nunca cumple?",
    "¿Quién sería el primero en rendirse?",
    "¿Quién exagera más cuando cuenta algo?",
    "¿Quién se ofende aunque sea broma?",
    "¿Quién tiene más probabilidades de desaparecer sin dar señales?",
    "¿Quién se cree más interesante de lo que es?",
    "¿Quién sería peor en una discusión seria?",
    "¿Quién se inventaría una excusa absurda?",
    "¿Quién sería capaz de robar comida del plato de otro?",
    "¿Quién siempre quiere llamar la atención?",

    "¿Quién se arrepiente de escribir mensajes borracho?",
    "¿Quién se pondría celoso sin motivo?",
    "¿Quién tiene más probabilidades de liarla en Navidad?",
    "¿Quién sería el peor organizando un viaje?",
    "¿Quién siempre deja todo para última hora?",
    "¿Quién tiene menos vergüenza?",
    "¿Quién se metería donde no le llaman?",
    "¿Quién acabaría discutiendo con un desconocido?",
    "¿Quién es más probable que se quede sin batería?",
    "¿Quién cancelaría planes en el último momento?",
    "¿Quién haría trampas en un juego de mesa?",
    "¿Quién sería peor compañero de equipo?",
    "¿Quién se pone más pesado cuando bebe?",
    "¿Quién sería incapaz de guardar una sorpresa?",
    "¿Quién tiene más probabilidades de decir algo fuera de lugar?",
    "¿Quién se cree todas las teorías conspiranoicas?",
    "¿Quién se liaría con alguien solo por aburrimiento?",
    "¿Quién se pondría nervioso mintiendo?",
    "¿Quién tiene menos sentido común?",
    "¿Quién se metería en problemas por hablar de más?",

    "¿Quién haría el ridículo delante de mucha gente?",
    "¿Quién se engancharía a un juego absurdo?",
    "¿Quién sería el peor dando consejos?",
    "¿Quién se hace el interesante constantemente?",
    "¿Quién acabaría discutiendo con el GPS?",
    "¿Quién sería incapaz de improvisar?",
    "¿Quién se estresa más sin motivo?",
    "¿Quién siempre quiere tener la última palabra?",
    "¿Quién se frustraría jugando algo fácil?",
    "¿Quién sería peor manteniendo la calma?",
    "¿Quién se dejaría llevar por la presión del grupo?",
    "¿Quién acabaría hablando solo en público?",
    "¿Quién sería peor negociando?",
    "¿Quién se pondría dramático por un mensaje en visto?",
    "¿Quién tiene más probabilidades de malinterpretar todo?",
    "¿Quién sería peor compañero de viaje?",
    "¿Quién se rayaría por nada?",
    "¿Quién se obsesiona más?",
    "¿Quién sería el más intenso?",
    "¿Quién acabaría pidiendo perdón sin saber por qué?",

    // 111–210 (100 preguntas nuevas)
    "¿Quién olería peor después de no ducharse una semana?",
    "¿Quién se comería un sándwich del suelo?",
    "¿Quién sería más probable que tropiece con nada?",
    "¿Quién habla como si fuera la cosa más importante del mundo?",
    "¿Quién tiene el sentido del humor más retrasado?",
    "¿Quién se da de cabezazos contra las puertas?",
    "¿Quién se pondría a llorar viendo un anuncio de seguros?",
    "¿Quién sería peor haciendo un baile viral?",
    "¿Quién se cae subiendo escaleras?",
    "¿Quién se merecería una patada en el culo regularmente?",
    "¿Quién confundiría la sal con el azúcar en la sopa?",
    "¿Quién llamaría a la policía por comida fría?",
    "¿Quién tiene un fetiche vergonzoso?",
    "¿Quién se pegaría con una puerta automática?",
    "¿Quién se quedaría atrapado en un armario?",
    "¿Quién baila como si tuviera un espasmo?",
    "¿Quién se comería la pasta sin cocinar?",
    "¿Quién diría la ley de Murphy como consejo de vida?",
    "¿Quién se haría pis en el sofá riéndose?",
    "¿Quién sería incapaz de abrir una lata de conservas?",
    "¿Quién llamaría al servicio técnico para reiniciar el móvil?",
    "¿Quién se pondría a llorar jugando videojuegos en modo fácil?",
    "¿Quién se acuerda de toda en el grupo menos de los cumpleaños?",
    "¿Quién se cree que su mal humor es una personalidad?",
    "¿Quién buscaría 'cómo respirar' en Google?",
    "¿Quién diría 'no duele' justo antes de desmayarse?",
    "¿Quién sería más probable que se quemara una tostada?",
    "¿Quién se cae por intentar ir guay?",
    "¿Quién vería un video de miedo y tendría pesadillas una semana?",
    "¿Quién perdería la batalla contra un troll de internet?",
    "¿Quién se quedaría con hambre porque la comida 'se ve extraña'?",
    "¿Quién sería la mascota perfecta para un asilo?",
    "¿Quién se engancharía a un juego para móviles tipo Candy Crush?",
    "¿Quién se burlaba en redes de alguien que luego conoce?",
    "¿Quién tiene fotos de su mascota en el carnet de identidad?",
    "¿Quién se ahogaría con agua?",
    "¿Quién sería más probable que ganara una tragaperra?",
    "¿Quién diría 'soy muy guapo/a' en serio?",
    "¿Quién sería peor en un karaoke?",
    "¿Quién se olvidaría el nombre de alguien mirándole a la cara?",
    "¿Quién se cree que todo es una señal del universo?",
    "¿Quién se haría análisis de sangre por un moretón?",
    "¿Quién se vestiría con pijama a una boda?",
    "¿Quién diría mentiras piadosas constantemente?",
    "¿Quién se comportaría como un pequeño tirano borracho?",
    "¿Quién gritaría viendo una película de terror?",
    "¿Quién pedazo de carne es con personalidad de lechuga?",
    "¿Quién haría un TikTok horrible?",
    "¿Quién se burlaría de su mejor amigo en las redes?",
    "¿Quién tendría un feed lleno de contenido cringe?",
    "¿Quién se cree millonario siendo pobre?",
    "¿Quién se quejaría de estar cansado sin hacer nada?",
    "¿Quién sería peor en una fuga de la cárcel?",
    "¿Quién se cree que sabe de ciencia viendo TikToks?",
    "¿Quién se tatuaría un error ortográfico?",
    "¿Quién dejaría morir una planta cactus?",
    "¿Quién sería la peor persona para pedir dinero prestado?",
    "¿Quién se lo gastaría todo en cosas inútiles de Wish?",
    "¿Quién lidaría con la noticia de que come algo de lo que tiene alergia?",
    "¿Quién se tropezaría en una cuerda invisible?",
    "¿Quién diría que necesita 'vibraciones positivas'?",
    "¿Quién se creería adivino después de acertar algo una vez?",
    "¿Quién sería más probable que cagase en un examen oral?",
    "¿Quién se comería toda la comida del congelador porque se aburre?",
    "¿Quién sería incapaz de despedirse de una llamada telefónica?",
    "¿Quién se bufaría por WhatsApp?",
    "¿Quién se rascaría en los sitios más inapropiados?",
    "¿Quién sería peor en un job interview?",
    "¿Quién se vestiría con chanclas a una reunión importante?",
    "¿Quién tendría un olor corporal insoportable?",
    "¿Quién se deprimiría por una pregunta de un quiz de internet?",
    "¿Quién sería el primero en borrar sus chats?",
    "¿Quién presionaría los botones del ascensor múltiples veces?",
    "¿Quién se engancharía a una serie basura?",
    "¿Quién comería directamente de la olla?",
    "¿Quién sería más probable que se durmiera en una conversación?",
    "¿Quién se cree que su comida hecha mal es un arte?",
    "¿Quién gritaría en un cine?",
    "¿Quién se comeríaun cubo de hielo en un restaurante fancy?",
    "¿Quién sería peor limpiando?",
    "¿Quién sería incapaz de seguir instrucciones simples?",
    "¿Quién abriría la puerta del frigorífico 50 veces en 5 minutos?",
    "¿Quién se perdería en IKEA?",
    "¿Quién se comería toda una caja de galletas de una sentada?",
    "¿Quién sería peor armando un mueble?",
    "¿Quién se cree que es superior pero no puede ni atarse los cordones?",
    "¿Quién diría 'no tenía hambre' comiendo todo?",
    "¿Quién se ofrecería a llevar algo y no lo haría?",
    "¿Quién se cree que la música que escucha es superior a la de todos?"

];
