module.exports = [
    { word: "MANZANA", forbidden: ["Fruta", "Roja", "Comer", "Blancanieves"] },
    { word: "FÚTBOL", forbidden: ["Pelota", "Deporte", "Gol", "Messi"] },
    { word: "INTERNET", forbidden: ["Wifi", "Ordenador", "Red", "Conexión"] },
    { word: "PLAYA", forbidden: ["Mar", "Arena", "Verano", "Sol"] },
    { word: "CHOCOLATE", forbidden: ["Dulce", "Cacao", "Leche", "Marrón"] },
    { word: "GATO", forbidden: ["Animal", "Perro", "Maullar", "Bigotes"] },
    { word: "AMOR", forbidden: ["Corazón", "Sentimiento", "Pareja", "Rojo"] },
    { word: "ESPAÑA", forbidden: ["País", "Europa", "Madrid", "Península"] },
    { word: "CINE", forbidden: ["Película", "Palomitas", "Actor", "Pantalla"] },
    { word: "AVIÓN", forbidden: ["Volar", "Ala", "Aeropuerto", "Viaje"] },
    { word: "RELOJ", forbidden: ["Hora", "Tiempo", "Manecillas", "Pulsera"] },
    { word: "DOUTZEN KROES", forbidden: ["Modelo", "Victoria", "Angel", "Rubia"] }, // Un guiño difícil
    { word: "HARRY POTTER", forbidden: ["Mago", "Libro", "Gafas", "Varita"] },
    { word: "PIZZA", forbidden: ["Italia", "Queso", "Masa", "Redonda"] },
    { word: "MICKEY MOUSE", forbidden: ["Ratón", "Disney", "Orejas", "Dibujo"] },
    { word: "COCHE", forbidden: ["Ruedas", "Conducir", "Motor", "Vehículo"] },
    { word: "ZAPATO", forbidden: ["Pie", "Caminar", "Cordones", "Suela"] },
    { word: "GUITARRA", forbidden: ["Música", "Cuerdas", "Instrumento", "Tocar"] },
    { word: "HOSPITAL", forbidden: ["Médico", "Enfermo", "Curar", "Edificio"] },
    { word: "NAVIDAD", forbidden: ["Regalos", "Árbol", "Diciembre", "Papá Noel"] },
    { word: "FANTASMA", forbidden: ["Miedo", "Sábana", "Espíritu", "Muerto"] },
    { word: "LECHE", forbidden: ["Vaca", "Blanca", "Beber", "Calcio"] },
    { word: "SOL", forbidden: ["Estrella", "Calor", "Luz", "Día"] },
    { word: "LUNA", forbidden: ["Noche", "Satélite", "Cielo", "Menguante"] },
    { word: "MONO", forbidden: ["Banana", "Selva", "Animal", "Trepar"] },
    { word: "PAYASO", forbidden: ["Circo", "Risa", "Nariz", "Maquillaje"] },
    { word: "BODA", forbidden: ["Novio", "Novia", "Casarse", "Anillo"] },
    { word: "DRÁCULA", forbidden: ["Vampiro", "Sangre", "Colmillos", "Conde"] },
    { word: "PIRATA", forbidden: ["Barco", "Tesoro", "Loro", "Parche"] },
    { word: "ESPEJO", forbidden: ["Reflejo", "Mirar", "Vidrio", "Cristal"] },
    { word: "SUBMARINO", forbidden: ["Barco", "Agua", "Bajo", "Mar"] },
    { word: "ELEFANTE", forbidden: ["Trompa", "Animal", "Grande", "Orejas"] },
    { word: "JIRAFA", forbidden: ["Cuello", "Alta", "Animal", "África"] },
    { word: "HELADO", forbidden: ["Frío", "Verano", "Cucurucho", "Postre"] },
    { word: "BOMBERO", forbidden: ["Fuego", "Apagar", "Camión", "Manguera"] },
    { word: "LLAVE", forbidden: ["Abrir", "Puerta", "Cerradura", "Metal"] },
    { word: "GAFAS", forbidden: ["Ojos", "Ver", "Lentes", "Sol"] },
    { word: "CAMA", forbidden: ["Dormir", "Mueble", "Colchón", "Noche"] },
    { word: "SILLA", forbidden: ["Sentarse", "Mesa", "Mueble", "Patas"] },
    { word: "LIBRO", forbidden: ["Leer", "Páginas", "Historia", "Papel"] },
    { word: "TELÉFONO", forbidden: ["Llamar", "Móvil", "Hablar", "Mensaje"] },
    { word: "ÁRBOL", forbidden: ["Hojas", "Tronco", "Bosque", "Madera"] },
    { word: "FLOR", forbidden: ["Jardín", "Oler", "Pétalos", "Primavera"] },
    { word: "PERRO", forbidden: ["Animal", "Ladrar", "Mascota", "Hueso"] },
    { word: "ORDENADOR", forbidden: ["Teclado", "Pantalla", "Ratón", "Internet"] },
    { word: "BICICLETA", forbidden: ["Ruedas", "Pedales", "Casco", "Manillar"] },
    { word: "CASA", forbidden: ["Vivir", "Techo", "Puerta", "Habitación"] },
    { word: "ESCUELA", forbidden: ["Aprender", "Profesor", "Alumnos", "Clase"] },
        { word: "CAFÉ", forbidden: ["Beber", "Mañana", "Taza", "Cafeína"] },
    { word: "PAN", forbidden: ["Comer", "Trigo", "Horno", "Bocadillo"] },
    { word: "QUESO", forbidden: ["Leche", "Ratón", "Amarillo", "Cortar"] },
    { word: "HAMBURGUESA", forbidden: ["Carne", "Pan", "Comida", "Fast food"] },
    { word: "TACO", forbidden: ["México", "Comida", "Tortilla", "Carne"] },
    { word: "SUSHI", forbidden: ["Japón", "Arroz", "Pescado", "Soja"] },
    { word: "CERVEZA", forbidden: ["Alcohol", "Bar", "Espuma", "Beber"] },
    { word: "VINO", forbidden: ["Uva", "Alcohol", "Botella", "Copa"] },
    { word: "COCINA", forbidden: ["Comida", "Fuego", "Horno", "Platos"] },
    { word: "BAÑO", forbidden: ["Ducha", "Agua", "WC", "Lavabo"] },
    { word: "CAMISA", forbidden: ["Ropa", "Botones", "Vestir", "Manga"] },
    { word: "PANTALÓN", forbidden: ["Ropa", "Piernas", "Vaquero", "Cintura"] },
    { word: "CHAQUETA", forbidden: ["Abrigo", "Frío", "Ropa", "Cremallera"] },
    { word: "SOMBRERO", forbidden: ["Cabeza", "Sol", "Gorra", "Vestir"] },
    { word: "BUFANDA", forbidden: ["Cuello", "Frío", "Lana", "Invierno"] },
    { word: "BIBLIOTECA", forbidden: ["Libros", "Silencio", "Leer", "Estudiar"] },
    { word: "MUSEO", forbidden: ["Arte", "Exposición", "Cuadros", "Historia"] },
    { word: "ESTADIO", forbidden: ["Deporte", "Gradas", "Público", "Partido"] },
    { word: "AEROPUERTO", forbidden: ["Avión", "Viaje", "Maletas", "Terminal"] },
    { word: "HOTEL", forbidden: ["Dormir", "Habitación", "Viaje", "Recepción"] },
    { word: "BOSQUE", forbidden: ["Árboles", "Naturaleza", "Verde", "Sendero"] },
    { word: "DESIERTO", forbidden: ["Arena", "Calor", "Sequía", "Cactus"] },
    { word: "MONTAÑA", forbidden: ["Altura", "Nieve", "Cima", "Escalar"] },
    { word: "RÍO", forbidden: ["Agua", "Fluir", "Puente", "Corriente"] },
    { word: "LAGO", forbidden: ["Agua", "Dulce", "Pez", "Orilla"] },
    { word: "POLICÍA", forbidden: ["Ley", "Uniforme", "Multa", "Patrulla"] },
    { word: "JUEZ", forbidden: ["Juicio", "Ley", "Martillo", "Tribunal"] },
    { word: "ABOGADO", forbidden: ["Defender", "Ley", "Juicio", "Cliente"] },
    { word: "PROFESOR", forbidden: ["Clase", "Enseñar", "Escuela", "Pizarra"] },
    { word: "ALUMNO", forbidden: ["Estudiar", "Clase", "Escuela", "Aprender"] },
    { word: "DRAGÓN", forbidden: ["Fuego", "Volador", "Fantasia", "Escamas"] },
    { word: "UNICORNIO", forbidden: ["Cuerno", "Fantasia", "Caballo", "Mágico"] },
    { word: "ZOMBI", forbidden: ["Muerto", "Cerebros", "Apocalipsis", "Caminar"] },
    { word: "HOMBRE LOBO", forbidden: ["Luna", "Transformación", "Peludo", "Bestia"] },
    { word: "AJEDREZ", forbidden: ["Tablero", "Rey", "Piezas", "Jaque"] },
    { word: "CARTAS", forbidden: ["Baraja", "Poker", "Juego", "Naipes"] },
    { word: "DADOS", forbidden: ["Juego", "Suerte", "Número", "Mesa"] },
    { word: "VIDEOJUEGO", forbidden: ["Consola", "Jugar", "Pantalla", "Mando"] },
    { word: "PUZZLE", forbidden: ["Piezas", "Montar", "Imagen", "Juego"] },
    { word: "YOUTUBE", forbidden: ["Videos", "Internet", "Canal", "Streamer"] },
    { word: "INSTAGRAM", forbidden: ["Fotos", "Red social", "Likes", "Stories"] },
    { word: "TIKTOK", forbidden: ["Videos", "Baile", "Red social", "Corto"] },
    { word: "TWITCH", forbidden: ["Directo", "Streamer", "Chat", "Gaming"] },
    { word: "DINERO", forbidden: ["Pagar", "Billetes", "Banco", "Rico"] },
    { word: "BANCO", forbidden: ["Dinero", "Cuenta", "Préstamo", "Cajero"] },
    { word: "TARJETA", forbidden: ["Pagar", "Banco", "Crédito", "Débito"] },
    { word: "FACTURA", forbidden: ["Pagar", "Recibo", "Gastos", "Cuenta"] },
    { word: "COHETE", forbidden: ["Espacio", "Despegar", "NASA", "Fuego"] },
    { word: "ASTRONAUTA", forbidden: ["Espacio", "Traje", "Luna", "NASA"] },
    { word: "PLANETA", forbidden: ["Espacio", "Órbita", "Tierra", "Sistema"] },
    { word: "GALAXIA", forbidden: ["Espacio", "Estrellas", "Universo", "Vía Láctea"] },
    { word: "MAGIA", forbidden: ["Hechizo", "Truco", "Mago", "Ilusión"] },
    { word: "ESPADA", forbidden: ["Arma", "Cortar", "Metal", "Guerrero"] },
    { word: "ESCUDO", forbidden: ["Defensa", "Protección", "Guerra", "Metal"] },
    { word: "CIRUJANO", forbidden: ["Operar", "Hospital", "Médico", "Bisturí"] },
    { word: "ENFERMERO", forbidden: ["Hospital", "Cuidar", "Médico", "Paciente"] },
    { word: "REINA", forbidden: ["Corona", "Rey", "Palacio", "Monarquía"] },
    { word: "REY", forbidden: ["Corona", "Reina", "Trono", "Monarquía"] },
    { word: "TORMENTA", forbidden: ["Lluvia", "Trueno", "Rayo", "Nubes"] },
    { word: "VIENTO", forbidden: ["Aire", "Soplar", "Fuerte", "Brisa"] },
    { word: "NIEVE", forbidden: ["Frío", "Blanco", "Invierno", "Caer"] },
    { word: "GRANIZO", forbidden: ["Hielo", "Tormenta", "Piedras", "Lluvia"] },
    { word: "ARCOÍRIS", forbidden: ["Colores", "Lluvia", "Cielo", "Sol"] },
    { word: "CAMELLO", forbidden: ["Desierto", "Joroba", "Arena", "Animal"] },
    { word: "DELFIN", forbidden: ["Mar", "Animal", "Saltos", "Inteligente"] },
    { word: "TIBURÓN", forbidden: ["Mar", "Dientes", "Peligro", "Pez"] },
    { word: "BALLENA", forbidden: ["Grande", "Mar", "Cantar", "Animal"] },
    { word: "PINGÜINO", forbidden: ["Frío", "Antártida", "Animal", "Traje"] },
    { word: "CEMENTO", forbidden: ["Construcción", "Gris", "Obra", "Secar"] },
    { word: "LADRILLO", forbidden: ["Rojo", "Construcción", "Pared", "Casa"] },
    { word: "HORMIGÓN", forbidden: ["Construcción", "Duro", "Obra", "Mezcla"] },
    { word: "VAMPIRO", forbidden: ["Sangre", "Noche", "Colmillos", "Ataúd"] },
    { word: "MOMIA", forbidden: ["Vendas", "Egipto", "Antiguo", "Muerto"] },
    { word: "BRUJA", forbidden: ["Escoba", "Hechizo", "Sombrero", "Magia"] },
    { word: "HECHICERO", forbidden: ["Magia", "Hechizos", "Poder", "Libro"] },
    { word: "CAMIÓN", forbidden: ["Grande", "Carga", "Ruedas", "Conducir"] },
    { word: "MOTO", forbidden: ["Casco", "Rápida", "Ruedas", "Motor"] },
    { word: "TRACTOR", forbidden: ["Campo", "Agricultura", "Grande", "Ruedas"] },
    { word: "SEMÁFORO", forbidden: ["Rojo", "Verde", "Cruce", "Coches"] },
    { word: "PASO PEATONES", forbidden: ["Cruzar", "Rayas", "Calle", "Semáforo"] },
    { word: "ACERA", forbidden: ["Caminar", "Calle", "Peatones", "Ciudad"] },
    { word: "MICROONDAS", forbidden: ["Calentar", "Comida", "Cocina", "Rápido"] },
    { word: "LAVADORA", forbidden: ["Ropa", "Lavar", "Electrodoméstico", "Agua"] },
    { word: "NEVERA", forbidden: ["Frío", "Comida", "Cocina", "Electrodoméstico"] },
    { word: "TELEVISIÓN", forbidden: ["Ver", "Pantalla", "Canales", "Mando"] },
    { word: "ALTAVOZ", forbidden: ["Sonido", "Música", "Volumen", "Escuchar"] },
    { word: "AURICULARES", forbidden: ["Oídos", "Música", "Escuchar", "Cables"] },
    { word: "EXAMEN", forbidden: ["Estudiar", "Notas", "Escuela", "Probar"] },
    { word: "APROBADO", forbidden: ["Examen", "Notas", "Pasar", "Bien"] },
    { word: "SUSPENSO", forbidden: ["Examen", "Mal", "Notas", "Repetir"] },
    { word: "MENTIRA", forbidden: ["Engañar", "Falso", "Verdad", "Decir"] },
    { word: "SECRETO", forbidden: ["Ocultar", "Contar", "Privado", "Guardar"] },
    { word: "PROMESA", forbidden: ["Cumplir", "Decir", "Palabra", "Futuro"] },
    { word: "CUMPLEAÑOS", forbidden: ["Fiesta", "Velas", "Tarta", "Años"] },
    { word: "ANIVERSARIO", forbidden: ["Años", "Celebrar", "Fecha", "Pareja"] },
    { word: "DESPEDIDA", forbidden: ["Adiós", "Marcharse", "Triste", "Final"] },
    { word: "MATRÍCULA", forbidden: ["Coche", "Número", "Placa", "Registro"] },
    { word: "PASAPORTE", forbidden: ["Viajar", "País", "Documento", "Frontera"] },
    { word: "DNI", forbidden: ["Documento", "Identidad", "Número", "Persona"] },
    { word: "CÁRCEL", forbidden: ["Presos", "Encerrar", "Delito", "Prisión"] },
    { word: "MULTA", forbidden: ["Pagar", "Castigo", "Dinero", "Infracción"] },
    { word: "JUICIO", forbidden: ["Juez", "Ley", "Tribunal", "Caso"] },
    { word: "TATUAJE", forbidden: ["Piel", "Tinta", "Dibujo", "Permanente"] },
    { word: "PIERCING", forbidden: ["Agujero", "Metal", "Oreja", "Nariz"] },
    { word: "DISCOTECA", forbidden: ["Bailar", "Noche", "Música", "Fiesta"] },
    { word: "CONCIERTO", forbidden: ["Música", "Directo", "Escenario", "Público"] },
    { word: "FESTIVAL", forbidden: ["Música", "Días", "Escenarios", "Gente"] },
    { word: "RESACA", forbidden: ["Alcohol", "Dolor", "Cabeza", "Día siguiente"] },
    { word: "BORRACHO", forbidden: ["Alcohol", "Beber", "Mareo", "Fiesta"] },
    { word: "MENTE", forbidden: ["Pensar", "Cerebro", "Ideas", "Cabeza"] },
    { word: "MEMORIA", forbidden: ["Recordar", "Pasado", "Cerebro", "Olvidar"] },
    { word: "SUEÑO", forbidden: ["Dormir", "Noche", "Soñar", "Cansancio"] },
    { word: "ESPELUZNANTE", forbidden: ["Miedo", "Terror", "Horror", "Asustar"] },
    { word: "RIDÍCULO", forbidden: ["Vergüenza", "Hacer", "Risa", "Situación"] },
    { word: "IMPUESTOS", forbidden: ["Pagar", "Estado", "Dinero", "Hacienda"] },
    { word: "HIPOTECA", forbidden: ["Casa", "Banco", "Pagar", "Años"] },
    { word: "BOMBA", forbidden: ["Explosión", "Peligro", "Guerra", "Estallar"] },
    { word: "MISIL", forbidden: ["Guerra", "Explosión", "Arma", "Lanzar"] },
    { word: "ESPÍA", forbidden: ["Secreto", "Infiltrado", "Información", "Agente"] },
    { word: "DETECTIVE", forbidden: ["Investigar", "Caso", "Pistas", "Resolver"] },
    { word: "ROBO", forbidden: ["Robar", "Ladrón", "Delito", "Policía"] },
    { word: "SECUESTRO", forbidden: ["Retener", "Persona", "Crimen", "Rescate"] },
    { word: "SORTEO", forbidden: ["Azar", "Premio", "Ganar", "Número"] },
    { word: "LOTERÍA", forbidden: ["Dinero", "Número", "Sorteo", "Ganar"] },
    { word: "FRACASO", forbidden: ["Perder", "Intento", "Mal", "Error"] },
    { word: "ÉXITO", forbidden: ["Ganar", "Logro", "Triunfo", "Conseguir"] },
    { word: "VIAJE", forbidden: ["Moverse", "Destino", "Maleta", "Ir"] },
    { word: "EXCURSIÓN", forbidden: ["Día", "Salida", "Grupo", "Visita"] },
    { word: "AVENTURA", forbidden: ["Riesgo", "Viaje", "Emoción", "Historia"] },
    { word: "MISTERIO", forbidden: ["Secreto", "Incógnita", "Resolver", "Raro"] },
    { word: "FUEGO", forbidden: ["Quemar", "Calor", "Llama", "Incendio"] },
{ word: "HUMO", forbidden: ["Fuego", "Nube", "Oler", "Negro"] },
{ word: "CHISPA", forbidden: ["Fuego", "Pequeña", "Electricidad", "Saltan"] },
{ word: "VENENO", forbidden: ["Matar", "Tóxico", "Sustancia", "Peligro"] },
{ word: "VACUNA", forbidden: ["Inyección", "Virus", "Enfermedad", "Prevenir"] },
{ word: "MEDICINA", forbidden: ["Curar", "Pastilla", "Doctor", "Tratamiento"] },
{ word: "LABERINTO", forbidden: ["Perderse", "Camino", "Salida", "Muros"] },
{ word: "TRAMPA", forbidden: ["Caer", "Engaño", "Atrapar", "Secreto"] },
{ word: "ENIGMA", forbidden: ["Misterio", "Resolver", "Secreto", "Pregunta"] },
{ word: "RUINA", forbidden: ["Viejo", "Antiguo", "Restos", "Historia"] },
{ word: "CASTILLO", forbidden: ["Rey", "Murallas", "Medieval", "Torre"] },
{ word: "SIRENA", forbidden: ["Mar", "Cantar", "Cola", "Mitología"] },
{ word: "MINOTAURO", forbidden: ["Laberinto", "Toro", "Criatura", "Mitología"] },
{ word: "VENDA", forbidden: ["Herida", "Cubrir", "Sangre", "Gasa"] },
{ word: "MORATÓN", forbidden: ["Golpe", "Azul", "Dolor", "Piel"] },
{ word: "CARRETERA", forbidden: ["Asfalto", "Coches", "Viajar", "Larga"] },
{ word: "ROTONDA", forbidden: ["Circular", "Coches", "Cruce", "Salida"] },
{ word: "MALETA", forbidden: ["Viaje", "Ropa", "Equipaje", "Cerrar"] },
{ word: "BOLSO", forbidden: ["Llevar", "Mano", "Cosas", "Moda"] },
{ word: "ROMPECABEZAS", forbidden: ["Piezas", "Montar", "Imagen", "Juego"] },
{ word: "RULETA", forbidden: ["Casino", "Girar", "Número", "Azar"] },
{ word: "CASINO", forbidden: ["Juego", "Dinero", "Apuestas", "Ruleta"] },
{ word: "PREMIO", forbidden: ["Ganar", "Regalo", "Resultado", "Concurso"] },
{ word: "ENTREVISTA", forbidden: ["Trabajo", "Preguntas", "Empresa", "Currículum"] },
{ word: "ASCENSO", forbidden: ["Trabajo", "Subir", "Puesto", "Mejora"] },
{ word: "DESPIDO", forbidden: ["Trabajo", "Echar", "Empresa", "Paro"] },
{ word: "HUELGA", forbidden: ["Trabajo", "Parar", "Protesta", "Derechos"] },
{ word: "FAMA", forbidden: ["Conocido", "Popular", "Gente", "Reconocimiento"] },
{ word: "ANONIMATO", forbidden: ["Desconocido", "Oculto", "Nombre", "Nadie"] },
{ word: "RUMOR", forbidden: ["Hablar", "Gente", "Secreto", "Decir"] },
{ word: "CHISME", forbidden: ["Hablar", "Gente", "Cotilleo", "Secreto"] },
{ word: "ESCÁNDALO", forbidden: ["Polémica", "Noticias", "Problema", "Público"] },
{ word: "POLÉMICA", forbidden: ["Opiniones", "Discusión", "Tema", "Problema"] },
{ word: "CENSURA", forbidden: ["Prohibir", "Ocultar", "Control", "Contenido"] },
{ word: "LIBERTAD", forbidden: ["Elegir", "Derechos", "Hacer", "Decidir"] },
{ word: "PRIVACIDAD", forbidden: ["Datos", "Personal", "Oculto", "Intimidad"] },
{ word: "IDENTIDAD", forbidden: ["Persona", "Nombre", "Quién", "Ser"] },
{ word: "CONTRASEÑA", forbidden: ["Clave", "Acceso", "Seguridad", "Cuenta"] },
{ word: "HACKEO", forbidden: ["Entrar", "Ilegal", "Sistema", "Cuenta"] },
{ word: "SERVIDOR", forbidden: ["Internet", "Datos", "Conexión", "Red"] },
{ word: "NUBE", forbidden: ["Internet", "Archivos", "Guardar", "Online"] },
{ word: "DESCARGA", forbidden: ["Internet", "Archivo", "Bajar", "Esperar"] },
{ word: "ACTUALIZACIÓN", forbidden: ["Sistema", "Cambios", "Nueva", "Versión"] },
{ word: "BUG", forbidden: ["Error", "Fallo", "Programa", "Arreglar"] },
{ word: "PARCHE", forbidden: ["Arreglar", "Actualizar", "Error", "Sistema"] },
{ word: "CONFIGURACIÓN", forbidden: ["Ajustes", "Cambiar", "Opciones", "Sistema"] },
{ word: "USUARIO", forbidden: ["Cuenta", "Persona", "Acceso", "Sistema"] },
{ word: "ADMINISTRADOR", forbidden: ["Permisos", "Control", "Sistema", "Acceso"] },
{ word: "PERFIL", forbidden: ["Usuario", "Cuenta", "Datos", "Persona"] },
{ word: "ALGORITMO", forbidden: ["Cálculo", "Proceso", "Reglas", "Pasos"] },
{ word: "CÓDIGO", forbidden: ["Programar", "Lenguaje", "Escribir", "Software"] },
{ word: "VARIABLE", forbidden: ["Cambiar", "Valor", "Código", "Dato"] },
{ word: "BUCLE", forbidden: ["Repetir", "Código", "Ciclo", "Mientras"] },
{ word: "ERROR", forbidden: ["Fallo", "Problema", "Equivocación", "Mal"] },
{ word: "SOLUCIÓN", forbidden: ["Resolver", "Problema", "Arreglar", "Respuesta"] },
{ word: "ESTRATEGIA", forbidden: ["Plan", "Pensar", "Objetivo", "Ganar"] },
{ word: "TACTICA", forbidden: ["Movimiento", "Plan", "Acción", "Juego"] },
{ word: "DERROTA", forbidden: ["Perder", "Fracaso", "Resultado", "Mal"] },
{ word: "VICTORIA", forbidden: ["Ganar", "Triunfo", "Resultado", "Éxito"] },
{ word: "RIESGO", forbidden: ["Peligro", "Intentar", "Azar", "Posible"] },
{ word: "OPORTUNIDAD", forbidden: ["Momento", "Aprovechar", "Posibilidad", "Única"] },
{ word: "CAOS", forbidden: ["Desorden", "Lío", "Nada", "Control"] },
{ word: "ORDEN", forbidden: ["Organizar", "Colocar", "Sistema", "Control"] },
{ word: "DESTINO", forbidden: ["Futuro", "Camino", "Final", "Escrito"] },
{ word: "CASUALIDAD", forbidden: ["Azar", "Suerte", "Coincidencia", "Sin plan"] },
{ word: "RECUERDO", forbidden: ["Pasado", "Memoria", "Pensar", "Vivir"] },
{ word: "NOSTALGIA", forbidden: ["Pasado", "Sentir", "Recuerdo", "Triste"] },
{ word: "SUSURRO", forbidden: ["Bajo", "Hablar", "Oído", "Secreto"] },
{ word: "GRITO", forbidden: ["Fuerte", "Voz", "Miedo", "Oír"] },
{ word: "OLOR", forbidden: ["Nariz", "Oler", "Aroma", "Sentido"] },
{ word: "TEXTURA", forbidden: ["Tocar", "Superficie", "Suave", "Rugoso"] },
{ word: "HAMACA", forbidden: ["Colgar", "Descansar", "Balancear", "Cuerdas"] },
{ word: "COLCHONETA", forbidden: ["Agua", "Flotar", "Piscina", "Inflable"] },
{ word: "SPA", forbidden: ["Relajarse", "Agua", "Masaje", "Descanso"] },
{ word: "SAUNA", forbidden: ["Calor", "Vapor", "Sudor", "Madera"] },
{ word: "MAREA", forbidden: ["Subir", "Bajar", "Agua", "Luna"] },
{ word: "CORRIENTE", forbidden: ["Mover", "Agua", "Fluir", "Arrastrar"] },
{ word: "MAPA", forbidden: ["Camino", "Lugar", "Orientarse", "Papel"] },
{ word: "COORDENADAS", forbidden: ["Ubicación", "Números", "Mapa", "Posición"] },
{ word: "MOJADO", forbidden: ["Agua", "Empapado", "Secar", "Lluvia"] },
{ word: "HÚMEDO", forbidden: ["Agua", "Pegajoso", "Ambiente", "Mojado"] },
{ word: "OXÍGENO", forbidden: ["Respirar", "Aire", "Gas", "Pulmones"] },
{ word: "CARBONO", forbidden: ["Elemento", "Átomo", "Vida", "Tabla"] },
{ word: "IMÁN", forbidden: ["Metal", "Atraer", "Pegar", "Fuerza"] },
{ word: "INERCIA", forbidden: ["Movimiento", "Física", "Parar", "Velocidad"] },
{ word: "PULSO", forbidden: ["Latido", "Muñeca", "Corazón", "Ritmo"] },
{ word: "REFLEXO", forbidden: ["Reacción", "Rápido", "Automático", "Movimiento"] },
{ word: "DESTELLO", forbidden: ["Luz", "Breve", "Brillar", "Flash"] },
{ word: "PENUMBRA", forbidden: ["Oscuridad", "Poca luz", "Ambiente", "Sombra"] },
{ word: "ALTITUD", forbidden: ["Altura", "Nivel", "Montaña", "Aire"] },
{ word: "LONGITUD", forbidden: ["Medida", "Distancia", "Extensión", "Largo"] },
{ word: "CARGA", forbidden: ["Peso", "Transportar", "Llevar", "Objeto"] },
{ word: "VOLTAJE", forbidden: ["Electricidad", "Corriente", "Potencia", "Cable"] },
{ word: "BATERÍA", forbidden: ["Energía", "Cargar", "Duración", "Porcentaje"] },
{ word: "INTERRUPTOR", forbidden: ["Encender", "Apagar", "Luz", "Botón"] },
{ word: "CRISTALINO", forbidden: ["Claro", "Transparente", "Limpio", "Ver"] },
{ word: "TRANSLÚCIDO", forbidden: ["Dejar pasar", "Luz", "Parcial", "Ver"] },
{ word: "ENGRANAJE", forbidden: ["Ruedas", "Dientes", "Mecánico", "Movimiento"] },
{ word: "POLEA", forbidden: ["Cuerda", "Subir", "Bajar", "Rueda"] },
{ word: "CALIBRE", forbidden: ["Medida", "Tamaño", "Diámetro", "Precisión"] },
{ word: "ESCALA", forbidden: ["Proporción", "Medir", "Mapa", "Tamaño"] },
{ word: "PLANO", forbidden: ["Dibujo", "Construcción", "Vista", "Técnico"] },
{ word: "MAQUETA", forbidden: ["Modelo", "Pequeño", "Representar", "Escala"] },
{ word: "BORDE", forbidden: ["Límite", "Extremo", "Final", "Contorno"] },
{ word: "PERIFERIA", forbidden: ["Exterior", "Borde", "Lejos", "Zona"] },
{ word: "TRÁNSITO", forbidden: ["Mover", "Paso", "Circular", "Flujo"] },
{ word: "DESVÍO", forbidden: ["Cambiar", "Ruta", "Camino", "Alternativo"] },
{ word: "FILTRO", forbidden: ["Separar", "Pasar", "Limpio", "Retener"] },
{ word: "DISOLUCIÓN", forbidden: ["Mezclar", "Líquido", "Deshacer", "Sustancia"] },
{ word: "CATALIZADOR", forbidden: ["Reacción", "Acelerar", "Proceso", "Química"] },
{ word: "EQUILIBRIO", forbidden: ["Estable", "Balance", "Caer", "Mantener"] },
{ word: "SIMETRÍA", forbidden: ["Igual", "Reflejo", "Forma", "Mitad"] },
{ word: "SECUENCIA", forbidden: ["Orden", "Pasos", "Serie", "Continuo"] },
{ word: "INTERVALO", forbidden: ["Tiempo", "Espacio", "Entre", "Pausa"] },
{ word: "AMPLITUD", forbidden: ["Altura", "Onda", "Intensidad", "Nivel"] },
{ word: "CONDUCTOR", forbidden: ["Transmitir", "Electricidad", "Material", "Pasar"] },
{ word: "AISLANTE", forbidden: ["Bloquear", "Electricidad", "Proteger", "Material"] },
{ word: "NÚCLEO", forbidden: ["Centro", "Interior", "Parte", "Principal"] },
{ word: "ENVOLTURA", forbidden: ["Cubrir", "Proteger", "Exterior", "Capa"] },
{ word: "DESGASTE", forbidden: ["Uso", "Deterioro", "Tiempo", "Rozar"] },
{ word: "PRESIÓN", forbidden: ["Fuerza", "Empujar", "Apretar", "Carga"] },
{ word: "EXPANSIÓN", forbidden: ["Aumentar", "Crecer", "Extender", "Espacio"] },
{ word: "CONTRACCIÓN", forbidden: ["Reducir", "Encoger", "Disminuir", "Tamaño"] },
{ word: "TRANSMISIÓN", forbidden: ["Enviar", "Pasar", "Señal", "Transferir"] },
{ word: "RECEPTOR", forbidden: ["Recibir", "Señal", "Entrada", "Destino"] },
{ word: "ORIGEN", forbidden: ["Inicio", "Comienzo", "Fuente", "Nacer"] },
{ word: "DESTINO FINAL", forbidden: ["Llegar", "Final", "Meta", "Terminar"] },
{ word: "VARIABLE OCULTA", forbidden: ["Factor", "Invisible", "Influir", "Resultado"] },
{ word: "CONSTANTE", forbidden: ["Fijo", "No cambiar", "Valor", "Siempre"] },
{ word: "PARÁMETRO", forbidden: ["Ajuste", "Valor", "Condición", "Control"] },
{ word: "CONDICIÓN", forbidden: ["Requisito", "Si", "Cumplir", "Caso"] },
{ word: "ITERACIÓN", forbidden: ["Repetir", "Ciclo", "Proceso", "Vez"] },
{ word: "RESULTADO", forbidden: ["Final", "Conclusión", "Salida", "Obtener"] },
{ word: "ALBA", forbidden: ["Amanecer", "Mañana", "Luz", "Sol"] },
{ word: "CREPÚSCULO", forbidden: ["Luz", "Oscuro", "Tarde", "Cielo"] },
{ word: "AURORA", forbidden: ["Luz", "Cielo", "Fenómeno", "Norte"] },
{ word: "BRUMA", forbidden: ["Niebla", "Ver", "Humedad", "Aire"] },
{ word: "CALIMA", forbidden: ["Polvo", "Aire", "Calor", "Visibilidad"] },
{ word: "SEQUÍA", forbidden: ["Agua", "Lluvia", "Seco", "Campo"] },
{ word: "INUNDACIÓN", forbidden: ["Agua", "Exceso", "Cubrir", "Daños"] },

{ word: "GERMINAR", forbidden: ["Planta", "Crecer", "Semilla", "Tierra"] },
{ word: "COSECHA", forbidden: ["Recoger", "Campo", "Cultivo", "Plantas"] },
{ word: "HERRUMBRE", forbidden: ["Óxido", "Metal", "Viejo", "Corroer"] },
{ word: "PÁTINA", forbidden: ["Capa", "Tiempo", "Superficie", "Color"] },

{ word: "CANTERA", forbidden: ["Piedra", "Extraer", "Roca", "Obra"] },
{ word: "ARENA MOVEDIZA", forbidden: ["Hundirse", "Trampa", "Suelo", "Peligro"] },
{ word: "VÉRTIGO", forbidden: ["Altura", "Mareo", "Caer", "Sensación"] },
{ word: "DESORIENTACIÓN", forbidden: ["Perderse", "Dirección", "Confusión", "Ubicación"] },
{ word: "IMPULSO", forbidden: ["Empuje", "Movimiento", "Fuerza", "Inicio"] },
{ word: "INCLINACIÓN", forbidden: ["Pendiente", "Lado", "Caer", "Ángulo"] },

{ word: "UMBRAL", forbidden: ["Entrada", "Límite", "Puerta", "Paso"] },
{ word: "PASADIZO", forbidden: ["Estrecho", "Camino", "Interior", "Conectar"] },

{ word: "CÚPULA", forbidden: ["Techo", "Redondo", "Edificio", "Cubrir"] },
{ word: "COLUMNATA", forbidden: ["Columnas", "Fila", "Arquitectura", "Soporte"] },
{ word: "VITRINA", forbidden: ["Cristal", "Exponer", "Objeto", "Mostrar"] },
{ word: "PEDESTAL", forbidden: ["Soporte", "Base", "Elevar", "Objeto"] },

{ word: "REPLIEGUE", forbidden: ["Retirarse", "Volver", "Mover", "Atrás"] },
{ word: "AVANCE", forbidden: ["Progresar", "Mover", "Adelante", "Ganar"] },

{ word: "COORDINACIÓN", forbidden: ["Sincronizar", "Mover", "Control", "Orden"] },
{ word: "PRECISIÓN", forbidden: ["Exactitud", "Acierto", "Detalle", "Fino"] },

{ word: "DESTREZA", forbidden: ["Habilidad", "Manos", "Práctica", "Control"] },
{ word: "TORPEZA", forbidden: ["Mal", "Caerse", "Falta", "Habilidad"] },

{ word: "RITMO", forbidden: ["Compás", "Tiempo", "Repetir", "Constante"] },
{ word: "CADENCIA", forbidden: ["Ritmo", "Regular", "Secuencia", "Pulso"] },

{ word: "FUGAZ", forbidden: ["Rápido", "Corto", "Durar", "Poco"] },
{ word: "EFÍMERO", forbidden: ["Temporal", "Breve", "Durar", "Poco"] },

{ word: "DENSIDAD", forbidden: ["Concentración", "Espeso", "Cantidad", "Volumen"] },
{ word: "VISCOSIDAD", forbidden: ["Espeso", "Fluir", "Lento", "Líquido"] },

{ word: "SUSTRAER", forbidden: ["Quitar", "Restar", "Reducir", "Sacar"] },
{ word: "AGREGAR", forbidden: ["Añadir", "Sumar", "Unir", "Poner"] },

{ word: "COMPRESIÓN", forbidden: ["Apretar", "Reducir", "Espacio", "Fuerza"] },
{ word: "DILATACIÓN", forbidden: ["Expandir", "Aumentar", "Calor", "Tamaño"] },

{ word: "RESILIENCIA", forbidden: ["Resistir", "Recuperar", "Adaptar", "Golpe"] },
{ word: "FRAGILIDAD", forbidden: ["Romper", "Débil", "Cuidado", "Delicado"] },

{ word: "UMBRA", forbidden: ["Sombra", "Oscuro", "Zona", "Luz"] },
{ word: "CLARIDAD", forbidden: ["Luz", "Ver", "Transparente", "Nítido"] },

{ word: "CONTRASTE", forbidden: ["Diferencia", "Opuesto", "Resaltar", "Comparar"] },
{ word: "GRADIENTE", forbidden: ["Transición", "Cambio", "Suave", "Escala"] },

{ word: "ALINEACIÓN", forbidden: ["Recto", "Colocar", "Orden", "Fila"] },
{ word: "DESFASE", forbidden: ["Diferencia", "Tiempo", "Retraso", "Fase"] },

{ word: "LATENCIA", forbidden: ["Retraso", "Tiempo", "Esperar", "Respuesta"] },
{ word: "FLUCTUACIÓN", forbidden: ["Variar", "Subir", "Bajar", "Cambiar"] },

{ word: "ESTÍMULO", forbidden: ["Reacción", "Provocar", "Activar", "Respuesta"] },
{ word: "RESPUESTA", forbidden: ["Reaccionar", "Contestar", "Acción", "Resultado"] },

{ word: "INTUICIÓN", forbidden: ["Presentir", "Saber", "Sin pensar", "Sensación"] },
{ word: "DEDUCCIÓN", forbidden: ["Conclusión", "Pensar", "Lógica", "Inferir"] },

{ word: "PARADOJA", forbidden: ["Contradicción", "Lógica", "Raro", "Idea"] },
{ word: "ANOMALÍA", forbidden: ["Extraño", "Error", "No normal", "Caso"] },

{ word: "SINGULARIDAD", forbidden: ["Único", "Especial", "Punto", "Excepción"] },
{ word: "REGULARIDAD", forbidden: ["Constante", "Normal", "Repetir", "Patrón"] },

{ word: "VINCULO", forbidden: ["Unión", "Relación", "Conectar", "Lazo"] },
{ word: "DESVINCULACIÓN", forbidden: ["Separar", "Romper", "Relación", "Alejar"] },

{ word: "UMBRÍA", forbidden: ["Sombra", "Oscuro", "Zona", "Fresca"] },
{ word: "SOLANA", forbidden: ["Sol", "Luz", "Calor", "Expuesta"] },

{ word: "SEDIMENTO", forbidden: ["Depositar", "Fondo", "Partículas", "Acumular"] },
{ word: "EROSIÓN", forbidden: ["Desgaste", "Agua", "Viento", "Tiempo"] },

{ word: "AFLUENTE", forbidden: ["Unirse", "Corriente", "Río", "Entrada"] },
{ word: "DELTA", forbidden: ["Desembocadura", "Ramificación", "Agua", "Sedimento"] },

{ word: "RESONANCIA", forbidden: ["Vibración", "Eco", "Amplificar", "Frecuencia"] },
{ word: "ARMÓNICO", forbidden: ["Sonido", "Vibración", "Tono", "Onda"] },

{ word: "SATURACIÓN", forbidden: ["Lleno", "Exceso", "Máximo", "Limite"] },
{ word: "ESCARCHE", forbidden: ["Hielo", "Frío", "Mañana", "Superficie"] },

{ word: "DESTILACIÓN", forbidden: ["Separar", "Líquidos", "Proceso", "Evaporar"] },
{ word: "FERMENTACIÓN", forbidden: ["Proceso", "Transformar", "Tiempo", "Cambio"] },

{ word: "COAGULACIÓN", forbidden: ["Espesar", "Solidificar", "Cambio", "Líquido"] },
{ word: "EMULSIÓN", forbidden: ["Mezcla", "Unir", "Líquidos", "Suspensión"] },

{ word: "TRAYECTORIA", forbidden: ["Camino", "Movimiento", "Recorrido", "Ruta"] },
{ word: "DESPLAZAMIENTO", forbidden: ["Mover", "Cambiar", "Posición", "Lugar"] },
{ word: "DERIVA", forbidden: ["Desviarse", "Mover", "Lento", "Dirección"] },

{ word: "INICIO", forbidden: ["Comienzo", "Empezar", "Principio", "Arrancar"] },
{ word: "FINALIZACIÓN", forbidden: ["Terminar", "Acabar", "Cerrar", "Fin"] },
{ word: "TRANSICIÓN", forbidden: ["Cambio", "Paso", "Etapa", "Entre"] },

{ word: "CONTORNO", forbidden: ["Borde", "Perfil", "Forma", "Línea"] },
{ word: "SILUETA", forbidden: ["Forma", "Sombra", "Figura", "Perfil"] },
{ word: "VOLUMEN", forbidden: ["Espacio", "Cuerpo", "Tamaño", "Tres dimensiones"] },

{ word: "COMPONENTE", forbidden: ["Parte", "Elemento", "Pieza", "Sistema"] },
{ word: "ENSAMBLE", forbidden: ["Unir", "Piezas", "Montar", "Juntar"] },
{ word: "DESMONTAJE", forbidden: ["Separar", "Piezas", "Quitar", "Abrir"] },

{ word: "ESTABILIDAD", forbidden: ["Equilibrio", "Firme", "Caer", "Mantener"] },
{ word: "OSCILACIÓN", forbidden: ["Mover", "Balancear", "Repetir", "Ir y venir"] },
{ word: "VIBRACIÓN", forbidden: ["Mover", "Temblar", "Rápido", "Ondas"] },

{ word: "INTENSIDAD", forbidden: ["Fuerza", "Nivel", "Grado", "Cantidad"] },
{ word: "MAGNITUD", forbidden: ["Tamaño", "Medida", "Importancia", "Valor"] },
{ word: "PROPORCIÓN", forbidden: ["Relación", "Parte", "Comparar", "Equilibrio"] },

{ word: "DISTRIBUCIÓN", forbidden: ["Repartir", "Colocar", "Extender", "Orden"] },
{ word: "CONCENTRACIÓN", forbidden: ["Acumular", "Reunir", "Juntar", "Cantidad"] },
{ word: "DISPERSIÓN", forbidden: ["Separar", "Extender", "Alejar", "Esparcir"] },

{ word: "APERTURA", forbidden: ["Abrir", "Inicio", "Hueco", "Entrada"] },
{ word: "CIERRE", forbidden: ["Cerrar", "Final", "Bloquear", "Terminar"] },

{ word: "PERSISTENCIA", forbidden: ["Durar", "Mantener", "Tiempo", "Continuar"] },
{ word: "INTERRUPCIÓN", forbidden: ["Parar", "Cortar", "Romper", "Detener"] },

{ word: "ACUMULACIÓN", forbidden: ["Sumar", "Juntar", "Guardar", "Cantidad"] },
{ word: "REDUCCIÓN", forbidden: ["Disminuir", "Menos", "Quitar", "Bajar"] },

{ word: "AMPLIFICACIÓN", forbidden: ["Aumentar", "Intensificar", "Más", "Potenciar"] },
{ word: "ATENUACIÓN", forbidden: ["Reducir", "Bajar", "Suavizar", "Disminuir"] },

{ word: "PERCEPCIÓN", forbidden: ["Sentir", "Captar", "Notar", "Interpretar"] },
{ word: "INTERPRETACIÓN", forbidden: ["Entender", "Significado", "Explicar", "Leer"] },

{ word: "COHERENCIA", forbidden: ["Lógico", "Consistente", "Conectar", "Sentido"] },
{ word: "INCOHERENCIA", forbidden: ["Sin sentido", "Contradecir", "Caos", "Error"] },

{ word: "SÍNTESIS", forbidden: ["Resumen", "Unir", "Reducir", "Conclusión"] },
{ word: "ANÁLISIS", forbidden: ["Examinar", "Separar", "Estudiar", "Detalle"] },

{ word: "OBSERVACIÓN", forbidden: ["Mirar", "Ver", "Analizar", "Atención"] },
{ word: "REGISTRO", forbidden: ["Guardar", "Anotar", "Datos", "Archivo"] },

{ word: "ARCHIVO", forbidden: ["Guardar", "Documento", "Datos", "Almacenar"] },
{ word: "RESPALDO", forbidden: ["Copia", "Seguridad", "Guardar", "Proteger"] },

{ word: "RECUPERACIÓN", forbidden: ["Volver", "Restaurar", "Obtener", "Datos"] },
{ word: "PÉRDIDA", forbidden: ["Desaparecer", "No tener", "Extraviar", "Falta"] },

{ word: "SINCRONÍA", forbidden: ["Coincidir", "Tiempo", "Juntos", "A la vez"] },
{ word: "ASINCRONÍA", forbidden: ["No coincidir", "Separado", "Retraso", "Diferente"] },

{ word: "INTEGRACIÓN", forbidden: ["Unir", "Incorporar", "Parte", "Sistema"] },
{ word: "SEGMENTACIÓN", forbidden: ["Dividir", "Separar", "Partes", "Cortar"] },

{ word: "ORIENTACIÓN", forbidden: ["Dirección", "Guiar", "Ubicar", "Posición"] },
{ word: "REFERENCIA", forbidden: ["Punto", "Guía", "Tomar", "Comparar"] },

{ word: "ESCENARIO", forbidden: ["Situación", "Contexto", "Marco", "Caso"] },
{ word: "CONTEXTO", forbidden: ["Entorno", "Situación", "Marco", "Circunstancia"] },

{ word: "PROYECCIÓN", forbidden: ["Lanzar", "Mostrar", "Extender", "Futuro"] },
{ word: "SIMULACIÓN", forbidden: ["Imitar", "Recrear", "Modelo", "Prueba"] },

{ word: "HIPÓTESIS", forbidden: ["Suposición", "Idea", "Probar", "Teoría"] },
{ word: "VERIFICACIÓN", forbidden: ["Comprobar", "Confirmar", "Revisar", "Validar"] },

{ word: "CORRELACIÓN", forbidden: ["Relación", "Conectar", "Vincular", "Comparar"] },
{ word: "CAUSALIDAD", forbidden: ["Causa", "Efecto", "Provocar", "Origen"] },

{ word: "ITERACIÓN MÚLTIPLE", forbidden: ["Repetir", "Varias", "Ciclo", "Proceso"] },
{ word: "OPTIMIZACIÓN", forbidden: ["Mejorar", "Ajustar", "Eficiencia", "Rendimiento"] },

{ word: "EFICIENCIA", forbidden: ["Rendimiento", "Aprovechar", "Óptimo", "Resultado"] },
{ word: "REDUNDANCIA", forbidden: ["Repetir", "Duplicar", "Extra", "Sobra"] },

{ word: "ESCALABILIDAD", forbidden: ["Crecer", "Aumentar", "Soportar", "Capacidad"] },
{ word: "LIMITACIÓN", forbidden: ["Restricción", "Tope", "Freno", "Máximo"] },

{ word: "INTERFAZ", forbidden: ["Conectar", "Interacción", "Contacto", "Punto"] },
{ word: "MEDIACIÓN", forbidden: ["Intervenir", "Intermedio", "Conectar", "Resolver"] },

{ word: "AUTONOMÍA", forbidden: ["Independencia", "Solo", "Control", "Propio"] },
{ word: "DEPENDENCIA", forbidden: ["Necesitar", "Otro", "Apoyarse", "Falta"] },

{ word: "MODULARIDAD", forbidden: ["Bloques", "Separar", "Partes", "Estructura"] },
{ word: "MONOLÍTICO", forbidden: ["Todo", "Único", "Bloque", "Compacto"] },

{ word: "PRIORIDAD", forbidden: ["Importancia", "Primero", "Antes", "Orden"] },
{ word: "SECUNDARIO", forbidden: ["Menos", "Después", "No principal", "Apoyo"] },

    { word: "CRUSH", forbidden: ["Gustar", "Persona", "Amor", "Secreto"] },
    { word: "STALKER", forbidden: ["Mirar", "Instagram", "Perfil", "Cotillear"] },
    { word: "EX", forbidden: ["Pasado", "Relación", "Antiguo", "Pareja"] },
    { word: "LÍO", forbidden: ["Relación", "Nada serio", "Besos", "Confusión"] },
    { word: "AMIGO CON DERECHOS", forbidden: ["Sexo", "Amistad", "Sin compromiso", "Lío"] },
    { word: "BORRACHERA", forbidden: ["Alcohol", "Beber", "Fiesta", "Mareo"] },
    { word: "MENSAJE BORRADO", forbidden: ["WhatsApp", "Enviar", "Arrepentir", "Chat"] },

    { word: "CAPULLO", forbidden: ["Persona", "Idiota", "Insulto", "Mal"] },
    { word: "COTILLA", forbidden: ["Chisme", "Hablar", "Gente", "Rumor"] },
    { word: "VERGÜENZA AJENA", forbidden: ["Incómodo", "Otro", "Mirar", "Situación"] },
    { word: "FRIENDZONE", forbidden: ["Amigo", "No gustar", "Rechazo", "Relación"] },
    { word: "LAGUNA MENTAL", forbidden: ["Olvidar", "Alcohol", "Noche", "Memoria"] },
    { word: "HACER EL RIDÍCULO", forbidden: ["Vergüenza", "Quedar mal", "Situación", "Gente"] },
    { word: "AUTOENGAÑO", forbidden: ["Mentirse", "Excusa", "Creer", "Verdad"] },
    { word: "CELOS", forbidden: ["Envidia", "Pareja", "Control", "Inseguridad"] },
    { word: "DRAMA", forbidden: ["Problema", "Exagerar", "Llorar", "Género"] },
    { word: "TÓXICO", forbidden: ["Relación", "Daño", "Mal", "Persona"] },

    { word: "CALENTÓN", forbidden: ["Deseo", "Momento", "Impulso", "Sexo"] },
    { word: "CORTE DE ROLLO", forbidden: ["Arruinar", "Momento", "Incómodo", "Situación"] },
    { word: "QUÍMICA", forbidden: ["Atracción", "Personas", "Sentir", "Conexión"] },
    { word: "CITA DESASTROSA", forbidden: ["Salir", "Mal", "Incómodo", "Persona"] },
    { word: "EXPECTATIVA", forbidden: ["Esperar", "Imaginar", "Resultado", "Ilusión"] },
    { word: "REALIDAD", forbidden: ["Verdad", "Lo que hay", "Chasco", "Resultado"] },
    { word: "CRINGE", forbidden: ["Vergüenza", "Incómodo", "Dar pena", "Situación"] },
    { word: "HACERSE EL LOCO", forbidden: ["Ignorar", "Disimular", "No responder", "Evitar"] },
    { word: "SINCERIDAD BRUTAL", forbidden: ["Verdad", "Decir", "Doler", "Directo"] },
    { word: "SILENCIO INCÓMODO", forbidden: ["Hablar", "Nadie", "Momento", "Miradas"] },

    { word: "SUBIDÓN", forbidden: ["Euforia", "Alegría", "Emoción", "Momento"] },
    { word: "BAJÓN", forbidden: ["Tristeza", "Ánimo", "Cansancio", "De repente"] },
    { word: "PROCRASTINAR", forbidden: ["Retrasar", "No hacer", "Tareas", "Excusas"] },
    { word: "COTILLEO", forbidden: ["Hablar", "Gente", "Secreto", "Rumor"] },
    { word: "MENTIR PIADOSAMENTE", forbidden: ["Verdad", "No herir", "Decir", "Persona"] },
    { word: "HUMILLACIÓN", forbidden: ["Vergüenza", "Ridículo", "Público", "Mal"] },
    { word: "SUBIR HISTORIA", forbidden: ["Instagram", "Foto", "Story", "Red social"] },
    { word: "LIKE ESTRATÉGICO", forbidden: ["Instagram", "Indirecta", "Foto", "Interés"] },
    { word: "BORRAR CONVERSACIÓN", forbidden: ["Chat", "WhatsApp", "Ocultar", "Mensajes"] },
    { word: "DOBLE CARA", forbidden: ["Falso", "Persona", "Hipócrita", "Mentir"] },
    { word: "CALENTÓN", forbidden: ["Deseo", "Ganas", "Momento", "Impulso"] },
    { word: "FOLLAR", forbidden: ["Sexo", "Cama", "Hacer", "Noche"] },
    { word: "POLVO", forbidden: ["Rápido", "Sexo", "Echar", "Cama"] },
    { word: "CACHONDO", forbidden: ["Excitado", "Caliente", "Ganas", "Sexo"] },
    { word: "HUMEDAD", forbidden: ["Excitación", "Mojado", "Deseo", "Calor"] },
    { word: "CALENTARSE", forbidden: ["Excitarse", "Subir", "Ganas", "Deseo"] },
    { word: "LENGÜETAZO", forbidden: ["Boca", "Lengua", "Lamer", "Besos"] },
    { word: "MORREO", forbidden: ["Besos", "Lengua", "Boca", "Pasión"] },
    { word: "MAGREO", forbidden: ["Tocar", "Manos", "Cuerpo", "Besos"] },

    { word: "FANTASÍA", forbidden: ["Imaginar", "Deseo", "Pensar", "Sexo"] },
    { word: "TENSIÓN SEXUAL", forbidden: ["Miradas", "Atracción", "Ambiente", "Ganas"] },
    { word: "ROCE", forbidden: ["Contacto", "Cuerpo", "Casual", "Accidental"] },
    { word: "SUDAR", forbidden: ["Calor", "Cuerpos", "Encima", "Cama"] },
    { word: "GEMIDO", forbidden: ["Sonido", "Placer", "Boca", "Cama"] },
    { word: "MORDER", forbidden: ["Dientes", "Cuello", "Labios", "Pasión"] },
    { word: "CHUPETÓN", forbidden: ["Cuello", "Marca", "Besos", "Morado"] },
    { word: "DESNUDAR", forbidden: ["Quitar", "Ropa", "Cuerpo", "Lento"] },
    { word: "LENTITO", forbidden: ["Despacio", "Saborear", "Momento", "Placer"] },

    { word: "RÁPIDO Y SUCIO", forbidden: ["Polvo", "Prisa", "Ganas", "Calor"] },
    { word: "JUGUETEAR", forbidden: ["Manos", "Provocar", "Tocar", "Calentar"] },
    { word: "PROVOCAR", forbidden: ["Insinuar", "Ganas", "Deseo", "Miradas"] },
    { word: "TONTEO", forbidden: ["Coquetear", "Insinuar", "Juego", "Miradas"] },
    { word: "DESFASE", forbidden: ["Noche", "Límite", "Control", "Sexo"] },
    { word: "CAMA AJENA", forbidden: ["Dormir", "Otro", "Infidelidad", "Noche"] },
    { word: "MADRUGADA", forbidden: ["Tarde", "Cama", "Noche", "Sexo"] },
    { word: "SIN ROPA", forbidden: ["Desnudo", "Cuerpo", "Nada", "Encima"] },
    { word: "GANAS", forbidden: ["Deseo", "Calor", "Impulso", "Momento"] },

    { word: "JUGADA", forbidden: ["Movimiento", "Cama", "Habilidad", "Truco"] },
    { word: "ENGANCHE", forbidden: ["Química", "Repetir", "Deseo", "Vicio"] },
    { word: "REPETIR", forbidden: ["Otra vez", "Más", "Ganas", "Noche"] },
    { word: "EN CALIENTE", forbidden: ["Impulso", "Pensar poco", "Momento", "Deseo"] },
    { word: "PASARSE", forbidden: ["Límite", "Más", "Exceso", "Control"] },
    { word: "SABOR", forbidden: ["Boca", "Cuerpo", "Lengua", "Piel"] },
    { word: "ARRIMAR", forbidden: ["Cuerpo", "Cerca", "Contacto", "Intención"] },
    { word: "RECALENTADO", forbidden: ["Deseo", "Otra vez", "Sobras", "Ganas"] },
    { word: "DESCONTROL", forbidden: ["Frenos", "Límite", "Cabeza", "Noche"] }
];